### ISSUE TITLE
Single-side buffering closes shape only sometimes

### ISSUE THREAD

**Issue by nubblesite** [locationtech/jts#1008]
I am performing single-sided buffering and then looping through the new offset curve to remove all points within offsetDistance - 0.01 of each point on the original curve. This results in a nice single-sided buffer like so:

![image](https://github.com/locationtech/jts/assets/144922796/ed55bdfb-3af8-49ac-be2e-667ad6d372be)

The problem is that when I increase the offset distance beyond a certain amount, the first and last points become connected by a line segment (the photo above is 7.5 offset distance, the one below is 8.0):
![image](https://github.com/locationtech/jts/assets/144922796/2cf110bf-4648-46f4-9043-6cb9edd3fc50)

I'm aware that buffering will always return either a polygon or multipolygon (closed shape). That being said, I would like to prevent the first and last points from "connecting" together entirely. Any ideas as to why this would happen only beyond a certain offset distance?

**Comment by nubblesite** [comment]
OK, this issue is caused by the final offset curve not maintaining point order past a certain offset distance. I guess there's no way to ensure that the first and last points in the offset curve correspond to the first and last points in the original curve, since the buffer operation doesn't guarantee point order. Is that right?

**Comment by dr-jts** [comment]
You'll have to provide more information about what API you are using, and what the input data is.
