### ISSUE TITLE
CoordinateArraySequence.getCoordinate is hard to understand

### ISSUE THREAD

**Issue by tohidemyname** [locationtech/jts#1020]
I find that the following weird method:

  public void getCoordinate(int index, Coordinate coord) {
    coord.setCoordinate(coordinates[index]);
  }

Its name starts with get, but calling this method does not return any values. Instead, it sets the value of a parameter. This method can be better named as setCoordinate

**Comment by mprins** [comment]
The method modifies the coordinate argument to hold (get) the value from the array sequence; since it directly modifies the argument it does not need to return the argument.
using `setCoordinate` does not make it more transparent as that still suggests a bean pattern method which it isn't
