### ISSUE TITLE
AppSweep identifies Medium security vulnerability: HTTP URLs to opengis were found

### ISSUE THREAD

**Issue by DropkickSteve** [locationtech/jts#1021]
In my Android app the security scan found a http vulnerability. The source code contains the following:
public static final String GML_NAMESPACE = "http://www.opengis.net/gml"

Is there a chance this might be updated to a https secure url?

**Comment by mprins** [comment]
It is not a URL it is a namespace reference ID URI, it cannot be changed.
Please read http://www.rpbourret.com/xml/NamespaceMyths.htm

**Comment by DropkickSteve** [comment]
@mprins Thank you for the immediate response!
