### ISSUE TITLE
ConstrainedDelaunayTriangulator causes an IllegalStateException: Unable to find a convex corner

### ISSUE THREAD

**Issue by sunil-chormale-polestar** [locationtech/jts#1027]
For the Polygon mentioned below when triangulated using ConstrainedDelaunayTriangulator upon getting the results from this triangulator it is causing this IllegalStateException: Unable to find a convex corner.

WKT: 

`POLYGON ((-122.85354855421944 76.3454140255136, -122.85354855421944 76.43850111082759, -122.54884197795562 76.43850111082759, -122.54884197795562 76.3650152796655, -122.55675816555662 76.36593103449002, -122.55517411229525 76.36449551595541, -122.54884197795562 76.36403251312015, -122.54884197795562 76.36064488319522, -122.55503845226254 76.36127471905326, -122.56250703317288 76.36281001556992, -122.56200575825883 76.36178374252577, -122.56161785098287 76.36121773710903, -122.56872594314741 76.36086225488953, -122.54884197795562 76.359569392616, -122.54884197795562 76.35652087709721, -122.55209982394744 76.35682880900248, -122.55408096296588 76.3552247287384, -122.56699013738466 76.3549939393188, -122.57645964599574 76.35274124101554, -122.57161176237258 76.35082745582281, -122.5890346764089 76.35236716261458, -122.58912265258815 76.35051691542338, -122.59429895872972 76.3493191002963, -122.58808255156816 76.34776425341784, -122.58670400863899 76.3454140255136, -122.59097070114032 76.3454140255136, -122.59120976951498 76.34695863713145, -122.59633445726912 76.34862184512215, -122.59814846537908 76.34873163705558, -122.60061872047743 76.3472987409443, -122.60741293395955 76.34698021456535, -122.62497174724814 76.34742033468098, -122.62413394422592 76.34604215602081, -122.61686679346604 76.3454140255136, -122.62785896259469 76.3454140255136, -122.62788414953361 76.34547913095716, -122.6295030116897 76.3454140255136, -122.85354855421944 76.3454140255136), (-122.55778682270345 76.37123751659814, -122.5588933233679 76.37113964517857, -122.5589877368943 76.37048041783714, -122.55277192598334 76.3680286411091, -122.55778682270345 76.37123751659814), (-122.56743145000114 76.36747944312191, -122.56740164736797 76.36716985690356, -122.56685852969724 76.36695837952573, -122.56584966213192 76.36682140828142, -122.56453716725619 76.3666566614759, -122.56300187073961 76.36645281304709, -122.56148552923356 76.3662489655175, -122.56063270573453 76.36625242251128, -122.56057965742498 76.36647832411555, -122.56104397739742 76.36683094469248, -122.56172084763868 76.36719596422253, -122.56302607059658 76.36742401160903, -122.56519365346401 76.36753284936162, -122.56712162456313 76.36777412847351, -122.56743145000114 76.36747944312191), (-122.56550133222034 76.3582458491667, -122.56469833835737 76.35827231441573, -122.56524395974076 76.35976231118187, -122.56713581046907 76.3603066204542, -122.56550133222034 76.3582458491667), (-122.58141076549423 76.35646045208836, -122.58086323754813 76.35590183730014, -122.58003842793084 76.35552597014745, -122.57881975212965 76.35525214636957, -122.57751667495435 76.35508286967877, -122.57645177872652 76.35500061498647, -122.57590675359369 76.35507845850441, -122.57599937926766 76.3552969694797, -122.57655644452407 76.35557866052679, -122.57718205430804 76.35588967756667, -122.57784640778524 76.356245756037, -122.57843005700133 76.35664200812238, -122.57900524179817 76.3569941520586, -122.57942831526441 76.35730481116823, -122.58127021764622 76.35781681499424, -122.58151805371502 76.35719335099239, -122.58141076549423 76.35646045208836), (-122.58064520321328 76.37327825998398, -122.58038115506605 76.37363231138215, -122.58245062819364 76.37419295324236, -122.5826586485776 76.37398040297342, -122.58251893530036 76.37372207631302, -122.5820256472657 76.3734375236229, -122.58153307419173 76.37319850900411, -122.58105254214085 76.37311804306336, -122.58064520321328 76.37327825998398), (-122.59072625621154 76.36022055173723, -122.59100306034281 76.36001551170676, -122.59083640607498 76.35981261745852, -122.58996665463718 76.35968327516306, -122.58866071671848 76.35968327516306, -122.58779096617997 76.35981261745852, -122.58762431101289 76.36001551170676, -122.58790135346443 76.36022055173723, -122.59072625621154 76.36022055173723), (-122.59776914123267 76.35523080815547, -122.609964609179 76.35529565826829, -122.60980403432853 76.35511326766334, -122.59881174596507 76.3541183467845, -122.5916991230158 76.35458493214898, -122.59163653829538 76.35541725200468, -122.59754407419948 76.35717105859763, -122.59902811025887 76.35725557778287, -122.59776914123267 76.35523080815547), (-122.60148525234233 76.35845232001884, -122.60124611811348 76.35798192062936, -122.60016393691593 76.35758054240821, -122.59646105753158 76.35773205748853, -122.59594023225569 76.3581167460911, -122.59655666355894 76.35919582822495, -122.59704995159382 76.35957765608424, -122.60148525234233 76.35845232001884), (-122.59794020667483 76.36102986333754, -122.59756577034365 76.36063897570835, -122.59669864132901 76.36036860982355, -122.59606397177468 76.36037242384856, -122.59606635587727 76.36058604700878, -122.59654867667994 76.36088001739921, -122.59703660025868 76.36118686158449, -122.59783315677451 76.36137664281787, -122.59794020667483 76.36102986333754), (-122.60366165665992 76.36750483547982, -122.60391664503692 76.36707854244091, -122.6037813429344 76.36665856803864, -122.60310983624974 76.36652576964858, -122.60224664176887 76.36676025348322, -122.60188233809934 76.36715483642661, -122.6019963028868 76.36751317938973, -122.60366165665992 76.36750483547982), (-122.60858655012895 76.35414421578301, -122.60819196718528 76.35386240512616, -122.60713446158586 76.35361444944749, -122.60602366935665 76.35356044785638, -122.60537445506682 76.35373830767676, -122.60530114143425 76.3540654180845, -122.60560107253137 76.35438227622132, -122.60845005552532 76.35438466032392, -122.60858655012895 76.35414421578301), (-122.61882865461854 76.35582435171258, -122.620237946224 76.35579860232383, -122.61882770043788 76.35436725574445, -122.62447512182924 76.35472655288824, -122.62787055987833 76.35338723663182, -122.63751602174675 76.35546112093417, -122.6375268693693 76.3508470061845, -122.63575482362592 76.34988570196386, -122.62997555712596 76.34880304322579, -122.62846994363272 76.34880816936176, -122.61774027349458 76.35050606690166, -122.6088004116095 76.35259485207084, -122.61535835250575 76.35387313403788, -122.61651945101161 76.35459744891332, -122.61882865461854 76.35582435171258), (-122.61218833942013 76.36085164558722, -122.6119939086918 76.36064517473514, -122.61111533670322 76.36051225673535, -122.60992383931358 76.36051845576225, -122.60945796980918 76.36068665956174, -122.60992741591721 76.36097812623973, -122.6119320389322 76.36105835475922, -122.61218833942013 76.36085164558722), (-122.61131536930854 76.35597276682978, -122.61100864383376 76.35632562662644, -122.61186432807605 76.35661041763677, -122.6121264696606 76.35628914832581, -122.61209404460416 76.35596883319519, -122.61173844367396 76.35583090777033, -122.61131536930854 76.35597276682978), (-122.61248111730954 76.36189210453722, -122.61211752860086 76.36243343345635, -122.61424112292934 76.36308014403369, -122.61451542334791 76.36255145058911, -122.61444115643404 76.36197054430517, -122.61389482008963 76.36162543306745, -122.61310291306876 76.36160290235219, -122.61248111730954 76.36189210453722), (-122.61484873278253 76.34816026718283, -122.61454200730746 76.3485131260802, -122.61539745322965 76.34879791709037, -122.61565983313466 76.34847664867848, -122.61562716975796 76.34815633264878, -122.61527180714795 76.34801840812312, -122.61484873278253 76.34816026718283), (-122.62126982204434 76.3567334412954, -122.6260228155003 76.3572038415842, -122.62508642699679 76.35571730181226, -122.62340974806116 76.35582017885837, -122.62098741513688 76.35651290414758, -122.62126982204434 76.3567334412954), (-122.62866044072656 76.34690415889992, -122.6285573244607 76.34635686837484, -122.6279151437686 76.34615123299325, -122.62697815901457 76.34638142616211, -122.62622654431947 76.34684514988393, -122.62838637862828 76.34743905047202, -122.62866044072656 76.34690415889992), (-122.64572083984476 76.35824215385242, -122.64037907103703 76.35821425958056, -122.63939464074979 76.35634624987958, -122.6269263032062 76.35863542558468, -122.63526666172673 76.3610273596251, -122.63050544217212 76.36381673825213, -122.63197624650635 76.36573314676747, -122.6324503421094 76.36610603356658, -122.64216315780328 76.36598527440108, -122.64383900126867 76.36163115545372, -122.65080165866938 76.36203110195382, -122.64725065229561 76.36272895337865, -122.6502335074702 76.36379647292927, -122.65830695620092 76.36375665634475, -122.65277135381467 76.36152231680151, -122.66457056967582 76.36150503183188, -122.65770185005998 76.35985004904063, -122.65164661399977 76.35987651339045, -122.6491956709431 76.35696160829164, -122.64459252342597 76.35635924328452, -122.64572083984476 76.35824215385242), (-122.63269114458033 76.37056612952333, -122.63353705409149 76.37183523211044, -122.63642835648321 76.37252294997424, -122.63898885225346 76.3704714776766, -122.63443922968644 76.3702820543736, -122.63269114458033 76.37056612952333), (-122.6376533509212 76.36761927600887, -122.64077067362749 76.3697502609659, -122.6412589551365 76.3712824584189, -122.64747834175188 76.37227165691144, -122.64452600507082 76.36797821522251, -122.6376533509212 76.36761927600887), (-122.6412913801929 76.35115885779527, -122.64152836773972 76.35087585463737, -122.64104127873185 76.3507261274089, -122.64022576810447 76.35074484320029, -122.6395783425663 76.35095596354694, -122.63919937634994 76.35132765784519, -122.64037132247834 76.35152065775227, -122.6412913801929 76.35115885779527), (-122.65217053923881 76.34736061070384, -122.6521378758621 76.34704005725294, -122.6517822740326 76.346902251438, -122.65135943888684 76.34704422920782, -122.65105271341169 76.34739696939474, -122.65190815933387 76.34768176040525, -122.65217053923881 76.34736061070384), (-122.65243947520143 76.36914217447185, -122.65301465999839 76.36962354199298, -122.65643560911582 76.37105262318018, -122.66239655036043 76.36967670901328, -122.67278695125653 76.36991214792744, -122.67042386566861 76.3684009316577, -122.6599822043151 76.36933934723316, -122.66273653546241 76.36794793594851, -122.66214942925258 76.36782515061043, -122.65243947520143 76.36914217447185), (-122.65249836460768 76.35692644120249, -122.65280032187728 76.35743212729098, -122.6572177414054 76.3587696547958, -122.65887475036914 76.35759413206367, -122.65533185048429 76.3569153543603, -122.65249836460768 76.35692644120249), (-122.65603232343273 76.36550653020248, -122.66049087075687 76.36503255331007, -122.65865397490074 76.36448335622191, -122.65476572545762 76.36443448076676, -122.65603232343273 76.36550653020248), (-122.66751086713253 76.36054456218184, -122.66769325773745 76.36227977259381, -122.67411434610001 76.36225295031353, -122.6779335734754 76.36249363407416, -122.67807090264976 76.36216855073826, -122.67384064193196 76.36051893240284, -122.67288231806432 76.3603798153764, -122.66751086713253 76.36054456218184), (-122.66983687906848 76.35517311125014, -122.66980445401207 76.35485255690014, -122.66944885218257 76.35471475108504, -122.66902577871655 76.35485672975449, -122.66871905324147 76.35520946994114, -122.66957473748397 76.35549426095147, -122.66983687906848 76.35517311125014), (-122.67075252560821 76.35774874710711, -122.67101466629366 76.35731375222804, -122.67098224123725 76.35686564433414, -122.67062664030702 76.35667395563866, -122.670203566841 76.35687315457261, -122.66989684136593 76.35738182101449, -122.67075252560821 76.35774874710711), (-122.67256605617831 76.36336863035814, -122.67238914963929 76.36394393476508, -122.6726893190566 76.36447274691986, -122.67488074295166 76.36432766918674, -122.67631339984325 76.36377441885443, -122.67645776261543 76.36333513241041, -122.67521715145014 76.36305284511289, -122.67356574526272 76.36304330870195, -122.67256605617831 76.36336863035814), (-122.67639231715151 76.36727786098461, -122.67572331417938 76.36757147344483, -122.6758835319991 76.3679752348693, -122.67785227296376 76.36805546248976, -122.6781324144791 76.36773645857085, -122.67803394770834 76.36740481827783, -122.67738223060513 76.36722052111026, -122.67639231715151 76.36727786098461), (-122.68627667402896 76.37132894977137, -122.68781137429538 76.37130773026769, -122.68944621047399 76.37116515624713, -122.69082915823883 76.37140190637302, -122.69113993605903 76.37109160429424, -122.69101166755424 76.37077045459307, -122.69013261802576 76.37058424906405, -122.68860125514365 76.37058341539242, -122.6870827678553 76.37070524655002, -122.68591976188713 76.37084484111668, -122.68530666796812 76.37101614487932, -122.68539190301382 76.37120902517665, -122.68627667402896 76.37132894977137), (-122.68609046939945 76.37344086190632, -122.69296944128641 76.37418854206766, -122.69445574273803 76.37318503895841, -122.69074630729601 76.37225008037711, -122.69164097265258 76.37301683425989, -122.68609046939945 76.37344086190632), (-122.68993341909179 76.36717545967977, -122.68985188025992 76.36688315843114, -122.68915855872028 76.3667862411921, -122.68795585667716 76.36691105360228, -122.68962955436028 76.36748385429657, -122.68993341909179 76.36717545967977), (-122.68797063793427 76.37585616123289, -122.68838346002848 76.37624084983548, -122.68887197985777 76.3765665294219, -122.69103980104573 76.37699460941377, -122.69161760826577 76.3765248062748, -122.691568851521 76.37597525125696, -122.69114172481056 76.37537300585959, -122.69034504868488 76.3750432730288, -122.68921291824134 76.3750797513296, -122.68820643387951 76.37541341779524, -122.68797063793427 76.37585616123289), (-122.69411790341832 76.36333835108412, -122.69371044667956 76.36365640172167, -122.6934466359533 76.36432313930158, -122.69551587076063 76.36503124209815, -122.69411790341832 76.36333835108412), (-122.69530880455744 76.36032295214255, -122.69632065337532 76.36087632208458, -122.69724786249866 76.36145865918988, -122.69818127154836 76.3616280554906, -122.69891142841941 76.36112833010856, -122.69878911972185 76.3606070281918, -122.69787466568305 76.36013054848632, -122.69699871521841 76.35979795491178, -122.69617235696852 76.3596365454903, -122.69535505758968 76.35965454542095, -122.69494342799659 76.35988151991631, -122.69530880455744 76.36032295214255), (-122.69719803376206 76.36299920055279, -122.69747042671851 76.36331284001565, -122.69904327352812 76.36331284001565, -122.69931566738391 76.36299920055279, -122.69923233980043 76.36266934901136, -122.6986637119605 76.36246931550656, -122.69785010789604 76.36246931550656, -122.6972813604462 76.36266934901136, -122.69719803376206 76.36299920055279))
`

The polygon seems to be simple, here is the image: 

![Screenshot from 2023-12-28 07-23-05](https://github.com/locationtech/jts/assets/125561827/dccf16e0-3e56-41f6-b600-52aefcc1ffbe)

I am using the JTS Topology suite 1.19.0 version to implement triangulation.

**Comment by dr-jts** [comment]
This is now fixed, probably by #946

**Comment by sunil-chormale-polestar** [comment]
@dr-jts I can see it has been fixed but it's not available in the latest release latest version that is present on the maven is 1.19.0 and in the master branch the version is 1.20.0-SNAPSHOT 

so when these changes will be available on maven? or when is the next release?

**Comment by micycle1** [comment]
> @dr-jts I can see it has been fixed but it's not available in the latest release, The latest version that is present on the maven is 1.19.0 and in the master branch the version is 1.20.0-SNAPSHOT
> 
> so when these changes will be available on Maven? or when is the next release?

See https://github.com/locationtech/jts/issues/996#issuecomment-1894649717
