### ISSUE TITLE
Wrong assumption in CascadedPolygonUnion

### ISSUE THREAD

**Issue by strk** [locationtech/jts#104]
Debugging an issue with CascadedPolygonUnion I found an unsafe assumption in `unionUsingEnvelopeIntersection` method of `CascadedPolygonUnion` class.

The method extracts, from 2 multipolygons, the ones that intersect an envelope and the ones that do not (disjointPolys). Then unions the intersecting ones togheter and finally combine the unioned intersecting polygons *and* the disjoint polygons, assuming that they would not be intersecting.

This is a wrong assumption, in that the union of the intersecting polygons may slightly move the envelope due to use of `SnapIfNeededOverlayOp` in `Geometry.union()`.

**Comment by strk** [comment]
Actually, it's not just about the Envelope growing, which may still be handled relatively easily, but generally about segments moving.

Consider a multipolygon with a very small space between two adjacent components.
One of the components is tall enough to be in the common envelope, the other is outside.
When unioning the tall one with other elements, it ends up overlapping the previously nearby-but-disjoint polygon, due to SnapOp heuristic.

**Comment by strk** [comment]
@dr-jts I've an XML test exposing this problem but did not find how to run it in JTS.
Asked on the mailing list but I'm afraid that list is not really used as I'm the only poster ?
https://dev.locationtech.org/mhonarc/lists/jts-dev/

Specific message: https://dev.locationtech.org/mhonarc/lists/jts-dev/msg00167.html

Shall I still use the sourceforge mailing list instead ?

**Comment by bjornharrtell** [comment]
It might be low-volume but you are not the only poster. :) https://dev.locationtech.org/mhonarc/lists/jts-dev/threads.html

**Comment by strk** [comment]
Thanks! Where had you found that  'threads' link ? :)

**Comment by strk** [comment]
XML tester for the issue is here: https://trac.osgeo.org/geos/raw-attachment/ticket/837/bug837.xml

I cannot find a way to run that single XML test with JTS so dunno what happens there.

**Comment by strk** [comment]
For the record, this bug is confirmed in GEOS (but GEOS uses a different heuristic):
https://trac.osgeo.org/geos/ticket/837

**Comment by bjornharrtell** [comment]
Found testrunner.sh is still here at https://github.com/locationtech/jts/blob/master/bin/testrunner.sh but it won't work at least because of namespace change and modularization of the source code.

**Comment by strk** [comment]
Ah, thanks. How hard would it be to fix it ?

**Comment by strk** [comment]
> How hard would it be to fix it ?

Not much : )
See #106 

With the fix I saw that JTS handles the testcase just fine. But I'm not sure that proves the assumption to be correct. For sure in GEOS SnapOp is not enough to succeeds in some union steps, and PrecisionReduction policy is being engaged, surely moving the vertices MORE than SnapOp would do, but I still think SnapOp could move vertices enough to make that assumption wrong, so a double check by @dr-jts would be good here.

**Comment by dr-jts** [comment]
The JTS TestRunner is now fixed:  #114

**Comment by dr-jts** [comment]
A possible fix for this is to check if any of the "disjoint" polygons overlap the envelope of the union result, and if so union them as well.  This would have to be done iteratively until no more overlaps occur (which should almost always happen with very few iterations, except in highly pathological cases).

**Comment by strk** [comment]
Agreed with the iterative approach.

**Comment by dr-jts** [comment]
Fixed by #429.

(But may now be slower, so fix is subject to revision)
