### ISSUE TITLE
Error in RelateGeometry?

### ISSUE THREAD

**Issue by pramsey** [locationtech/jts#1064]
This line

https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/operation/relateng/RelateGeometry.java#L146

Looks suspiciously like a typo. Is it?

**Comment by dr-jts** [comment]
Yes, that's a typo. Fixed by https://github.com/locationtech/jts/commit/0d5eac992da509d052e3d23b522c375ba902cd86
