### ISSUE TITLE
How to split concave polygon with version 1.19.0?

### ISSUE THREAD

**Issue by tiandizhiguai** [locationtech/jts#1066]
I have one polygon:
`public static void main(String[] args) {
        GeometryFactory geometryFactory = new GeometryFactory();
        
        Coordinate[] coordinates = new Coordinate[] {
            new Coordinate(0, 0),
            new Coordinate(10, 0),
            new Coordinate(10, 10),
			new Coordinate(5, 5),
            new Coordinate(0, 10),
            new Coordinate(0, 0)
        };
        
        Polygon polygon = geometryFactory.createPolygon(coordinates);
    }`
Now, I wanto to split it into multiple convex polygons with version 1.19.0, but I don't know what to do.
Anyone offer a solution? 
Many thanks.

**Comment by dr-jts** [comment]
Thew best that you can do with JTS currently is to triangulate the polygon using [`ConstrainedDelaunayTriangulator`](https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/triangulate/polygon/ConstrainedDelaunayTriangulator.java).

From that result you could build up larger convex polygons, according to some heuristic.

**Comment by tiandizhiguai** [comment]
ok, tks
