### ISSUE TITLE
Geometry.buffer() produces polygon with artifacts

### ISSUE THREAD

**Issue by freekode** [locationtech/jts#1078]
I have gpx path, around this path I create a polygon. In some cases, it produces polygon with strange artifacts.
Code example
```kotlin
val geometryFactory = GeometryFactory()
val coordinates = ... // array of Coordinate
val line = geometryFactory.createLineString(coordinates)
val polygonPoints = line.buffer(0.00025, 0, BufferParameters.CAP_FLAT).coordinates
```
Results:
![image](https://github.com/user-attachments/assets/48ac0844-2677-44cb-837c-1a299ad29ec7)
![image](https://github.com/user-attachments/assets/f14799b5-2a3f-48d6-9cba-3da5e9d8f275)

In all cases I have gpx path without any "jumps" or artifacts.

Why this happens? How can I fix this?

**Comment by dr-jts** [comment]
Hard to say without seeing the input data.

Does it work better if you use CAP_ROUND?  And/or more quadrant segments?

**Comment by freekode** [comment]
with `line.buffer(0.00025, 1000, BufferParameters.CAP_ROUND)` result is rather similar to original, with same artifacts.

**Comment by dr-jts** [comment]
>  if you need I can provide gpx paths used here

That would be great.

**Comment by freekode** [comment]
Sending full gpx in zip
[activity_17051267004.zip](https://github.com/user-attachments/files/17017731/activity_17051267004.zip)

From first gpx path, I was able to narrow it down to 15 points which can reproduce the artifact (one of multiple).
![image](https://github.com/user-attachments/assets/43ae43d8-40d6-4b7c-b2bb-15736d4797b8)
Red is gpx path, blue is polygon. This diagonal blue line, shouldn't exist.

For line:
```
LINESTRING (50.335045 16.388235, 50.33504 16.388224, 50.335037 16.38821, 50.335033 16.388195, 50.33503 16.388184, 50.33503 16.388172, 50.335022 16.388157, 50.33502 16.388144, 50.335014 16.388134, 50.335007 16.388123, 50.335003 16.388111, 50.335 16.388098, 50.33499 16.388084, 50.334988 16.388073, 50.334984 16.38806)
```

`line.buffer(0.00025, 1000, BufferParameters.CAP_ROUND)` output will be:
```
POLYGON ((50.33474594632737 16.388133247283967, 50.33474505524784 16.388133521462283, 50.33474905524785 16.388146521462282, 50.33475127106778 16.388145839671534, 50.33475831198971 16.38816249062744, 50.33475940220107 16.388167214876667, 50.33476582917547 16.38819005694144, 50.334769829175464 16.38820205694144, 50.33478734690272 16.388238861169786, 50.33478880904469 16.388249779351433, 50.33479162322888 16.3882600980268, 50.33479384635988 16.388268434768047, 50.334795549396475 16.388276382272174, 50.33481240838064 16.3883274507361, 50.334817408380644 16.3883384507361, 50.335157199999976 16.388184, 50.33515766664853 16.388184, 50.33516222530176 16.388197808863914, 50.33522666666671 16.388184, 50.335280000000004 16.388184, 50.335280000000004 16.388172571428584, 50.335284450603524 16.388171617727828, 50.335281450603524 16.388157617727828, 50.33527855873491 16.388145584337412, 50.335274558734916 16.38813058433741, 50.33527419095532 16.388129220648565, 50.33527119095532 16.388118220648565, 50.33526906444768 16.38811880060519, 50.335267092924404 16.388105985703895, 50.33525540393815 16.388073615752564, 50.3352505882353 16.38805435294117, 50.33524396066482 16.388041926246526, 50.33523437323144 16.388015376061155, 50.335228389395716 16.388005403001625, 50.33522694475216 16.387999478537715, 50.335222944752154 16.387986478537716, 50.33521918654606 16.38798763490882, 50.33520343336778 16.38795269045154, 50.33519343336778 16.38793869045154, 50.33509171668389 16.38801134522577, 50.33509752051649 16.38802507061027, 50.334865299725166 16.388096523161526, 50.33486501626123 16.388095360679717, 50.334742032522456 16.388117721359436, 50.33474403252245 16.388128721359436, 50.33474594632737 16.388133247283967), (50.33526683333333 16.38811933333329, 50.335267470588725 16.388119235294, 50.335266851063835 16.38811940425533, 50.33526683333333 16.38811933333329))
```

Now I noticed, it has 2 sets of coordinates, without the last set (4 points), polygon looks fine. What are they?

**Comment by dr-jts** [comment]
What version of JTS are you using?

With the latest version I get this result, which has no very obvious artifacts:
```
POLYGON ((50.334761757307184 16.388175585142825, 50.33476582917547 16.38819005694144, 50.334769829175464 16.38820205694144, 50.33477827054962 16.38822391005167, 50.3347875309997 16.38824490040517, 50.33479746437496 16.388284633906235, 50.33481240838064 16.3883274507361, 50.334817408380644 16.3883384507361, 50.33515760576125 16.388183815563057, 50.33516222530176 16.388197808863914, 50.335284450603524 16.388171617727828, 50.33527882646386 16.388146767305457, 50.3352779001028 16.388139665203987, 50.33526543547789 16.38808791590073, 50.33525543547789 16.38805991590073, 50.335244136655 16.388036022544426, 50.335233001167886 16.388007388434712, 50.33522459205489 16.38799183227161, 50.335222944752154 16.387986478537716, 50.335221875809836 16.387986807443045, 50.33520343336778 16.38795269045154, 50.33519343336778 16.38793869045154, 50.33509171668389 16.38801134522577, 50.33509752051649 16.38802507061027, 50.33474505524784 16.388133521462283, 50.334747464374956 16.38814463390625, 50.334761757307184 16.388175585142825))
```
<img width="281" alt="image" src="https://github.com/user-attachments/assets/16a370ca-85e1-44bf-bc6f-be21b1161075">

**Comment by dr-jts** [comment]
In general, using flat caps and joins (0 or 1 quadrant segments) is more likely to produce results with artifacts, because the round fillets and caps serve to hide issues caused by convex angle handling.  This is also more likely at larger buffer sizes, where even fairly large convex angles can "blow up" to cause join issues.

If at all possible avoid flat caps and joins.  Issues caused by larger buffer sizes could be mitigated by buffering multiple times.

**Comment by dr-jts** [comment]
I ran `buffer(0.00025, 0, BufferParameters.CAP_FLAT)` on the provided GPX line, and it doesn't appear to have any artifacts either (it's flipped because I didn't switch the lat/lng):

<img width="471" alt="image" src="https://github.com/user-attachments/assets/e2b7ab9e-a0e0-4d60-a36d-ba7781bbca5a">

<img width="207" alt="image" src="https://github.com/user-attachments/assets/22ff91a5-0b9c-4c68-bab3-9912601b1f19">

**Comment by freekode** [comment]
>What version of JTS are you using?
I used 1.19.0, migrated to 1.20.0, yeah in that small example the problem was fixed.

Now I get why it's not working. I use `Polygon.getCoordinates()` to get list of all coordinates to render, this method also returns holes coordinates. Leaflet which I use to render polygons can't render polygon and holes in one set of coordinates, they must be in separate sets. And since they all in one, that's why it has weird artifacts on the map.

Is it possible to get holes from polygon as separated sets of coordinates?

**Comment by freekode** [comment]
Found it - `Polygon.getInteriorRingN()`. I'm able to supply one set as exterior ring and other sets as holes. Now it works perfectly.
![image](https://github.com/user-attachments/assets/399b56d8-755e-4f2a-9b3a-273b1905d6b6)

Thanks for the help

**Comment by dr-jts** [comment]
Great that you've got it all to work.
