### ISSUE TITLE
Two empty geometries should have the same topology

### ISSUE THREAD

**Issue by michaelkirk** [locationtech/jts#1087]
For example: 
```
MultiPoint a = (MultiPoint) readerXY.read("MULTIPOINT EMPTY");
MultiPoint b = (MultiPoint) readerXY.read("MULTIPOINT EMPTY");
// This currently fails
assertTrue(a.equalsTopo(b));
```

Does the current behavior make sense?

**Comment by dr-jts** [comment]
I think the original idea was that EMPTY geometries contained no points, so could not be equal.  But it's debatable whether that makes sense.

**Comment by dr-jts** [comment]
This was changed in GEOS for RelateNG so that empty geometries **are** equal (regardless of geometry type).

**Comment by michaelkirk** [comment]
The motivation for my question (which I should have included originally, sorry!) is that I'm comparing the outputs of some geometry transformations to known "correct" answers.

Occasionally the expected answer is an empty geometry. 
So to check that I have achieved the *correct* answer, I currently have to say:

```
// (pseudo code)
if expected.empty() && actual.empty() {
   return true
} else {
   expected.isTopoEquals(actual)
}
```

I'm somewhat emboldened by this change in RelateNG - it's what I expected.

**Comment by dr-jts** [comment]
That's a good use case for this semantic.

This actually isn't implemented in JTS yet.  Perhaps I should make that change.

**Comment by michaelkirk** [comment]
For my own reference, in geos, it looks like we're talking about this code:

```
class EqualsTopoPredicate : public IMPredicate {

    std::string name() const override {
        return std::string("equals");
    }

    bool requireInteraction() const override {
        //-- allow EMPTY = EMPTY
        return false;
    };

    void init(int _dimA, int _dimB) override {
        IMPredicate::init(_dimA, _dimB);
        //-- don't require equal dims, because EMPTY = EMPTY for all dims
    }

    void init(const Envelope& envA, const Envelope& envB) override {
        //-- handle EMPTY = EMPTY cases
        setValueIf(true, envA.isNull() && envB.isNull());

        require(envA.equals(&envB));
    }
    ...
}
```
https://github.com/libgeos/geos/blob/29a4c7ea895da8bb721f1d9342b0a8ef3ad89b2f/include/geos/operation/relateng/RelatePredicate.h#L505

**Comment by dr-jts** [comment]
> For my own reference, in geos, it looks like we're talking about this code:

https://github.com/libgeos/geos/blob/29a4c7ea895da8bb721f1d9342b0a8ef3ad89b2f/include/geos/operation/relateng/RelatePredicate.h#L505

Correct.

**Comment by dr-jts** [comment]
I changed RelateNG to have the EMPTY-equals semantics (#1089)

**Comment by michaelkirk** [comment]
Thank you for making this change.

I wrote a test harness to consume your xml tests here: https://github.com/georust/geo/tree/main/jts-test-runner

It was especially useful when I was porting the topology graph stuff for DE-9IM operations. I haven't yet found the time to port your OverlayNG work.

I'll pull in the new https://github.com/locationtech/jts/blob/master/modules/tests/src/test/resources/testxml/misc/TestRelateEmpty.xml momentarily.

**Comment by michaelkirk** [comment]
The new tests uncovered a couple errors in our own implementation, so thank you for those. All our tests are passing now. 

https://github.com/georust/geo/pull/1227/files
