### ISSUE TITLE
CoverageUnion - improve performance for huge amount of geometries

### ISSUE THREAD

**Issue by jandam** [locationtech/jts#1100]
Input: 1M of rectangular polygons

org.locationtech.jts.coverage.CoverageUnion is slow because it internally calls GeometryCollection::getDimension multiple times. GeometryCollection::getDimension process all internal polygons O(n).

Simple test.
- Not suggested fix.
- Performance improvement using org.locationtech.jts.operation.overlayng.CoverageUnion. 
- !!! Package is "overlayng" !!!

current code:
CoverageUnion.union(factory.createGeometryCollection(coverage))
 - union from GeometryCollection  - O(n) for getDimension

improved performance:
CoverageUnion.union(factory.buildGeometry(coverage))
 - union from MultiPolygon - O(1) for getDimension

Suggested fix:
 - cache dimensions in org.locationtech.jts.operation.overlayng.InputGeometry
 - replace all access to Geometry::getDimension with method call

```
class InputGeometry {
 
  //private static final PointLocator ptLocator = new PointLocator();

  private Geometry[] geom = new Geometry[2];  // redundant array allocation
  private PointOnGeometryLocator ptLocatorA;
  private PointOnGeometryLocator ptLocatorB;
  private boolean[] isCollapsed = new boolean[2];

  private int[] dimension = new int[2]; // new code

  public InputGeometry(Geometry geomA, Geometry geomB) {
    geom = new Geometry[] { geomA, geomB };
    dimension[0] = geomA == null ? -1  : geomA.getDimension();  // new code
    dimension[1] = geomB == null ? -1  : geomB.getDimension(); 
  }
...
    public int getDimension(int index) {
        return this.dimension[index];
    }

    public boolean isArea(int geomIndex) {
        return this.getDimension(geomIndex) == 2;
    }

    public boolean isAllPoints() {
        return this.getDimension(0) == 0 && this.getDimension(1) == 0; // redundant: this.geom[1] != null 
    }

    public boolean hasEdges(int geomIndex) {
        return this.getDimension(geomIndex) > 0;
    }
...
}

```
Thank you

**Comment by dr-jts** [comment]
Thanks for pointing this out.  Even the little things can hurt performance, and it's sometimes surprising where they lurk.  This was an issue in RelateNG as well (but worse there, since `hasDimension` was the problem, which is harder to cache.

I agree that caching the dimension in OverlayNG.InputGeometry is a good idea.  It's also possible to add a short-circuit in GeometryCollection.getDimension when a dim 2 geometry has been found.  I'll add both of these optimizations.

**Comment by dbaston** [comment]
It doesn't seem too painful...see https://github.com/dbaston/libgeos/commit/a0ffc6790b51f019e320844eb4d8a5152d98b302

**Comment by dr-jts** [comment]
Potentially more storage overhead in Java, though, at least with a straightforward implementation.

**Comment by dr-jts** [comment]
I've changed my thinking about this.  Embedding a cache in `GeometryCollection` is worth the storage cost of a single reference.  Will make a PR soon.

**Comment by dr-jts** [comment]
See #1103 for fix.

**Comment by jandam** [comment]
Thank you for fixing this issue by #1103. It is more general. I still suggest some cleanup in InputGeometry. Thank you.

**Comment by dr-jts** [comment]
>  I still suggest some cleanup in InputGeometry. 

@jandam can you be more specific?
