### ISSUE TITLE
Handling of non-SRID CRS

### ISSUE THREAD

**Issue by willcohen** [locationtech/jts#1101]
I've now got a working(ish) first build of native bindings of PROJ for the JVM (https://github.com/willcohen/clj-proj/) and am contemplating how to most cleanly relate this wider set of CRS options to JTS objects. Things with EPSG codes are, of course, pretty straightforward and can just be embedded, as usual, in the existing SRID field. That said, for systems that don't map cleanly to a specific SRID field -- perhaps most abstractly thought of as anything that PROJ could convert to a coordinate reference system -- the only option right now seems to be creating some kind of larger JVM data structure where the geometry is a JTS object, and the CRS has to sit alongside.

How would you all feel about adding a slightly more flexible thing alongside the SRID field that can hold other PROJ objects? The least disruptive option that would still provide the full flexibility that PROJ could utilize is probably just to add string field under something like `CRS` rather than `SRID`, which could then, for downstream users, just hold something like anything that could fit into the strings for `source_crs` or `target_crs` from https://proj.org/en/stable/development/reference/functions.html#c.proj_create_crs_to_crs. The fancier (and probably outside of JTS's scope) option could be to abstract it to allow any object itself, so that getting from the values in the JTS object wouldn't always require instantiating CRS objects from whatever is doing the projections over and over, since PROJ itself represents projections and transforms with opaque pointer objects.

**Comment by dr-jts** [comment]
Supporting a string or object CRS reference is more flexible, for sure.  

For the time being, you can use the user data reference to link to a CRS.

**Comment by willcohen** [comment]
Will give it a shot. Thanks!

**Comment by FObermaier** [comment]
Since every `Geometry` has access to its `GeometryFactory` we could add the crs definition to that and just pass the value through to `Geometry`.

**Comment by dr-jts** [comment]
> Since every `Geometry` has access to its `GeometryFactory` we could add the crs definition to that and just pass the value through to `Geometry`.

Yes, that is an option.  The `GeometryFactory` already carries several items of metadata: a `Precision Model`, an SRID, and a `CoordinateSequenceFactory`. My feeling though is that this is complicated to manage when dealing with multiple values of each metadata item.   One reason is that they all have different semantics and lifecycles.  For instance, the SRID is a default value, which can be changed per-geometry (for instance, by the `WKBReader`, or by some other mechanism).  Whereas the `CoordinateSequenceFactory` is likely to only have one or a few values within a given system.  The PrecisionModel I view as a flawed design, which is better provided on a per-operation basis.

The CRS (and SRID) is probably the most volatile of the metadata items.  Presumably any system which provides CRS handling has to deal with potentially many different CRSes being present at a time.  If the CRS is defined by the `GeometryFactory` then multiple `GeometryFactory`s are required, with a way to identify and reuse them.  JTS provides no guidance or machinery to do this.  

On balance it seems better to be explicit that additional context metadata is NOT handled by JTS, beyond the current `int SRID` and `Object userData` context for each geometry.  The two of those should give ample scope for JTS clients to implement whatever geometry metadata handling they require.

**Comment by willcohen** [comment]
Understood. I’m a little embarrassed that I’ve been using JTS this long and didn’t realize userData was a thing until now, especially since the docs specifically call out its use for coordinate reference systems and can take Objects. Apologies for the noise — it fits the bill perfectly and this can be considered complete.
