### ISSUE TITLE
Clarification on JTS license questions for downstream projects

### ISSUE THREAD

**Issue by jodygarnett** [locationtech/jts#124]
Recent State of JTS presentation brought to light some questions from downstream projects around license change.

Downstream projects include both:
- ports: GEOS, JSTS, etc..
- use: GeoTools, GeoServer, etc ...

Q: JTS no longer uses LGPL, what does this mean for downstream projects?

> License change gives downstream projects more options using a dual license approach:
>
> * We have a BSD-3 license (permissive license than LGPL) in part to allow iOS use of the project for mobile development. 
> * We have an EPL license (similar permissive to LGPL with different wording around patents).

Q: But I thought LGPL and EPL do not mix? How does this effect the LGPL GEOS project?

> For use of JTS by an LGPL project like GEOS:
> 
> * Please use the BSD-3 License (the BSD-3 License is compatible with the LGPL license used by GEOS)
> * Long term the EPL license is being revised to work with GPL / LGPL allowing GEOS the choice of BSD-3 or EPL license.

Q: How can the LGPL GEOS program contribute fixes to JTS?

> Using a contributor license agreement:
> 
> * The GEOS team should be sure to have permission (via osgeo CLA or similar) to relicense the work in question. The JTS team wants to be in position to distribute any fix as both BSD and EPL.

Q: Why do you keep saying BSD-3, I thought it was the Eclipse Distribution License (BSD-3)

> The BSD-3 license used is called Eclipse Distribution License (as eclipse is the distributing organization.)

Should we would like to add a FAQ entry to handle these questions? Or just take to jts-dev email list (or discuss@osgeo.org email list).

**Comment by dr-jts** [comment]
Perhaps add this content here?

https://github.com/locationtech/jts/blob/master/LICENSES.md

**Comment by dr-jts** [comment]
Hmmm...  need a link to LICENSING from README too.   Actually not sure where this file came from - is it something official from Eclipse?  If so perhaps put the downstream license advice somewhere else - README perhaps, or another page if too long.

**Comment by dr-jts** [comment]
Some further questions:

- Does "downstream" mean "ports of JTS to other languages"?  Or does it include using parts of JTS in other Java projects?
- What does "you can use BSD-3 license for GEOS" mean?  Hopefully this means "the LGPL license is compatible with BSD-3/EDL, so there are no issues for releasing ported code under LGPL" ?
- Need some more detail about contributing code back I think.  Who actually contributes the code, and do they need an ECA?  The code will be licensed under EDL/EPL, right?
- The note about JTS being able to depend on LGPL projects is good to know, but perhaps should be moved elsewhere for clarity?  Isn't this about fully integrating code into JTS, not just depending on other libs?

**Comment by jodygarnett** [comment]
good feedback @dr-jts, the geoserver-devel meeting just provided that same feedback about moving jts being able to depend on out to a seperate question.

**Comment by dr-jts** [comment]
@jodygarnett I think there are still outstanding questions in the issue.  Other projects are continuing to ask about this [1].  How can we move forward on providing clear direction?

[1] https://lists.osgeo.org/pipermail/postgis-devel/2017-September/026457.html

**Comment by jodygarnett** [comment]
I think the only real solution @dr-jts is to release with the new license so people can try it.

**Comment by dr-jts** [comment]
You mean so the lawyers can sue it?  :)    Isn't it possible to be more prescriptive a priori?

Perhaps the LT legal team can advise on this?

**Comment by jodygarnett** [comment]
No I mean that until we make a release with these licenses we are going to keep getting questions. I hope that by making a release so people can try it out that these questions will go away.

I think we are being as prescriptive as possible; we are moving to a situation where we offer more choice not less.

**Comment by jodygarnett** [comment]
@dr-jts could we handle this with a FAQ addition to the JTS docs or website?

**Comment by dr-jts** [comment]
Yes, I agree this should all be documented on the JTS docs in the repo.  Perhaps here?

https://github.com/locationtech/jts/blob/master/LICENSES.md

Along with a link to this doc from the main README.  Perhaps that doc should have a final FAQ section where the questions above can be answered.  I can set this up - but may need some advice on what the answers should be!

**Comment by jodygarnett** [comment]
I think the LICENSE files on github have some kind of special processing:

* https://help.github.com/articles/adding-a-license-to-a-repository/
* https://help.github.com/articles/licensing-a-repository/
* https://opensource.guide/legal/

It offers the following:

> If your repository is using a license that is listed on the Choose a License website and it's not displaying clearly at the top of the repository page, it may contain multiple licenses or other complexity. To have your license detected, simplify your LICENSE file and note the complexity somewhere else, such as your repository's README file.

I am not sure how much we care about being detected.

**Comment by jodygarnett** [comment]
For the FAQ can we start with the questions on this bug report and then add to it as we see questions on other sources?

**Comment by dr-jts** [comment]
re the license file - looks like none of the current JTS license files follow the pattern GH provides.  So maybe we're not on the radar.  Probably not a big deal  But I will not add the FAQ to the license files, but in the README or maybe a separate file.

And yes, the questions above are a very good start to the FAQ - as long as we have answers for them!

**Comment by dr-jts** [comment]
Here's another question:  Can GPL projects (like Geoserver) link to JTS?  

I'm pretty sure the answer is yes!  But doesn't hurt to make this explicit?

**Comment by dr-jts** [comment]
Fixed by #184
