### ISSUE TITLE
[Docs] FAQ Code styling

### ISSUE THREAD

**Issue by lossyrob** [locationtech/jts#133]
From @dr-jts:

In the FAQ, style the JTS Javadoc references to make them look more like "code". 

The simple way to do this is to wrap them in [tt] tags. Even better is to wrap them in a [span] with a CSS class 'javadoc' defined in the document.

**Comment by moovida** [comment]
I can add this, but having no idea what you are talking about (the CSS part :-) ), I need help here. Can you tell me what you would add to the css? 

Also I would also like to make the "code" part more readable. These are the parts that contain WKT geometry definitions for example. At the moment they are wrapped in the code tag, but don't look all that nice. Experiences welcome.

**Comment by dr-jts** [comment]
I just commited some styling for Javadoc refs and WKT data.  You can add the CSS classes to the remainder of the document.

**Comment by moovida** [comment]
Ok, added. I left some of the WKT parts as <code>, since the div forces line wrap and that made the text less readable.

**Comment by dr-jts** [comment]
Looks good, thanks!

That's fine about leaving the code tags.  [span] could be used as well, but using [code} actually makes the markup more semantic.
