### ISSUE TITLE
Split CGAlgorithms classes into meaningful classes

### ISSUE THREAD

**Issue by dr-jts** [locationtech/jts#142]
CGAlgorithms is a kitchen-drawer class which has outlived its usefulness.  It can be split into the following classes.  

* Orientation
  * computeOrientation - deprecated in favour of index
  * index
  * isCCW
  * CLOCKWISE
  * COUNTERCLOCKWISE
  * COLLINEAR
  * RIGHT
  * LEFT
  * STRAIGHT
* PointLocation
  * isInRing
  * isOnLine
  * locateOnRing
* DistanceBetween
  * linesegToLineseg
  * pointToLineseg (x2)
  * pointToLine
* Area
  * ofRing (new)
  * ofRingSigned (x2)
* Length
  * ofLine

CGAlgorithms can be deprecated and then removed in a future version.

CGAlgorithms3D can be renamed Distance3D since it contains only distance functions.

CGAlgorithmsDD can be left for now, since it is not intended to be used directly.

**Comment by dr-jts** [comment]
@bjornharrtell @strk @FObermaier Any comments or concerns for downstream ports?

**Comment by bjornharrtell** [comment]
Should not cause any issues with the transpilation I use for JSTS. A small thing is that `length` is a reserved word in JavaScript and can/should not be used as a method name. I've renamed it `computeLength` in my fork, would be nice to avoid that.

**Comment by strk** [comment]
GEOS official API is the C one, so no concerns with C++ classes reorganization

**Comment by FObermaier** [comment]
A bit late, I don't see any problems either.

**Comment by dr-jts** [comment]
Thanks for the comments, all.  I'll proceed with this refactoring.

**Comment by dr-jts** [comment]
Fixed by #157, #158, #161, #164, #169, #170
