### ISSUE TITLE
Prepared Geometry Thread Safety?

### ISSUE THREAD

**Issue by samhendley** [locationtech/jts#162]
I have code that is running lots of polygon checks in parallel in separate threads. As far as I can tell there is no relationship between my threads, I am using a new GeometryFactory and PreparedGeometryFactory in each call stack. When I run the code with a single thread everything works as expected and I get the correct results. As soon as I start doing the calculation in multiple threads these intersection tests start to fail. In cases where it fails repeatedly calling the method will sometimes lead to different answers but not always. FWIW the failing boxes are usually near the edge of the polygons.

I have traced through the JTS code and I can't find anything that would explain this issue. I can't find any statics anywhere in the code I have stepped through but there must be something somewhere that is causing this issue. I am using version 1.13.

The code boils down to:
```scala
val pgeom = new PreparedGeometryFactory().create(target)
Seq(otherGeometries).foreach{ box : Envelope =>
  val canidateBox = new GeometryFactory().toGeometry(box)
   if(pgeom.covers(canidateBox)){
     // do something
  } else if(pgeom.insersects(candidate)){
    if(!pgeom.insersects(canidateBox)){
        throw new IllegalArgumentException("How can you intersect and not intersect?")
    }
  } else {
    if(pgeom.insersects(canidateBox)){
        throw new IllegalArgumentException("How can you intersect and not intersect?")
    }
  }
}
```

**Comment by dr-jts** [comment]
PreparedGeometry thread-safety was fixed in JTS 1.14.  Commit was r720
(2102-12-27) [1]

You should be able to get JTS 1.14 from Maven Central.  It would be good to
hear if that release fixes your problem.

[1] https://sourceforge.net/p/jts-topo-suite/code/720

**Comment by samhendley** [comment]
That does appear to fix my issue, thanks for the quick response! I missed the "private static LineIntersector" in FastSegmentSetIntersectionFinder . I had looked for a new version but didn't notice that the group name had changed so thought 1.13 was most recent.

**Comment by dr-jts** [comment]
Good to hear.

Do you mean the artifact ID has changed, rather than the group ID?

**Comment by dr-jts** [comment]
I added a bit of doc for using older versions of JTS with Maven.

https://github.com/locationtech/jts/blob/master/USING.md
