### ISSUE TITLE
Use JTS 1.15.0 in the build.gradle?

### ISSUE THREAD

**Issue by alihut** [locationtech/jts#186]
I wrote

compile group: 'org.locationtech.jts', name: 'jts-core', version: '1.15.0'

under the dependencies but android studio failed to resolve this. What am i doing wrong?

**Comment by dr-jts** [comment]
The only 1.15 version now available is 1.15.0-SNAPSHOT.  Can you try using 

`version: '1.15.0-SNAPSHOT'`

**Comment by alihut** [comment]
Thank you for your answer. I wrote

_compile group: 'org.locationtech.jts', name: 'jts-core', version: '1.15.0-SNAPSHOT'_

Same thing happened. Am i missing something?

**Comment by dr-jts** [comment]
Is it possible you need to define the repo, as in https://github.com/locationtech/jts/blob/master/USING.md ?

**Comment by jnh5y** [comment]
@alihut, Martin is right.  You'll need to tell Gradle about the LocationTech repo in order to use the 1.15.0-SNAPSHOT version.  We are releasing 1.15.0 soon.  If you are interested in contributing details to USING.md related to using JTS in Gradle, I'd be happy to help review them.
