### ISSUE TITLE
Move RobustDeterminant back from test to core

### ISSUE THREAD

**Issue by jnh5y** [locationtech/jts#205]
GeoTools was using RobustDeterminant.

**Comment by jnh5y** [comment]
@dr-jts @jodygarnett if RobustDeterminant shouldn't be part of JTS, perhaps we could deprecate it and remove it as part of 1.16 or 2.0?  In that event, GeoTools could roll the code into its codebase?

**Comment by dr-jts** [comment]
Fixed by #216.  

@jnh5y can you confirm this and close issue if so?

**Comment by dr-jts** [comment]
@jnh5y  should probably also delete branch `revertRobust` ?
