### ISSUE TITLE
Dual licensing requirements unclear

### ISSUE THREAD

**Issue by Brideau** [locationtech/jts#227]
I've tried reading the license documentation to clarify what it means to have two different licenses, but I'd still like some clarification. Does one take precedence over the other, or do you simply choose one when you use it (as is implied by the bolded "or" in "JTS is now released under a dual license: EDL **or** EPL")?

For example, if I work for a private company and use JTS to build a downstream project, do I need to publish a reference to where to find the original JTS source somewhere in my documentation (as it says in the EPL [here](https://www.eclipse.org/legal/eplfaq.php#SOURCEWOBJ)), or can I opt to "only use" the EDL where there is no such requirement?

**Comment by dr-jts** [comment]
Good questions, and ones which should get into the [Licensing FAQ](https://github.com/locationtech/jts/blob/master/FAQ-LICENSING.md).

Perhaps one of the team can comment, or we can run this by Eclipse Legal.

@jnh5y @jodygarnett ?

**Comment by jodygarnett** [comment]
You choose which license, the library is available under two licenses because we have two competing goals.

a) We would like a very permissive license so JTS is used everywhere - BSD meets this needs.
b) Some projects enjoy the additional protections around patents available under the Eclipse Public License.

**Comment by jodygarnett** [comment]
Revised the text in the FAQ to be clear this is your choice, please review, marking it as resolved.

**Comment by Brideau** [comment]
Looks good, thanks for the clarification!
