### ISSUE TITLE
org.locationtech.jts.io.geojson missing from 1.5.X-SNAPSHOT

### ISSUE THREAD

**Issue by Brideau** [locationtech/jts#235]
I noticed that `org.locationtech.jts.io.geojson` is documented [here](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/io/geojson/package-summary.html), but it seems to be missing from both 1.5.0-SNAPSHOT and 1.5.1-SNAPSHOT releases available through https://repo.locationtech.org/content/repositories/jts-snapshots

Both `org.locationtech.jts.io.gml2` and `org.locationtech.jts.io.kml` are available, however.

**Comment by dr-jts** [comment]
It's in the io-common module. You should be able to find it here:

https://repo.locationtech.org/content/repositories/jts-snapshots/org/locationtech/jts/io/jts-io-common/1.15.0-SNAPSHOT/

**Comment by Brideau** [comment]
Ah, I had used the wrong path: 

`libraryDependencies += "org.locationtech.jts" % "jts-io" % "1.15.1-SNAPSHOT"` 

instead of 

`libraryDependencies += "org.locationtech.jts.io" % "jts-io-common" % "1.15.1-SNAPSHOT"`

If it helps future users using SBT to build, this is everything you need to get the core and io dependencies:

```
resolvers += "locationtech-releases" at "https://repo.locationtech.org/content/groups/releases"
resolvers += "jts-snapshots" at "https://repo.locationtech.org/content/repositories/jts-snapshots"

libraryDependencies += "org.locationtech.jts" % "jts-core" % "1.15.1-SNAPSHOT"
libraryDependencies += "org.locationtech.jts.io" % "jts-io-common" % "1.15.1-SNAPSHOT"
```

**Comment by jnh5y** [comment]
@Brideau I think @lossyrob and I can hijack this issue to add some SBT notes to the USING.md.;)

As another note, we just released 1.15.0 to Maven central last night.  If you'd prefer to use the released version, you can give that a try!

**Comment by Brideau** [comment]
Perfect, I’ll give it a spin!

**Comment by dr-jts** [comment]
Further to this, it seems a bit confusing that there are different Maven groupids for the two published artifacts (core and io-common).  This for instance makes it harder to find both of them via a search.

Is it worth looking at/possible to reduce this to a single groupid next time round?

It would be nice to get rid of the other pom cruft in there too, I think, if that's possible.
