### ISSUE TITLE
Is the GML test data available?

### ISSUE THREAD

**Issue by Brideau** [locationtech/jts#236]
I'm working through ways to read data into JTS. I've worked out from [this post](https://sourceforge.net/p/jts-topo-suite/mailman/message/27979389/) that when reading in GML, you first have to convert it to GML _fragments_ (which admittedly confused me for a while).

Now that I have that sorted out, I found [this test class](https://github.com/locationtech/jts/blob/f6187ee22aee29933c561284e1cb56df32fddcc0/modules/core/src/test/java/org/locationtech/jts/io/gml2/GMLReaderTestCase.java) that includes a series of tests where sample data is loaded from the `bin/data` directory. This folder doesn't seem to have been included in this repo, however.

I was wondering if it might be possible to include these files so that it's possible to see how they're structured? 

Also, do you have any sample code or helper classes that you use to read from GML files (and others)? I assume they must exist, as JTS wouldn't work very well if you couldn't load common files 😄

**Comment by Brideau** [comment]
I managed to find what looks like a copy of it here: https://github.com/synhershko/nettopologysuite/tree/master/NetTopologySuite.Tests.NUnit/TestData

**Comment by Brideau** [comment]
Maybe I'm seeing this wrong, but those files are KML, not GML, correct? They use <MultiGeometry> and similar tags, and not the GML style.

**Comment by jnh5y** [comment]
As a note, I'd point to https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/io/gml2/GMLReader.java
https://github.com/locationtech/jts/blob/master/modules/core/src/test/java/org/locationtech/jts/io/gml2/GMLReaderTestCase.java
https://github.com/locationtech/jts/tree/master/modules/core/src/test/resources/testdata
