### ISSUE TITLE
Buffering a simple geometry produces a complex geometry.

### ISSUE THREAD

**Issue by ghost** [locationtech/jts#25]
The attached file contains a simple polygon geometry in WKT format. When buffering this polygon with distance = 400 and quadrantSegments = 2, a complex geometry is returned.
The majority of the shape is buffered correctly, but there are two tiny triangle fragments outside the buffered area on the bottom-left edge which are unexpected. Similar results are seen on other comparable input geometries.

[poly3.txt](https://github.com/dr-jts/jts/files/293059/poly3.txt)

**Comment by dr-jts** [comment]
Grrr..  GitHub seems to have made the file attachment disappear.
