### ISSUE TITLE
jts-example/jts-modules 1.15 jar?

### ISSUE THREAD

**Issue by willcohen** [locationtech/jts#263]
While jts-core has a jar on maven central, is there any plan to upload a jar for jts-modules or jts-example based on 1.15? There's currently a pom for jts-modules 1.15. Various projects using jts 1.14 also call jts-example as a dependency for things like ExtendedCoordinate, so migrating them to 1.15 seems like they'll either need an updated version of jts-example or just re-implement those classes themselves.

**Comment by dr-jts** [comment]
Whoa... had no idea that clients would be using jts-example as a dependency!  That's not what it was intended for.  If the ExtendedCoordinate (AKA CoordinateM) is useful, then perhaps it should be moved into the core module.  

To answer the original question, no, there is no plans to publish a jts-example jar.

**Comment by willcohen** [comment]
jai-ext, for example, is using it [here](https://github.com/geosolutions-it/jai-ext/blob/master/jt-vectorbin/src/main/java/it/geosolutions/jaiext/vectorbin/VectorBinarizeOpImage.java). Geotools also started pulling it in when updating to jts 1.14 (geotools/geotools#1665), but I'm not sure if that's just because of its dependency on jai-ext.

**Comment by dr-jts** [comment]
Hmmm...  jai-ext should know better!  It looks like in that file it's not really necessary (but I could be wrong).

For this particular case I'd suggest they look at an alternative, or bundle a copy.

**Comment by jnh5y** [comment]
@dr-jts What's your aversion to pulling ExtendedCoordinate into core?  From my point of view, it seems like a small change.  Am I missing something?

**Comment by dr-jts** [comment]
No particular aversion, although it should be renamed to something more indicative of its function - e.g. CoordinateM.  

Also, it was originally intended as a quick demo of how to make a CoordinateSequence with a custom Coordinate implementation.  No attempt was made to ensure it is fully functional (whatever that means - there was no driving use case that could be used as requirements).  But I guess if it's in core those use cases might surface :)

**Comment by willcohen** [comment]
Now that Coordinates can take M and the examples uses of ExtendedCoordinate were reworked, this is no longer relevant.
