### ISSUE TITLE
Close SourceForge account?

### ISSUE THREAD

**Issue by dbaston** [locationtech/jts#272]
I noticed that the SourceForge account for JTS is still open. It appears above GitHub in some searches and continues to see a lot of downloads and occasional bug reports.

**Comment by dr-jts** [comment]
I'm reluctant to close the SF JTS site completely, since it still has useful artifacts and history.  Perhaps could add a pointer to the GH site on the front page.

**Comment by dsmiley** [comment]
On Fri, Mar 16, 2018 at 12:53 PM Martin Davis <notifications@github.com>
wrote:

> I'm reluctant to close the SF JTS site completely, since it still has
> useful artifacts and history. Perhaps could add a pointer to the GH site on
> the front page.
>

+1 to add a pointer.  It's important for people to know where the current
place is.  Hopefully you can disable the ability to add bug reports and
other content?  Disable the mailing list?


> --
Lucene/Solr Search Committer, Consultant, Developer, Author, Speaker
LinkedIn: http://linkedin.com/in/davidwsmiley | Book:
http://www.solrenterprisesearchserver.com

**Comment by dbaston** [comment]
Duplicate of #237
