### ISSUE TITLE
Geometry.copy() should copy SRID

### ISSUE THREAD

**Issue by SPalominos** [locationtech/jts#273]
With the last (1.15) release, it seems that the abstract method `Geometry.copy()` implementation doesn't copy the Geometry SRID.

As example, the following test on the Polygon class : 
```java
@Test
    public void testSRID(){
        GeometryFactory factory = new GeometryFactory();
        Coordinate[] coords = new Coordinate[]{
                new Coordinate(0, 0),
                new Coordinate(1, 0),
                new Coordinate(1, 1),
                new Coordinate(0, 1),
                new Coordinate(0, 0),
        };
        Polygon polygon = factory.createPolygon(coords);
        polygon.setSRID(4326);
        Polygon copy = polygon.copy();
        Assert.assertEquals(polygon.getSRID(), copy.getSRID());
    }
```
returns an error : `java.lang.AssertionError: Expected :4326 Actual   :0`
Is it a normal behaviour ? Did I miss something and the SRID should be transmitted in an other way (maybe by setting the SRID on the `GeometryFactory`) ?

**Comment by SPalominos** [comment]
As discussed in the issue orbisgis/h2gis#865, it's not clear if it is a normal behaviour or not. Does someone has any clue or link to the documentation where it is explained ?

**Comment by ebocher** [comment]
Thanks @dr-jts 
setUserData must  also be tested.

```java
GeometryFactory factory = new GeometryFactory();       
Point point = factory.createPoint(new Coordinate(0, 0));
point.setUserData(12);
Point copy = (Point) point.copy();
Assert.assertEquals(point.getUserData(), copy.getUserData());
```

**Comment by dr-jts** [comment]
Yes, agreed.  All fields in the Geometry object should be copied, and the unit test should cover these.

My plan is to create a GeometryCopyTest unit test class to include these tests.

**Comment by dr-jts** [comment]
@bjornharrtell any comments?  I assume that adding in the previous semantics will not break anything in JSTS?

**Comment by bjornharrtell** [comment]
Should be fine and the correct semantics, the problem for JSTS was reliance on built in Java object cloning.

**Comment by dr-jts** [comment]
@bjornharrtell do you have any suggestions/constraints for how to implement this?  

At the moment I am thinking of providing an implementation for `Geometry.copy()` to copy the base fields.  Subclasses will have to call `super.copy()`.

Alternatively can leave `Geometry.copy()` as `abstract`, and create a `Geometry.copyBase()`.

**Comment by ebocher** [comment]
Dear @dr-jts 
Are you planning to submit this fixe (https://github.com/locationtech/jts/compare/master...dr-jts:fix-geometry-copy) soon?

**Comment by dr-jts** [comment]
Fixed.

**Comment by ebocher** [comment]
Thanks a lot
