### ISSUE TITLE
Failed to find intersection between the endpoint of the LineString and the boundary of the Polygon

### ISSUE THREAD

**Issue by ttranwork** [locationtech/jts#282]
Hi,
Thank you for providing us with a powerful and very useful library for geospatial operations. We couldn't do what we do in our project without it. Anyway, we ran into an issue that we are not sure if you noticed before. This happened when we:
1.  Perform an intersection between a line string and multiple polygons 
2.  Find the intersection points between the resulting line strings in 1. and the boundaries of these polygons.
We notice that in some cases (not all the time), JTS failed to find the intersection point where a line string begin at the boundary of the polygon. Does this have anything to do with the FAQs mentioned here regarding the double precision: https://locationtech.github.io/jts/jts-faq.html#D7 (question 8 and probably 9)?

**Comment by dr-jts** [comment]
Yes, that's almost certainly a result of limited numerical precision.  Can't say for 100% sure without seeing the test data, however.

One solution is to perform the point-boundary intersection test using a distance measure, instead of requiring exact coincidence.

**Comment by dr-jts** [comment]
The simplest way of doing this is to compute the distance between the point and the boundary geometry.  You can use the Geometry.distance [1] method to do this, and there are other ways as well  ([2], [3])

[1]https://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/Geometry.html#distance(org.locationtech.jts.geom.Geometry)
[2] https://locationtech.github.io/jts/javadoc/org/locationtech/jts/algorithm/distance/DistanceToPoint.html
[3] https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/algorithm/Distance.java#L118

**Comment by ttranwork** [comment]
Thank you.  I was thinking of a built-in method to do this for the intersection but I understand what you meant now.
