### ISSUE TITLE
LinearLocation::setToEnd - invalid segmentFraction

### ISSUE THREAD

**Issue by jandam** [locationtech/jts#286]
I would expect that segmentFraction will be set to 0.0 instead of 1.0. Because segmentIndex is already set to last coordinate.
  When I call LocationIndexedLine::project(<last_coordinate>) I get same component and segment indices but segmentFraction will be 0.0 (correct value). So I can't compare this LinearLocation with LocationIndexedLine::getEndIndex.

Current code:
```
  public void setToEnd(Geometry linear)
  {
    componentIndex = linear.getNumGeometries() - 1;
    LineString lastLine = (LineString) linear.getGeometryN(componentIndex);
    segmentIndex = lastLine.getNumPoints() - 1;
    segmentFraction = 1.0;
  }

```

Correct code:
```
  public void setToEnd(Geometry linear)
  {
    componentIndex = linear.getNumGeometries() - 1;
    LineString lastLine = (LineString) linear.getGeometryN(componentIndex);
    segmentIndex = lastLine.getNumPoints() - 1;
    segmentFraction = 0.0;  // here is fix
  }

```

PS I suggest to extend LinearLocation with equals + hashCode.

**Comment by jandam** [comment]
normLocation became invalid for geometry because segmentIndex is incremented due to normalization and segmentFraction is set to 0.0. I would expect that normLocation and endLocation will have same values.
```
    LinearLocation endLocation = LocationIndexedLine::getEndIndex();
    LinearLocation normLocation = new LinearLocation(endLocation.getComponentIndex(), endLocation.getSegmentIndex(), endLocation.getSegmentFraction());

```

**Comment by albin3** [comment]
Found same bug.

**Comment by jandam** [comment]
Thank you
