### ISSUE TITLE
Need help in understanding the connecting the edge from holes to parent after boolean operation

### ISSUE THREAD

**Issue by aayushraina** [locationtech/jts#304]
Hi,

I am facing a issue while using JTS with Boolean operations. 
Basically I have Polygon 1 

![image](https://user-images.githubusercontent.com/23273834/44702581-c96b8400-aab1-11e8-8a00-ad32a62386e5.png)
Multipolygon 2:
![image](https://user-images.githubusercontent.com/23273834/44702605-e1430800-aab1-11e8-9f5b-b453477410b3.png)

I expect a connecting edge from holes to parent when I do (1 DIFF 2)
Like this 

![image](https://user-images.githubusercontent.com/23273834/44702623-f4ee6e80-aab1-11e8-842b-13b9d2b95de3.png)

Where as JTS is returning a multipolygon which is outside polygon and inner 4 polygons which is confusing our rendering library Klayout

![image](https://user-images.githubusercontent.com/23273834/44702717-68907b80-aab2-11e8-9f3e-a71e2f0319b7.png)

Need some help in using right way of doing it.
  
createMP(){    
 List<Polygon> polygons1 = new LinkedList<>();
For (......

  polygons1.add(new GeometryFactory().createPolygon(getCoordinatesOfShape()));

)
 MultiPolygon multiPolygon = new MultiPolygon(polygons1.toArray(new Polygon[polygons1.size()]) ,new GeometryFactory());
}
Then I use createMP  to create Multipolgon A and B and perform A DIFF B

**Comment by dr-jts** [comment]
Why do you expect a connecting edge?  JTS does not return one - there is not need for holes to be connected to the containing shell.

Perhaps the rendering library cannot handle separate holes?

**Comment by aayushraina** [comment]
Thanks for a quick reply. I feel the same.
What can we do in order to have an connecting edge between holes to outside containing shell

**Comment by dr-jts** [comment]
If you need connections that do not cross any other edge of the polygon, then that's going to be a bit of a science project.   I don't know of any available code for doing this.
