### ISSUE TITLE
Do we have an option to check Point-in-polygon

### ISSUE THREAD

**Issue by lakshmankhcl** [locationtech/jts#312]
If I have a closed Polygon(c1,c2,c3,c4,c1) where c1..c4 are my Co-ordinates.

Do we have a feature in JTS library to check if a co-ordinate lies within the polygon?

**Comment by mprins** [comment]
yes; eg [covers](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/Geometry.html#covers(org.locationtech.jts.geom.Geometry))

**Comment by lakshmankhcl** [comment]
Thanks @mprins 

But, covers take another Geometry.

What I am looking at is

`
 val c1 = new Coordinate(42.6191710, -71.3215467)
  val c2 = new Coordinate(42.6180894, -71.3223299)
  val c3 = new Coordinate(42.6186657, -71.3244864)
  val c4 = new Coordinate(42.6198329, -71.3240457)
  val c5 = new Coordinate(42.6191710, -71.3215467)

  val c_coordinates: Array[Coordinate] = Array(c1,c2,c3,c4, c5)

  val g3: Polygon = new GeometryFactory().createPolygon(c_coordinates)

   val c = new Coordinate(48.6191710, -73.3215467)
   g3.xxxxxx(c) //Should give me false if that co-ordinate doesn't fall inside the polygon.

`

**Comment by dr-jts** [comment]
There's a few options.  

- [`PointLocation.isInRing`](https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/algorithm/PointLocation.java#L93) - needs to have the polygon shell ring extracted.  Does not work for polygons with holes
- [`SimplePointInAreaLocator.locate`](https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/algorithm/locate/SimplePointInAreaLocator.java#L52) - a general purpose solution
- [`IndexedPointInAreaLocator`](https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/algorithm/locate/IndexedPointInAreaLocator.java#L74) - use in situations where many points need to be tested against a single polygon

**Comment by dr-jts** [comment]
BTW, questions like are better posted to the [JTS mailing list](https://locationtech.org/mailman/listinfo/jts-dev), rather than being raised as issues.
