### ISSUE TITLE
VoronoiDiagramBuilder clipping bug

### ISSUE THREAD

**Issue by crisbodnar** [locationtech/jts#314]
The following lines in the Voronoi diagram builder increase the clipping region significantly and the returned polygons are not clipped by the envelope supplied in the builder:

```
// add a buffer around the final envelope
double expandBy = Math.max(diagramEnv.getWidth(), diagramEnv.getHeight());
```
If the buffer is larger than the supplied clipping envelope, then the supplied envelope is ignored, even if all sites fit in the original envelope.

**Comment by dr-jts** [comment]
Closed by #449
