### ISSUE TITLE
ConformingDelaunayTriangulator can generate unnecessary points

### ISSUE THREAD

**Issue by johnhultman** [locationtech/jts#320]
It takes four coordinate points to demonstrate this, and there's a test case snippet below. In the figure the interior segments have been removed (for unrelated reasons) but one can see the unnecessary points (that form a sort of fractal pattern). 

<img width="1548" alt="screen shot 2018-09-26 at 20 51 17" src="https://user-images.githubusercontent.com/20039211/46132213-c349fe00-c23d-11e8-94cd-d24b0efca819.png">

    import org.locationtech.jts.geom.Coordinate;
    import org.locationtech.jts.triangulate.ConformingDelaunayTriangulator;
    import org.locationtech.jts.triangulate.ConstraintVertex;
    import org.locationtech.jts.triangulate.Segment;
    import org.locationtech.jts.triangulate.quadedge.QuadEdgeSubdivision;
    import org.testng.Assert;
    import org.testng.annotations.Test;

    import java.util.ArrayList;
    import java.util.Collection;

    @Test
    public void testFractalTriangulation()
    {
        final Coordinate c0 = new Coordinate(1.99, 38.36);
        final Coordinate c1 = new Coordinate(15.96, 1.97);
        final Coordinate c2 = new Coordinate(126.67, 0);
        final Coordinate c3 = new Coordinate(62.08, 54.19);

        final ArrayList<Segment> segments = new ArrayList<>();
        segments.add(new Segment(c0, c1));
        segments.add(new Segment(c1, c2));
        segments.add(new Segment(c2, c3));
        segments.add(new Segment(c3, c0));

        final ArrayList vertices = new ArrayList<>();
        for (final Segment segment : segments)
        {
            vertices.add(new ConstraintVertex(segment.getStart()));
        }

        final ConformingDelaunayTriangulator cdt = new ConformingDelaunayTriangulator(new ArrayList<>(), 1E-5);
        cdt.setConstraints(segments, vertices);
        cdt.formInitialDelaunay();
        cdt.enforceConstraints();
        final QuadEdgeSubdivision subdivision = cdt.getSubdivision();

        final Collection subdivisionEdges = subdivision.getEdges();

        Assert.assertEquals(subdivisionEdges.size(), 3);
    }

**Comment by johnhultman** [comment]
I'm not sure on the assessment of this issue. Are these additional points a problem? (Other than that they may possibly affect performance.)

**Comment by johnhultman** [comment]
Thanks for the clarifications here. As you indicate, it also seems rare that this can happen. I observed it on triangulating a larger (more complex) polygon, and reduced it to the test above. It's not a lot that can be altered in the test before the unnecessary points will disappear.

I should also have mentioned that in addition to the unnecessary points, there's also small unnecessary triangles, on the order of the tolerance in size. Probably as a result when the "fractal" cycle terminates, as the tolerance is reached.

**Comment by dr-jts** [comment]
From what I recollect this only happens for a certain range of angle sizes.  In the original work for which the CDT code was built I think I had a further heuristic to prevent this from happening (which might have involved introducing Steiner points to "split" the angles).  

There's probably some further heuristics that could be introduced to prevent this, but that's definitely a research project.

**Comment by johnhultman** [comment]
I understand. Let's close the issue, but it will still be here, should someone run across it again, the discussion and clarifications might prove valuable.
