### ISSUE TITLE
Union operation generates incorrect array of points if the resulting region contains several holes

### ISSUE THREAD

**Issue by AlexMaleyko** [locationtech/jts#322]
When union() methods from org.locationtech.jts.operation.union are used the union is generated incorrectly, if it should contain multiple holes in it.
The case is the following:
 1) multiple circles are being generated:
`private Polygon getJTSCircle(Coordinate centre, Double radius) {

        GeometryFactory geometryFactory = new GeometryFactory();
        GeometricShapeFactory shape = new GeometricShapeFactory(geometryFactory);
        shape.setCentre(centre);
        shape.setNumPoints(100);
        shape.setSize(radius);
        return shape.createCircle();
    }`
 2) After that their union is calculated, then its geometries are iterated (in case union results in MultyPolygon) and coordinates array of each geometry is retrieved and then fetched to proprietary drawing tool to create the polygon and display it on a map:

`public static void drawUnion() {

        Geometry union = CascadedPolygonUnion.union(circles);
        List unions = new ArrayList<>();
        for (int i = 0; i < union.getNumGeometries(); i++) {
            unions.add(union.getGeometryN(i));
        }
        for (Geometry region : unions) {
            Coordinate[] unionCoordinates = region.getCoordinates();
            List proprietaryUnion = new ArrayList<>();
            for (Coordinate coordinate : unionCoordinates) {
                Proprietary2DPoint point = proprietaryFactory.createCoordinate(coordinate.x, coordinate.y);
                proprietaryUnion.add(point);
            }
            proprietaryDrawingTool.draw(proprietaryUnion);
        }
    }`

The union works fine if resulting regions don't have holes or have just one hole, however if more than one hole is present in a region then the coordinate array is created incorrectly. It feels like the api tries to draw inner boundaries at once (without switching to outer boundaries) but fails to do so.
The screenshots are attached.
I also tried to preform union only on intersecting polygons, but that didn't work as well.
I'll be grateful for any help.
![union1](https://user-images.githubusercontent.com/26231521/46201369-a59f9600-c31c-11e8-9c20-19029966fdb1.PNG)
![union2](https://user-images.githubusercontent.com/26231521/46201376-aa644a00-c31c-11e8-8426-39814b545d63.PNG)
![uniononlyintersectingpolygons](https://user-images.githubusercontent.com/26231521/46201501-06c76980-c31d-11e8-82be-c4523023941a.png)

**Comment by AlexMaleyko** [comment]
@FObermaier , could you please provide an example of the right way to retrieve coordinates of such region? The Geometry interface doesn't make difference between inner ring and exterior rings. In fact, when a region contains only one interior ring the array of coordinates represents the following polygon:
![screenshot_20180928_142451](https://user-images.githubusercontent.com/26231521/46205710-5f513380-c32a-11e8-8adb-5693fc79b670.png)
(it is just a drawing of what I got when dealing with such a union. Here red and green arrows actually have the same ends. The arrows are used just to give the understanding of how coordinates arranged in the array)

**Comment by FObermaier** [comment]
That depends on your drawing library. You can get an idea of what has to be taken care of by having a [look at the `awt` namespace](https://github.com/locationtech/jts/tree/master/modules/core/src/main/java/org/locationtech/jts/awt), especially the `ShapeWriter` class.

**Comment by dr-jts** [comment]
To get the outer and inner rings of Polygons use 

- [Polygon.getExteriorRing
 ](http://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/Polygon.html#getExteriorRing()) 
- [Polygon.getInteriorRingN](http://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/Polygon.html#getInteriorRingN(int))

**Comment by AlexMaleyko** [comment]
@dr-jts , @FObermaier , thank you for your help, everything works now very robust. Those two methods are undocumented and I interpreted their purpose in a wrong way.
