### ISSUE TITLE
 Can not construct instance of org.locationtech.jts.geom.Point: no suitable constructor found

### ISSUE THREAD

**Issue by mmohiahmed** [locationtech/jts#325]
What should be my work around for the issue bellow, Thanks in advance

JSON parse error: Can not construct instance of org.locationtech.jts.geom.Point: no suitable constructor found, can not deserialize from Object value (missing default constructor or creator, or perhaps need to add/enable type information?); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of org.locationtech.jts.geom.Point: no suitable constructor found, can not deserialize from Object value (missing default constructor or creator, or perhaps need to add/enable type information?)\n at [Source: java.io.PushbackInputStream@12205f02;

**Comment by mprins** [comment]
I don't think there's a point constructor that has a Jackson json or Object argument, so you need to parse the json

**Comment by mmohiahmed** [comment]
Thanks @mprins , I was using com.vividsolution.jts.Point class and it was working fine (could convert GeoJson {    "type": "Point", "coordinates": [125.6, 10.1]}   to Point ). Recently moved to org.locationtech.jts.Point and facing the problem. Should I go back to  com.vividsolution.jts.Point ?

**Comment by jnh5y** [comment]
@mmohiahmed is there a library that is handling the Jackson mapping between JSON and JTS classes?  If so, then it might need to be updated to handle the new JTS package names.

**Comment by jnh5y** [comment]
@mmohiahmed any more details?
