### ISSUE TITLE
Simplifications  & Enhancements to Coordinate classes

### ISSUE THREAD

**Issue by dr-jts** [locationtech/jts#329]
It seems like it would be reasonable to:

* Do **not** specify X and Y ordinate indices in subclasses of `Coordinate`, since they are inherited
* Do **not** specify ordinate indices in subclasses if they are not valid for that class (e.g. Z and M)
* Do **not** set the values of unsupported ordinates in `setCoordinate `overrides (or maybe set them to `NaN`)

None of these will change the API, so can be fixed now.

Also it might be nice to add `getDimension ()`and `getMeasures() `methods to `Coordinate `and subclasses, since those are known statically from the Coordinate definition.

Although one possible point of confusion is that if a `CoordinateSequence `does not use an appropriate Coordinate subclass then the dimension and measures count would not be in synch.

See also #372 and #349

**Comment by dr-jts** [comment]
@jodygarnett  thoughts?

**Comment by dr-jts** [comment]
@jnh5y thoughts?

**Comment by dr-jts** [comment]
Also wondering if it would make sense to add `getDimension `and `getMeasures `methods to Coordinate and subclasses?

**Comment by jnh5y** [comment]
@dr-jts my main thought/consideration about simplifying Coordinate would be any options that'd let us 'combine' Coordinate and Point.  This especially gets more interesting when we consider Value Classes coming to the JVM sometime...

If we could get that right, we'd could likely make some stronger claims about memory layout and push some optimizations there.

**Comment by jodygarnett** [comment]
GML3 combines Coordinate and Point (or rather lets a Point be used as a Coordinate) never found the extra expressability worth the trade off in complexity.

**Comment by jodygarnett** [comment]
Returning to @dr-jts question:

```
public class Coordinate implements Comparable<Coordinate>, Cloneable, Serializable {
public static final int X = 0;
public static final int Y = 1;
public static final int Z = 2;
...
}
public class CoordinateXY extends Coordinate {
  public static final int X = 0;
  public static final int Y = 1;
  public static final int Z = -1;
}
```

Static constants have no concept of inheritance (indeed you will often get a warning when using a constant via a subclass reference since the result is brittle if anyone later introduces a static field with the same name).

In this case we are defining `X`,`Y`,`Z` constants for `CoordianteXY` to both avoid this warning and document the fact that `CoordianteXY.Z` is unused and unusable.

**Comment by jodygarnett** [comment]
The break in this (beyond compiler warning) is `CoordinateXYM.M` being `3` and `CoordianteXYZM.M` being `4`.

Enum would be perfect but that is too much of an API break.

**Comment by dr-jts** [comment]
Ok, @jodygarnett has provided some good reasons why each subclass should have it's own set of ordinate constants.

As for not checking for setting non-existent ordinates, my feeling is still that it's better to not complain where not needed, since it doesn't impact the correctness of JTS functionality.  But this check can be relaxed at a later date if it proves onerous.

So am closing this issue as WONT FIX.
