### ISSUE TITLE
How to add points to a LineString dynamically & efficiently?

### ISSUE THREAD

**Issue by userLikun** [locationtech/jts#331]
When I create a LineString, I want to add a new Point in it to make a new LineString.But I don't want to use 
createLineString(Coordinate[] coordinates). what should I Do?

**Comment by dr-jts** [comment]
Please ask questions like this on the mailing list.

**Comment by dr-jts** [comment]
Based on your limited description, that is the only way to do what you want.

**Comment by userLikun** [comment]
Sorry, I want to generate  track lines based on real time coordinates, but with this method, the more points we track, the more time we used.

**Comment by dr-jts** [comment]
Ah, ok, good to have that background.

You might be able to make an "extendable" `CoordinateSequence` backed by an `ArrayList`.  

Note that you must call `Geometry.geometryChanged()` before calling any operations on the modified geometry.  Depending on what operations you use, the envelope may be recomputed, which might reduce the savings of extending the coordinates in place.

**Comment by userLikun** [comment]
ok,thanks
