### ISSUE TITLE
TestBuilder CPU usage explosion when showing Orientations at high zoom level

### ISSUE THREAD

**Issue by dbaston** [locationtech/jts#332]
Using latest commit that compiles (b9f54c9)

Paste in geometry recently discussed on Boost.Geometry mailing list: https://bugs.mysql.com/bug.php?id=92937

Construct minimum clearance line, and zoom to result

Turn on "magnify topology", "geometry structure", and "orientations"

Orientations are not rendered, and CPU usage goes to 100%.

**Comment by dr-jts** [comment]
Good find!  I will investigate.  Things can get weird down at the subatomic zoom level.

**Comment by dr-jts** [comment]
It looks to me like the Orientations style is the culprit, at high zoom levels.   With Orientations enabled, CPU usage rises as the zoom level increases. And at the extreme zoom level of this case system memory is consumed rapidly.  So the JVM does not appear to respect the memory limit, which is somewhat disturbing.

**Comment by dr-jts** [comment]
Fixed by  [0453021](https://github.com/locationtech/jts/commit/045302139235b5cf3e8ac68ebd5b53b541497ba7).

Fix is to clip segments before rendering decorations for them.

**Comment by dr-jts** [comment]
@dbaston Can this be closed?

**Comment by dbaston** [comment]
@dr-jts I can confirm that CPU usage now remains normal in this case. Thanks for the fix!

One small note: I now see a display artifact in this case:

![image](https://user-images.githubusercontent.com/6318931/47733244-30d2bb00-dc3e-11e8-8fef-dd3380de979e.png)

**Comment by dr-jts** [comment]
The artifact is actually as designed.  I have been experimenting with changing the rendering of polygon segment direction arrows, to make them visible at all scales (this was enabled by the addition of segment clipping).  Java2D has issues with rendering long segments (in view space), which is why it looks odd.  It should be possible to use segment clipping to improve this as well.
