### ISSUE TITLE
Confusing logic in hasM

### ISSUE THREAD

**Issue by schwehr** [locationtech/jts#347]
Why is `getMeasures() > 0` not sufficient?  Can someone who knows add a comment as to why?

https://github.com/locationtech/jts/blob/8ef27d434edbdebf96d9b61be1810319a435ae7d/modules/core/src/main/java/org/locationtech/jts/geom/CoordinateSequence.java#L114

```java
  /**
   * Checks {@link #getMeasures()} to determine if {@link #getM(int)}
   * is supported.
   * 
   * @return true if {@link #getM(int)} is supported.
   */
  default boolean hasM() {
      return getDimension()>2 && getMeasures() > 0;
  }
```

**Comment by dr-jts** [comment]
`hasM` is just a convenience method.  It also helps explain the semantics of `getMeasures`.

**Comment by dr-jts** [comment]
Why is it confusing?

**Comment by dr-jts** [comment]
Perhaps the Javadoc could be better?  Something like:

`Tests whether the coordinates in the sequence have measures associated with them.  Returns true if getMeasures > 0.  See getMeasures to determine the number of measures present.`

**Comment by schwehr** [comment]
Then can you drop the `getDimension()>2`?  aka Can't the code just be:

```
default boolean hasM() {
      return getMeasures() > 0;
}
```

**Comment by dr-jts** [comment]
Yes, I think so.  

@jodygarnett  do you agree?

**Comment by jodygarnett** [comment]
In order not to break client code assumptions we carefully introduced measures so the number of measures is (dimensions - measures). So I would write this test as (dimensions - measures) > 0
