### ISSUE TITLE
Densify code appears to be unused

### ISSUE THREAD

**Issue by pramsey** [locationtech/jts#351]
While porting JTS changes to GEOS, I found the XML tests for org.locationtech.jts.densify.Densifier and then tried to track down what depended on the densifier, and it doesn't look like anything does anymore, except for some tests? It seems to have been build for the Hausdorff distance calculation but then superseded by another design, which is what ended up in GEOS.

**Comment by dr-jts** [comment]
That's correct.   A more efficient "in-place" algorithm was developed for
the Hausdorff distance class. The Densifier was left in place to provide
that functionality as part of the JTS API.

There's quite a few algorithms/functions which are provided as standalone
classes, and not exposed as Geometry methods.  At some point it would be
nice to regularize the interface to these, and perhaps make them
discoverable via some sort of registry.

**Comment by dr-jts** [comment]
Sounds like a good idea.  The Densifier should continue to be shipped as
part of the JTS API - can't see any reason to remove it.
