### ISSUE TITLE
CoordinateSequenceFilter.isDone() javadoc typo

### ISSUE THREAD

**Issue by groldan** [locationtech/jts#353]
The javadocs for `CoordinateSequenceFilter.isDone()` say that `Once this method returns **false**, it should continue to return **false** on every subsequent call.`.

It looks like it should say  `Once this method returns **true**, it should continue to return **true** on every subsequent call.` instead.

**Comment by dr-jts** [comment]
Good catch - thanks.  I'll make a PR for this.
