### ISSUE TITLE
Outdated Javadocs

### ISSUE THREAD

**Issue by dbaston** [locationtech/jts#358]
JTS 1.16 has been released, but the only Javadocs I can find online are stamped with "1.15.0-SNAPSHOT.":

https://locationtech.github.io/jts/javadoc/index.html

Is there a newer URL that `README.md` should refer to, or does the site above need to be updated?

**Comment by dr-jts** [comment]
The website needs to be updated.

**Comment by dr-jts** [comment]
Fixed by https://github.com/locationtech/jts/commit/56d1a1100f67318807e012bec1a192db5af8cbda
