### ISSUE TITLE
PackedCoordinateSequence.Float: missed a spot updating for measures?

### ISSUE THREAD

**Issue by airbreather** [locationtech/jts#378]
I'm going through the NTS port of JTS 1.16 now, and I noticed this block:
https://github.com/locationtech/jts/blob/7186cb473c139d6877ffb8a538fefa47c59566c4/modules/core/src/main/java/org/locationtech/jts/geom/impl/PackedCoordinateSequence.java#L471-L473

It still thinks ordinate index 2 is always Z, and it doesn't do anything for M.

`PackedCoordinateSequence.Double`'s equivalent block handles it differently (and, apparently, more correctly):
https://github.com/locationtech/jts/blob/7186cb473c139d6877ffb8a538fefa47c59566c4/modules/core/src/main/java/org/locationtech/jts/geom/impl/PackedCoordinateSequence.java#L300-L304

**Comment by dr-jts** [comment]
Yes, indeedy.  It looks like the [unit test](https://github.com/locationtech/jts/blob/master/modules/core/src/test/java/org/locationtech/jts/geom/impl/PackedCoordinateSequenceTest.java) doesn't check the Float version.

I will work up a fix and unit test.

**Comment by dr-jts** [comment]
Fixed by #379

**Comment by dr-jts** [comment]
Maybe this is the last multidimensional CoordinateSequence bug.  Hahahahaha...
