### ISSUE TITLE
PackedCoordinateSequenceFactory.create(Coordinate[]) skips checking dimension / measures for single-element arrays

### ISSUE THREAD

**Issue by airbreather** [locationtech/jts#380]
This code looks like it's trying to infer `dimension` / `measures` from the input coordinates, but shouldn't the middle check be `coordinates.length > 0` instead of `coordinates.length > 1`?

https://github.com/locationtech/jts/blob/0b8afdbeef9a328470c01599020cb99452e53f66/modules/core/src/main/java/org/locationtech/jts/geom/impl/PackedCoordinateSequenceFactory.java#L72-L79

**Comment by dr-jts** [comment]
Yes, that looks like a bug.  Will work on a unit test and a fix.

**Comment by dr-jts** [comment]
Fixed by #381
