### ISSUE TITLE
Unexpected Geometry Contains result.

### ISSUE THREAD

**Issue by funkyminus** [locationtech/jts#410]
Hello. I tried to use following LineString to check if it's Contains in Polygon or not.
*( Every "Contains" that mentioned in this one will apply to Polygon.Contains(LineString) )

`POLYGON ((15507072.3012821 4258678.03752752, 15507156.0180082 4258715.26440252, 15507155.7914345 4258693.17468075, 15507123.0573852 4258686.5164328, 15507142.455274 4258673.26393471, 15507157.4549545 4258670.81022548, 15507156.0180082 4258640.81065252, 15507072.3012821 4258678.03752752))`

`LINESTRING (15507156.2804967 4258671.0023481, 15507155.7580031 4258693.16788066)`

![001](https://user-images.githubusercontent.com/8348565/55866154-f33d6b00-5ba9-11e9-9b57-4c32c623f70e.PNG)

As you can see in the pictures that this LineString isn't contains in Polygon, but Polygon.Contains(LineString)'s result turned out to be TRUE instead of FALSE.
***P.s.** This LineString is result of using other longer line to Intersection with polygon, then use end point of first line and start point of next line to create new line which is our problem line as shown in picture.

But if I changed LineString coordinate for only one digit in decimal of Y axis, Contains result will changed to FALSE as it should be.

Contains = TRUE
> LINESTRING (15507156.2804967 4258671.002348**1**, 15507155.7580031 4258693.16788066)

![001](https://user-images.githubusercontent.com/8348565/55866154-f33d6b00-5ba9-11e9-9b57-4c32c623f70e.PNG)

Contains = FALSE
> LINESTRING (15507156.2804967 4258671.002348**2**, 15507155.7580031 4258693.16788066)

![004](https://user-images.githubusercontent.com/8348565/55867509-d3f40d00-5bac-11e9-8914-b4e41563898e.PNG)

This is another example when I tried to add extra points to LineString. It's also have different result depends on side that line bended to too.

Contains = TRUE
![002](https://user-images.githubusercontent.com/8348565/55867429-aad37c80-5bac-11e9-9d7f-d48da0f3dd3d.PNG)

Contains = FALSE
![003](https://user-images.githubusercontent.com/8348565/55867436-aeff9a00-5bac-11e9-9ce3-3dc405e19258.PNG)

I tried to tracing down the code and end up in RayCrossingCounter.locatePointInRing that created different result on this two cases, but I literally have no idea how this class works (but cause of problem is probably because points is too narrow with Polygon?). 

Is this a problem(bug) for Contains checking process? Or I just misunderstood the concept of how to use Geometry Contains?

Thanks in advance.

**Comment by dr-jts** [comment]
When I run this using the latest JTS (HEAD) I get `Polygon.contains(LineString) = false`.  So not sure why you're seeing something different.  What version of JTS are you using?  Can you provide test code that demonstrates the problem?

**Comment by funkyminus** [comment]
Sorry for replying late. It's been a while since my project is updated the code from JTS. After I upgrade my project to using last JTS, It's seem to working fine now. Thank you again for your replied.
