### ISSUE TITLE
GeoJsonWriter produces invalid JSON for empty geometries

### ISSUE THREAD

**Issue by wulfsberg** [locationtech/jts#411]
Geometry g = new WKTReader().read("LINESTRING EMPTY");
    System.out.println(new GeoJsonWriter().write(g));

results in

    {"type":"LineString","coordinates":,"crs":{"type":"name","properties":{"name":"EPSG:0"}}}

which is syntactically invalid JSON.

I realize that JTS takes the interpretation that there is no such thing as "empty geometries" in GeoJSON, and it should simply be represented as a null-value. But since empty geometries are a well-established case in the rest of JTS and something the geometry classes can explicitly carry, the serializer should handle them gracefully.

So I suggest that the GeoJsonWriter should serialize empty geometries as the JSON value `null`.

(As is, it is quite surprising that it does not even raise an error, but produces flat-out invalid JSON)

**Comment by dr-jts** [comment]
Agreed it is unfortunate that invalid JSON is produced, and that should be fixed.

Not sure about simply returning `null`, since that loses the geometry type information.  

What about returning an empty array for the `coordinates` property?

Is there any prior art here?  It's too bad the spec doesn't cover this.

**Comment by wulfsberg** [comment]
An empty coordinate array would be the obvious equivalent representation, and what I initially expected I'd get.
I dug through the GeoJsonWriter code and realized it was a deliberate choice that, to quote a comment in the test class, "empty atomic geometries are not supported in GeoJSON", so my suggestion for using a  null-value was based on that (and the spec's somewhat vague "implementation _may_ interpret...").

Personally, I'd prefer an empty coordinate array, to maintain the type as you say, but I don't know if that has, say, some interop issues.

**Comment by dr-jts** [comment]
Hmm... [this (old) GeoJSON thread](http://lists.geojson.org/pipermail/geojson-geojson.org/2013-October/000839.html) indicates that representing empty geometries as null is in fact correct.

Seems more limited than it needs to be, but ONTRW.  Too bad this isn't indicated more explicitly in the spec.  Is it worth querying to see if this stance has changed?

**Comment by dr-jts** [comment]
On the plus side, emitting `null` for empty geometries is a pretty easy fix...

**Comment by wulfsberg** [comment]
I'm somewhat on the fence.
As I read the spec, it is valid to write an empty coordinate array, and valid for a _reader_ to interpret that as simply a null object. Some part of me wants to do it that way, to maintain as much information as possible.
But then the frontend programmer in finds it a bit of hassle to have to check whether the geometry I just explicitly got isn't actually a geometry. Pragmatically, it just isn't very useful. (On the other-other hand, I may have to do that anyway, since the spec does allow empty coordinate arrays).

**Comment by dr-jts** [comment]
One argument for emitting a `null` `coordinates` property is that if a totally `null` value is required then it's easy to write a wrapper function to do this - but the converse is not true.

In any case, one of these needs to be implemented - invalid JSON is clearly wrong.

**Comment by JamesRTaylor** [comment]
I'd be happy to contribute a fix for this that returns an empty geometry in the case of an empty coordinate array if you're open to it.

**Comment by JamesRTaylor** [comment]
FYI, I submitted a PR for this, @dr-jts.

**Comment by jratike80** [comment]
is this issue fixed with the commits above and ready to be closed as fixed?

**Comment by dr-jts** [comment]
Yes, it should be fixed.
