### ISSUE TITLE
Quadtree.ensureExtent does not pad maxx or maxy

### ISSUE THREAD

**Issue by AjuHan** [locationtech/jts#412]
Quadtree.ensureExtent currently has this code:

 // pad one or both extents
    if (minx == maxx) {
      minx = minx - minExtent / 2.0;
      maxx = **minx** + minExtent / 2.0;
    }
    if (miny == maxy) {
      miny = miny - minExtent / 2.0;
      maxy = **miny** + minExtent / 2.0;
}

This might be correct:
 // pad one or both extents
    if (minx == maxx) {
      minx = minx - minExtent / 2.0;
      maxx = **maxx** + minExtent / 2.0;
    }
    if (miny == maxy) {
      miny = miny - minExtent / 2.0;
      maxy = **maxy** + minExtent / 2.0;
}

**Comment by dr-jts** [comment]
`maxx `is only updated if `minx == maxx` (and likewise for `maxy`).  So the code is technically correct, even if not perhaps obvious.

**Comment by AjuHan** [comment]
Hi,

Please, would you reconsider the issue. The existing code does only update minx (and miny) but
not maxx (nor maxy) at all:
minx = minx - minExtent / 2.0;
maxx = minx + minExtent / 2.0;

when the first line has been executed minx has been updated.
The second line tries to update maxx but operates on the (alrady updated) value on minx
As the second operation is opposite to the first one it has zero net effect on maxx.

I, of course, do assume minx should be decreased and maxx increased in value. 

Regards
AjuHan

**Comment by dr-jts** [comment]
Right, I see the problem now. Thanks for following up. I will make a PR to fix this.
