### ISSUE TITLE
Geometry.union(Geometry) does not support GeometryCollection

### ISSUE THREAD

**Issue by ericjeffers-ifactor** [locationtech/jts#425]
The documentation indicates that `Geometry.union()` accepts a GeometryCollection in the documentation, yet the code indicates otherwise:

https://github.com/locationtech/jts/blob/68cc804fc8cac499ae1143ecbdb1cd8c37302ae8/modules/core/src/main/java/org/locationtech/jts/geom/Geometry.java#L1405

Documentation: This method supports GeometryCollections (which the other overlay operations currently do not).

**Comment by dr-jts** [comment]
The link is to the code for the [`Geometry.union(Geometry)`](http://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/Geometry.html#union-org.locationtech.jts.geom.Geometry-) method, whereas the documentation quoted is for the [`Geometry.union()`](http://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/Geometry.html#union--) method.

**Comment by ericjeffers-ifactor** [comment]
Apologies, here are the correct references:
`Geometry.union(Geometry)` - [code](https://github.com/locationtech/jts/blob/68cc804fc8cac499ae1143ecbdb1cd8c37302ae8/modules/core/src/main/java/org/locationtech/jts/geom/Geometry.java#L1405) / [documentation](http://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/Geometry.html#union-org.locationtech.jts.geom.Geometry-)
