### ISSUE TITLE
Thread-safety support

### ISSUE THREAD

**Issue by ShivKJ** [locationtech/jts#444]
Hi,

I have a MULTILINESTRING (say **A**) and I am trying to find its intersection with other LineStrings (which is a list of LineString) (say **B**). As the number of lineString in list **B** is very large, i am parallel processing **A** with elements of **B** to find intersection of **A** with elements of **B**.

Is doing this thread safe?

**Comment by dr-jts** [comment]
Yes, the spatial predicatee and the overlay ops should be thread-safe.
