### ISSUE TITLE
GMLReader fails to parse Point with pos elements in it

### ISSUE THREAD

**Issue by pandzel** [locationtech/jts#450]
Points defined like `<Point><coordinates>10.0,10.0</coordinates></Point>` are parsed fine.
Points defined like `<Point><pos>10.0 10.0</pos></Point>` GMLReader fails to parse.

Is this a limitation, or I am missing something here?

**Comment by dr-jts** [comment]
Not sure.  Is `<pos>` part of the GML2 spec?

In any case, it looks like it isn't supported by `GMLReader`.

**Comment by pandzel** [comment]
Looks like <pos> element has been introduced in post-GML2 specs. Thanks for responding.
