### ISSUE TITLE
Question about GeometryCollection

### ISSUE THREAD

**Issue by wwwwxiaojie** [locationtech/jts#458]
Hi, I want to know that is it possible that one GeometryCollection contains another GeometryCollections? If yes, what's the consideration of allowing this? Thanks.

**Comment by wwwwxiaojie** [comment]
Follow up: If I use the method provided in the library, ex. geometry.difference(Geometry), is it possible that the result will be a nested GeometryCollection? Thanks.

**Comment by dr-jts** [comment]
Yes, `GeometryCollection`s can be nested.

If operations support `GeometryCollection`s they should allow nested ones as well.  If you find anything lacking in this area, please file an issue.

**Comment by dr-jts** [comment]
> Follow up: If I use the method provided in the library, ex. geometry.difference(Geometry), is it possible that the result will be a nested GeometryCollection? 

JTS operations never emit nested `GeometryCollection`s, since a flat geometry collection is simpler and semantically equivalent.

**Comment by wwwwxiaojie** [comment]
Very helpful. Thank you.
