### ISSUE TITLE
Locale for WKTWriter numbers

### ISSUE THREAD

**Issue by menion** [locationtech/jts#473]
Devices with locale set to non-arabic numbers, like *ar_SA* cause that `Geometry.toText()` result ends with number formatted in locale, and not in Arabic numbers. Because we use result of this call in queries to the database, it is a problem.

Should be possible to specify optional `Locale` instance, that will be used in `WKTWriter.createFormatter()` , more precisely in the constructor of inner `DecimalFormatSymbols` object? All required functions are private or static, so it is not possible to simply extend this class.

![image](https://user-images.githubusercontent.com/1257075/64759320-14c6c800-d537-11e9-9f07-707faf0ce2ff.png)

Thank you.

**Comment by mprins** [comment]
see also #456 (which is about parsing localized numbers)

**Comment by menion** [comment]
Thanks for pointing on this issue. I've already noticed it and also checked it's PR. Anyway, it is a little different problem. #456 talk about WKTReader and parsing values into the `Geometry` object.

What I talk here is opposite, it is about format of `Geometry` into WKT text. And it is not fixed by mentioned PR.

**Comment by menion** [comment]
Hello, sorry for very late response. Meanwhile, I've changed our usage from WKT to WKB, so this problem exists no more for now. So I cannot confirm that #409 fixed this (but as I looked on changes, I do not think so, so just keep it in mind).
Thanks for understanding.
