### ISSUE TITLE
Where can I find documentation on the various specifications for reading and writing geometry?

### ISSUE THREAD

**Issue by IanKemp** [locationtech/jts#481]
I have two libraries written in two different languages that supposedly both support (E)WKB, but one of these libraries cannot consume the EWKB produced by the other. Hence I'm trying to debug what's going on by looking at the generated WKB and comparing it to JTS source, as it appears that JTS is the de facto standard.

However I'd very much like to be able to check these libraries against a specification so that if (when) I find a bug, I can simply point the authors to the relevant section of the spec. For example, where is it specified that writing a WKB with undefined ordinate values should cause the writer to emit NaN?

If anyone could point me to this specification it would be greatly appreciated.

**Comment by FObermaier** [comment]
Well-Known-[Text|Binary] is defined in OGC's _Simple Feature Access, Part 1 - Common Architecture_:
https://www.opengeospatial.org/standards/sfa
Chapter 8

**Comment by IanKemp** [comment]
I poked around the OGC site for a while but didn't manage to find that doc, thanks a mil @FObermaier!

**Comment by IanKemp** [comment]
Ugh, wait - I can't see anything in that doc that specifies what should happen if you emit a WKB in a format where the coords aren't specified.

The closest is section 6.1.4.2 that states that requesting and undefined coord value should return NIL, but the document doesn't appear to define what NIL's actual value is. There are also no examples in the WKT/WKB representations (ch 7 and 8) that have an input that is output in a way that Z/M would end up being NIL.

You don't happen to know where I can find that info in particular, @FObermaier ?

**Comment by FObermaier** [comment]
I suppose it is not particularily defined in the mentioned spec. Maybe that is handled in [ISO 19125](https://www.iso.org/standard/40114.html).

**Comment by IanKemp** [comment]
Unfortunately the ISO 19125 spec costs about CHF 158 more interest than I have in getting an answer. Maybe someone with a copy could fill us in?

**Comment by dr-jts** [comment]
> Which leads to a more important question: **if NaN is not covered by the official spec, why bother allowing such values to be emitted (and/or read) at all**? Wouldn't it make far more sense that a WKT/WKB writer specified to write 4 dimensions would throw an exception if passed a Geometry with fewer dimensions? (Requesting a writer to emit **fewer** dimensions than the input, of course, should continue to work.)

Yes, that might make more sense.  Although throwing an exception is really a last resort.  If this situation can occur, then the client code likely needs to be written to handle the exception, or more likely ensure that it can't happen in the first place.  And in that case, it's the client code which is preventing the situation from occurring, not JTS. And that can be done with the current JTS behaviour.

I think you are trying to "overdrive" the spec.  If the specification doesn't cover a given situation, then it is up to you to avoid entering that situation in the first place.
