### ISSUE TITLE
Polygon Area Calculation or Perimeter

### ISSUE THREAD

**Issue by jvoyatz** [locationtech/jts#493]
Hello,
I want to make a question.

I have already seen that methods like getArea() and getLength() return the area and the perimeter as well but i am not sure if anything else to be done is needed.

Apart from that i don't know what the return value of getArea() means. For instance, it could be square meters etc?

Thanks.

**Comment by jnh5y** [comment]
Hi @jvoyatz, JTS is handling geometries and it does not keep a notion of unit of measurement.  As such, the units for the coordinates represent the distance (and square units for the area).  If your geometries represent coordinates measured in meters, then yes, the area would be in square meters.

On the other hand, if your data is represented in degrees of longitude and latitude, the area would be in 'square degrees' which isn't a very sensible thing to work with.  Generally, to calculate meters from lon-lat coordinates, you'll want to use something like GeoTools's GeodeticCalculator (https://docs.geotools.org/stable/userguide/library/referencing/calculator.html)
