### ISSUE TITLE
WKB representation of POLYGON EMPTY

### ISSUE THREAD

**Issue by jagill** [locationtech/jts#508]
When JTS makes a WKB for POLYGON EMPTY, it strangely specifies that there is 1 ring with 0 coordinates.  Esri specifies 0 rings.  Both libraries parse both forms of WKB fine.

The WKB spec for polygons, as I've parsed it (please correct me if wrong!) is:
1 byte: big/little endian
4 bytes: uint32 specifying geometry type (3 for polygon)
4 bytes: uint32 specifying how many rings
for each ring:
  4 bytes: uint 32 specifying how many points in the ring
  for each point:
    8 bytes: double specifying x-coordinate
    8 bytes: double specifying y-coordinate

OGC does not specify how to handle empty geometries (as usual).

When JTS makes a WKB for a POLYGON EMPTY, it produces the expected endian and type bytes.  It then has a 1 in the 5th byte, and a 0 in the 6th byte.  (Esri has a 0 in the 5th byte, and no 6th byte).  This is making cross-library testing slightly more challenging, and the esri version is more intuitive to me.  However, I can't say that either version is "to spec", since it's underspecified.

Thoughts?

**Comment by dr-jts** [comment]
As another data point, for POLYGON EMPTY PostGIS emits WKB as the endian byte and type word, followed by a word of value 0, indicating no rings.  This seems like the canonical form to me.

I agree the JTS representation is odd.  It's due to the (also regrettable) choice to represent an empty polygon as having an empty exterior ring.  This should be changed, if it can be done without breaking too much.  Then the WKB would match the PostGIS form.

It's really too bad the spec is so lacking in clarity about empty geometries.

**Comment by dr-jts** [comment]
Of course it's also possible to fix `WKBWriter` to detect empty polygons and emit the canonical WKB.  This is the simplest solution, I think.

**Comment by jagill** [comment]
That makes sense.  If PostGIS emits a WKB with 0 rings, that suggests GEOS does too.  If this is the case, the proposed change would also make GEOS and JTS more compatible with each other,

**Comment by dr-jts** [comment]
> That makes sense. If PostGIS emits a WKB with 0 rings, that suggests GEOS does too. If this is the case, the proposed change would also make GEOS and JTS more compatible with each other,

Actually PostGIS has it's own implementation of WKB.  

GEOS *probably* does the same thing as JTS.  If so, we should port the JTS fix to GEOS as well.

**Comment by pramsey** [comment]
GEOS represents `POLYGON EMPTY` using polygon-with-zero-holes, not polygon-with-one-empty-hole, so it's consistent with PostGIS and general practice.

**Comment by dr-jts** [comment]
Well then clearly JTS needs to change to that semantic.

**Comment by jagill** [comment]
Great!  Is this something reasonable to get in by 1.18.0?

If I can work through the Eclipse foundation CLA issue, I'll try to put up a PR.  But don't wait for me.
