### ISSUE TITLE
Geometry.union for default precision model fails with TopologyException

### ISSUE THREAD

**Issue by stmoebius** [locationtech/jts#511]
I'm aware of issue #288. However, that issue deals with fixed precision, where I'm using the default, which I understand is floating. The following code fails when using JTS 1.16. The corresponding test case for JTS 1.13, however, works just fine.

```java
public class Test {
	private static final String geometryStr1 = "POLYGON ((11.569 48.223, 11.569 48.22, 11.57 48.22, 11.57 48.219, 11.571 48.219, 11.571 48.216, 11.572 48.216, 11.572 48.214, 11.571 48.214, 11.571 48.212, 11.57 48.212, 11.57 48.209, 11.571 48.209, 11.571 48.208, 11.572 48.208, 11.572 48.207, 11.573 48.207, 11.573 48.206, 11.574 48.206, 11.574 48.205, 11.577 48.205, 11.577 48.206, 11.578 48.206, 11.578 48.207, 11.58 48.207, 11.58 48.206, 11.581 48.206, 11.581 48.205, 11.586 48.205, 11.586 48.208, 11.588 48.208, 11.588 48.209, 11.589 48.209, 11.589 48.21, 11.59 48.21, 11.59 48.208, 11.594 48.208, 11.594 48.209, 11.595 48.209, 11.595 48.213, 11.592 48.213, 11.592 48.214, 11.593 48.214, 11.593 48.218, 11.589 48.218, 11.589 48.219, 11.586 48.219, 11.586 48.222, 11.582 48.222, 11.582 48.226, 11.579 48.226, 11.579 48.225, 11.578 48.225, 11.578 48.224, 11.577 48.224, 11.577 48.223, 11.569 48.223), (11.58 48.215, 11.58 48.216, 11.582 48.216, 11.582 48.215, 11.583 48.215, 11.583 48.213, 11.582 48.213, 11.582 48.215, 11.58 48.215))";
	private static final String geometryStr2 = "POLYGON ((11.679 48.198, 11.679 48.194, 11.682 48.194, 11.682 48.192, 11.685 48.192, 11.685 48.191, 11.688 48.191, 11.688 48.192, 11.689 48.192, 11.689 48.193, 11.694 48.193, 11.694 48.192, 11.695 48.192, 11.695 48.188, 11.697 48.188, 11.697 48.187, 11.7 48.187, 11.7 48.191, 11.703 48.191, 11.703 48.19, 11.704 48.19, 11.704 48.189, 11.708 48.189, 11.708 48.19, 11.709 48.19, 11.709 48.194, 11.708 48.194, 11.708 48.195, 11.705 48.195, 11.705 48.196, 11.703 48.196, 11.703 48.199, 11.702 48.199, 11.702 48.2, 11.699 48.2, 11.699 48.204, 11.696 48.204, 11.696 48.203, 11.694 48.203, 11.694 48.202, 11.692 48.202, 11.692 48.204, 11.689 48.204, 11.689 48.203, 11.687 48.203, 11.687 48.206, 11.683 48.206, 11.683 48.203, 11.681 48.203, 11.681 48.202, 11.68 48.202, 11.68 48.198, 11.679 48.198))";

	@org.junit.jupiter.api.Test
	public void testUnion113() throws Exception
	{
		final com.vividsolutions.jts.io.WKTReader reader = new com.vividsolutions.jts.io.WKTReader();
		final com.vividsolutions.jts.geom.Geometry geometry1 =  reader.read(geometryStr1);
		final com.vividsolutions.jts.geom.Geometry geometry2 =  reader.read(geometryStr2);

		geometry1.union(geometry2);
	}
	
	@org.junit.jupiter.api.Test
	public void testUnion116() throws Exception
	{
		final org.locationtech.jts.io.WKTReader reader = new org.locationtech.jts.io.WKTReader();
		final org.locationtech.jts.geom.Geometry geometry1 =  reader.read(geometryStr1);
		final org.locationtech.jts.geom.Geometry geometry2 =  reader.read(geometryStr2);

		geometry1.union(geometry2);
	}
}
```

The exception is 
`org.locationtech.jts.geom.TopologyException: found non-noded intersection between LINESTRING ( 11.582 48.216, 11.582 48.215 ) and LINESTRING ( 11.582 48.213, 11.582 48.215 ) [ (11.582, 48.215, NaN) ]
	at org.locationtech.jts.noding.FastNodingValidator.checkValid(FastNodingValidator.java:140)
	at org.locationtech.jts.geomgraph.EdgeNodingValidator.checkValid(EdgeNodingValidator.java:81)
	at org.locationtech.jts.geomgraph.EdgeNodingValidator.checkValid(EdgeNodingValidator.java:46)
	at org.locationtech.jts.operation.overlay.OverlayOp.computeOverlay(OverlayOp.java:231)
	at org.locationtech.jts.operation.overlay.OverlayOp.getResultGeometry(OverlayOp.java:183)
	at org.locationtech.jts.operation.overlay.OverlayOp.overlayOp(OverlayOp.java:86)
	at org.locationtech.jts.operation.overlay.snap.SnapIfNeededOverlayOp.getResultGeometry(SnapIfNeededOverlayOp.java:75)
	at org.locationtech.jts.operation.overlay.snap.SnapIfNeededOverlayOp.overlayOp(SnapIfNeededOverlayOp.java:37)
	at org.locationtech.jts.geom.Geometry.union(Geometry.java:1407)
	at com.stmoebius.Test.testUnion116(Test.java:25)
`

**Comment by dr-jts** [comment]
In fact, even using the default floating precision model, overlay operations may still encounter TopologyExceptions (although this is less likely than when using fixed precision). This is usually due to nearly-coincident linework.

However, in this case the geometries are disjoint, which does not usually cause topology errors.  So looking further, it turns out that the first geometry is invalid.  This also causes `TopologyException`s.

In this case you can probably run `buffer(0)` to fix the invalid geometry.

**Comment by stmoebius** [comment]
Yeah, that appears to solve the problem. In what way is the geometry invalid?

Also, I seem to observe that using CascadedPolygonUnion returns the same result without an exception. If I "know" that my input consists of only polygons, would using CascadedPolygonUnion be a viable alternative?

**Comment by dr-jts** [comment]
Geometry is invalid due to self-touching hole.

CascadePolyognUnion has an optimization to simply combine polygons if it detects they are disjoiont.  So if that happens, GIGO.  But you can't rely on this working.  In general, JTS operations require valid geometry (in particular, overlay ops)

**Comment by stmoebius** [comment]
Thanks a lot. So I presume this is not a bug in JTS, it just has become stricter from 1.13 to 1.16? If so, I'll close the ticket.

**Comment by dr-jts** [comment]
That's right, not a bug.  And yes, i think there was a recent change which introduced stricter checking for invalidity.
