### ISSUE TITLE
Is GeometryFactory thread safe?

### ISSUE THREAD

**Issue by karussell** [locationtech/jts#512]
I found out that PreparedGeometryFactory seems to be thread safe according to the source and #162. 

I cannot find information about this topic for GeometryFactory. Did I overlook something?

**Comment by dr-jts** [comment]
As far as I know GeometryFactory is thread-safe. And that is certainly the intention (even if not documented as such at the moment).

**Comment by karussell** [comment]
Thanks! So I can define it as a static final variable and share it safely across threads. Sounds good. 

Should I add this to some documentation or the javadocs?

**Comment by dr-jts** [comment]
> Should I add this to some documentation or the javadocs?

Sure, feel free to make a PR to add it to the Javadoc (following previous pattern if possible)

**Comment by dr-jts** [comment]
Closed by https://github.com/locationtech/jts/commit/3165996a8423b7ee4784a456df32a62f6b254776
