### ISSUE TITLE
CoordinateArrays.scroll missing functionality

### ISSUE THREAD

**Issue by FObermaier** [locationtech/jts#527]
`CoordinateArrays` has a single `scroll` function:
* `scroll(Coordinate[] coordinates, Coordinate first)`

`CoordinateSequences` has three scroll functions:
* `scroll(CoordinateSequence coordinates, Coordinate first)`
* `scroll(CoordinateSequence coordinates, int indexOfFirstCoordinate)`
* `scroll(CoordinateSequence coordinates, int indexOfFirstCoordinate, boolean ensureRing)`

Additionally `CoordinateArrays.scroll` skrews up the input array when it forms a ring.

**Comment by dr-jts** [comment]
Fixed by #528
