### ISSUE TITLE
Bug(?) in GeometryFactory.equals(Geometry g) with LineString comparison

### ISSUE THREAD

**Issue by johanneshiry** [locationtech/jts#531]
Hi,

a strange error occurred in one of our projects making use of this library when we compare objects holding `LineString` as fields. 
After investigating this issue a little bit deeper I would _assume_ that the root of the issue is the implementation of `GeometryFactory.equals(Geometry g)` or something around it. 

**Problem Description:**
We use `LineString` fields in different classes that define their own `equals()` and `hashCode()` methods. In the following scenario, the comparison between two of these objects seems not to work as expected due to the implementation of the `equals()` method in `GeometryFactory`:

Consider two objects of `LineString` with exactly the same attributes, where (by intention) both coordinates are exactly the same. If you now compare these two `LineString` objects with `line1.equals(line2)` it returns `false` (where true would be expected), but if you call `line1.equalsExact(line2))` it returns true. 

If both `LineString` objects have different coordinates  `line1.equals(line2)` becomes `true` (which is actually what you're expecting). 

This behavior causes problems, when you put `LineString` objects into wrapper objects and then check for for equality of these objects, because even if they're equal by their attributes, the equals method returns false. 

While it might be questionable from a logical perspective if it makes sense to put the same coordinate twice into a `LineString` object, there might be scenarios (and in our case there are some) where this might make sense and then this behavior of the equals method might be confusing.

Any help on this issue would be really appreciated! The issue can be fully reproduced by the script below. 

If you need any more information, pls let me know.

**Environment:**
- Java 1.8 / Java 11

**Reproducibility:**
```java
import org.locationtech.jts.geom.LineString;
import org.locationtech.jts.io.ParseException;
import org.locationtech.jts.io.geojson.GeoJsonReader;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;


public class GeometryEqualBug {

    public static void main(String[] args) throws ParseException {

        // two line strings with two points each, where both points have exactly the same coordinate
        System.out.println("======= 2 linestings with 2 points each, where both points have exactly the same coordinate =======");
        LineString line1 = (LineString) new GeoJsonReader()
                        .read("{ \"type\": \"LineString\", \"coordinates\": [[7.39249992,51.81000137], [7.39249992,51.81000137]]}");

        LineString line2 = (LineString) new GeoJsonReader()
                        .read("{ \"type\": \"LineString\", \"coordinates\": [[7.39249992,51.81000137], [7.39249992,51.81000137]]}");

        Set<LineString> lines1 = new HashSet<>(Arrays.asList(line1));

        System.out.println("Line1.equals(Line2): " + line1.equals(line2)); // false <-- expected to be true!
        System.out.println("Line1.equalsExact(Line2): " + line1.equalsExact(line2)); // true
        System.out.println("HashSet with line1 contains line2: " + lines1.contains(line2)); // true


        ComplexObjectWithLineString o1 = new ComplexObjectWithLineString(line1);
        ComplexObjectWithLineString o2 = new ComplexObjectWithLineString(line2);

        Set<ComplexObjectWithLineString> objects1 = new HashSet<>(Arrays.asList(o1));

        System.out.println("HashSet with complexObjectWithLineStrings contains o2: " + objects1.contains(o2)); // false <-- expected to be true!
        System.out.println("==============\n");


        // two line strings with two points each, where both points differ in coordinates
        System.out.println("======= 2 linestings with 2 points each, where both points differ in coordinates =======");
        LineString line3 = (LineString) new GeoJsonReader()
                        .read("{ \"type\": \"LineString\", \"coordinates\": [[7.39249992,51.81000138], [7.39249992,51.81000137]]}");

        LineString line4 = (LineString) new GeoJsonReader()
                        .read("{ \"type\": \"LineString\", \"coordinates\": [[7.39249992,51.81000138], [7.39249992,51.81000137]]}");

        Set<LineString> lines2 = new HashSet<>(Arrays.asList(line3));

        System.out.println("Line3.equals(Line4): " + line3.equals(line4)); // true (as expected)
        System.out.println("Line3.equalsExact(Line4): " + line3.equalsExact(line4)); // true (as expected)
        System.out.println("HashSet with line3 contains line4: " + lines2.contains(line4)); // true (as expected)

        // the new
        ComplexObjectWithLineString o3 = new ComplexObjectWithLineString(line3);
        ComplexObjectWithLineString o4 = new ComplexObjectWithLineString(line4);

        Set<ComplexObjectWithLineString> objects2 = new HashSet<>(Arrays.asList(o3));

        System.out.println("HashSet with complexObjectWithLineStrings contains o4: " + objects2.contains(o4)); // true (as expected)
        System.out.println("==============\n");

    }

    private static class ComplexObjectWithLineString {

        private final LineString lineString;

        public ComplexObjectWithLineString(LineString lineString) {
            this.lineString = lineString;
        }

        @Override
        public boolean equals(Object o) {
            if(this == o)
                return true;
            if(o == null || getClass() != o.getClass())
                return false;
            ComplexObjectWithLineString wrapper = (ComplexObjectWithLineString) o;
            return lineString.equals(wrapper.lineString);
        }

        @Override
        public int hashCode() {
            return Objects.hash(lineString);
        }
    }
}
```

**Comment by dr-jts** [comment]
This occurs because LineStrings with only a single unique point are invalid.  The reason for this semantic in JTS is due to my reading of the OGC Simple Features Specification.  It may not actually be very useful, but it's been in place for a long time now.  I haven't traced into the `equals` implementation to see exactly where it computes false.  

I suppose it might be possible to allow `equals` to compute true for identical single-point lines, but that would depend on the DE-9IM computation working out. It might not, because a single point linestring is probably considered to be closed, and hence has no boundary.  Would have to think this one through.

**Comment by johanneshiry** [comment]
Thanks for the reply and the explanation. I'm not familiar with the OGC Simple Features Specification, but I see the point from a logical perspective that LineStrings with only a single unique point are invalid. 

From my point of view, it would have been helpful if instead of silently allowing the build of an invalid LineString, an Exception would have been thrown that the resulting LineString is invalid due to the usage of exactly equal points. It is actually already done like this for other cases e.g. if you only provide one Point when constructing a LineString. This would prevent building an incomparable LineString in a 'fail fast' manner. 

Otherwise, as it is implemented now, one would _assume_ that the LineString that has been build is valid and that the comparison should work even for two exactly equal points.

**Comment by dr-jts** [comment]
JTS does't check or enforce validity in constructors for the following reasons:

* it can be expensive to check validity
* in some cases validity is already known, so there is no need to check it again
* if invalid geometry can not be created then there is no way to check whether geometry is invalid!

The only exception to this rule is that of structural invalidity - e.g. a single point used to create a LineString.

If you are expecting to encounter invalid geometry, you need to check for this condition explicitly.

**Comment by johanneshiry** [comment]
Thanks for these further explanations. We ended up with a small workaround for our scenario. 

From our perspective this issue can be closed then.
