### ISSUE TITLE
Does IsValidOp.isValid return true for Polygons with coincident points?

### ISSUE THREAD

**Issue by roeyshemtov** [locationtech/jts#540]
According to this issue:
https://github.com/locationtech/jts/issues/486

Geometries from Polygon types with consecutive point return true on IsValidOp.isValid,

example:

```
        ArrayList<Coordinate> points = new ArrayList<Coordinate>();
        points.add(new Coordinate(0,0));
        points.add(new Coordinate(0,1));
        points.add(new Coordinate(1,1));
        points.add(new Coordinate(1,1));
        points.add(new Coordinate(1,0));
        points.add(new Coordinate(0,0));
        Coordinate[] coords = (Coordinate[]) points.toArray(new Coordinate[]{});
        Polygon polygon = new GeometryFactory().createPolygon(coords);
        System.out.println(polygon.isValid());

```
`true`

I guess it is returning true for all types of gemotry (e.g LineString, MultiPolygon...).

Is that okay? polygon can have consecutive points?
I know that you can`t insert elasticsearch geometry with consecutive points.

**Comment by dr-jts** [comment]
Yes, correct, Polygons with *conincident* points are considered valid.

This is because topologically speaking coincident points are irrelevant.

**Comment by roeyshemtov** [comment]
@dr-jts thanks for answer,
I asked it because i have Polygon that it`s coordinate attribute doesn`t have coincident points, but it`s exterior ring does have coincident point, and isValid returning true, altaugh I can`t index it for example.
Is coincident points is correct according to JTS community, or according to official docs?

**Comment by dr-jts** [comment]
> I asked it because i have Polygon that it's coordinate attribute doesn't have coincident points, but it's exterior ring does have coincident point, and isValid returning true, altaugh I can`t index it for example.

I don't understand your description.

> Is coincident points is correct according to JTS community, or according to official docs?

It's my reading of the official docs.  But there is debate about this.

Generally JTS tries to be as lenient as possible with what it accepts.  It's not very helpful to reject geometry, since that means it can't be fixed or represented in the JTS model, thus requiring some other potentially complex representation to be created by the client.

**Comment by roeyshemtov** [comment]
I understand,
but probably people that used JTS and want to know for 100% that their geometry is valid, should trust the isValid method.
And yet seems like consecutive/coincident point is valid by JTS, but does not valid by other frameworks(such as elasticsearch).
I think a fix should be made to isValid function, but if JTS community has decided already that it is valid, so i`ll close the issue.

**Comment by dr-jts** [comment]
It's hard to get every codebase to agree on semantics.  Impossible, even.  Perhaps ElasticSearch should provide their own isValid implementation.  Or even better, sanitize the input if they don't like coincident points (which isn't hard to do). Failing that, you could do this yourself.
