### ISSUE TITLE
Update FAQ date when updating the faq doc

### ISSUE THREAD

**Issue by initialdmg** [locationtech/jts#542]
[FAQ](https://locationtech.github.io/jts/jts-faq.html) page shows that this doc was last updated at 2008, then something appears in my mind that that may be the year when vividsolutions released ver 1.10 , and it's really outdated. I checked the gh-pages branch, its last commit was at 2018, yeah~it is updating.

So i think it will be more clear for the reader that they are reading a latest and continuously updating document, if authors and contributors modify the update date in passing when updating the faq 😄

**Comment by dr-jts** [comment]
Good point, thanks. Fixed by https://github.com/locationtech/jts/commit/63f5f9969bc277cce55cad603c30089de20a4341#diff-3aaef0d9675f935f11fc70296db9e841
