### ISSUE TITLE
org.locationtech.jts.geom.impl not exposed in OSGI environment

### ISSUE THREAD

**Issue by qtran** [locationtech/jts#545]
Hi, 
I would like to use the classes in 'org.locationtech.jts.geom.impl' in a OSGI environment, unfortunately that package is not exported. Any plans to expose this?

I tested this with jts-core 1.16.1

Kind regards

**Comment by jnh5y** [comment]
Generally, this sounds reasonable.  

Speaking for myself, I'm not savvy on OSGI.  What changes would need to be made?  Are you able to contribute to the project directly (see https://github.com/locationtech/jts/blob/master/CONTRIBUTING.md for details)?

**Comment by qtran** [comment]
You'll need to adapt the configuration of the org.apache.felix:maven-bundle-plugin (modules/core/pom.xml)
I should be able to contribute to the project, I'll try to open a pull request in the near future

**Comment by qtran** [comment]
Fixed with 1.17.0
