### ISSUE TITLE
	extractPoint(double index, double offsetDistance) what is the second argument, what unit measurement is used and what direction is the offset?

### ISSUE THREAD

**Issue by b2bking** [locationtech/jts#555]
for instance I have index in the middle of polyline and I need to get point 50 meters to the right and second point 50 meters to the left, can I use this method to accomplish my task?

**Comment by dr-jts** [comment]
The units of measurement are the same as the coordinates (which are implicit).

The offset direction is specified in the [Javadoc](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/linearref/LengthIndexedLine.html#extractPoint-double-double-):

> The computed point is offset to the left of the line if the offset distance is positive, to the right if negative.
