### ISSUE TITLE
Link to SF SQL Standard on IntersectionMatrix javadoc page is broken

### ISSUE THREAD

**Issue by ianturton** [locationtech/jts#566]
If you goto https://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/IntersectionMatrix.html - the link to OGC 99-049 OpenGIS Simple Features Specification for SQL, is broken it should probably be http://portal.opengeospatial.org/files/?artifact_id=829 if you want to keep the link to 99-049 or possibly http://portal.opengeospatial.org/files/?artifact_id=25354 is you want to link to the newer SF Part 1 (http://portal.opengeospatial.org/files/?artifact_id=25355) where the relational operators are discussed in 6.1.15 and DE-9IM in 6.1.15.2

**Comment by dr-jts** [comment]
Fixed by https://github.com/locationtech/jts/commit/32806aadd72a90b4deba5707504fcdcda941415f

Thanks @ianturton !
