### ISSUE TITLE
Orientation.isCCW returns wrong result for simple non-intersecting polygon

### ISSUE THREAD

**Issue by avinash-anand** [locationtech/jts#570]
Hi Team

For given below data, when checked for `Orientation.isCCW`, it returns true, while the data is not CCW.
Data in `geojson` format:-
`{"type":"Polygon","coordinates":[[[-90.51024983023109,41.50299067633676],[-90.51012823887969,41.50285720667567],[-90.51010891123467,41.502825538523545],[-90.51009963239215,41.50279368911433],[-90.51010319964833,41.50273782414724],[-90.51017736674304,41.50252996564051],[-90.51031142673386,41.50218344066586],[-90.51036115387318,41.50212418280591],[-90.51040028758659,41.50209565855619],[-90.51048061265524,41.50206012585747],[-90.51068679376839,41.502022105603054],[-90.51074426316445,41.502005938687006],[-90.51079124632464,41.50198718850645],[-90.51083567804037,41.501961053868214],[-90.51097779654076,41.501837849312786],[-90.51100485751732,41.50182819970854],[-90.51103931751665,41.50182888733242],[-90.51105521801526,41.50183569900754],[-90.51106939694992,41.5018491347428],[-90.51134616125044,41.502340851290874],[-90.51024983023109,41.50299067633676]]]}`

when testing this data on [geojsonlint](https://geojsonlint.com), it returns `Line 1: Polygons and MultiPolygons should follow the right-hand rule`, meaning this polygon is not CounterClockWise.

We also tested on postgis :
`
select 
st_ispolygonccw(
    st_geomfromgeojson(
'{"type":"Polygon","coordinates":[[[-90.51024983023109,41.50299067633676],[-90.51012823887969,41.50285720667567],[-90.51010891123467,41.502825538523545],[-90.51009963239215,41.50279368911433],[-90.51010319964833,41.50273782414724],[-90.51017736674304,41.50252996564051],[-90.51031142673386,41.50218344066586],[-90.51036115387318,41.50212418280591],[-90.51040028758659,41.50209565855619],[-90.51048061265524,41.50206012585747],[-90.51068679376839,41.502022105603054],[-90.51074426316445,41.502005938687006],[-90.51079124632464,41.50198718850645],[-90.51083567804037,41.501961053868214],[-90.51097779654076,41.501837849312786],[-90.51100485751732,41.50182819970854],[-90.51103931751665,41.50182888733242],[-90.51105521801526,41.50183569900754],[-90.51106939694992,41.5018491347428],[-90.51134616125044,41.502340851290874],[-90.51024983023109,41.50299067633676]]]}'
    )
)
`
Result: `false`

**Comment by dr-jts** [comment]
Looks fine to me.  JTS gives `Orientation.isCCW = false`.

**Comment by avinash-anand** [comment]
Sorry, I tested it wrong. Hence closed this issue.
