### ISSUE TITLE
Computing Point in Polygon at scale?

### ISSUE THREAD

**Issue by raunaq1990** [locationtech/jts#573]
Hi,

I am fairly new to JTS and geometry related processing. I am currently working on a Point in Polygon problem in my project, where I am dealing with about 5 million Points and about 1 million Polygons. My objective is to identify which all points belong to which all polygons.

Until now, i have been able to arrive at a brute force solution comparing each point against each polygon using the point.within(polygon) function, but this solution is taking hours to execute. With some initial research on the internet, I came across someone's post mentioning the usage of a QuadTree for optimizing search of Point in Polygon, but they haven't mentioned any detail on the approach. I went through the JTS documentation of QuadTree and Envelope, but I am still finding it difficult to arrive at a solution.

Any guidance on how to use QuadTree for addressing my problem, or any other suitable alternative approaches will be highly appreciated.

**Comment by dr-jts** [comment]
A quick answer:  
* Use an `STRtree` to index a `PreparedGeometry` created for each polygon
* query the tree by point envelope, and then test the `covers` method for each `PreparedGeometry` returned
