### ISSUE TITLE
Issue with RayCrossingCounter and coordinates with Measures

### ISSUE THREAD

**Issue by mukoki** [locationtech/jts#581]
Some algo may fail with coordinates with measures.
For example, with RayCrossingCounter.locatePointInRing(coord, coordSequence)
If CoordinateSequence is
dim = 4, measures = 0 (see previous bug report) : OK
dim = 4, measures = 1 (normal XYZM coordinate) : throws exception at ring.getCoordinate(i, p1)

Problem is that RayCrossingCounter.locatePointInRing tries to set the M of the XYZM coordinate to a default 3D Coordinate without M initialized in the method. I suppose XYM coordinates has the same problem in this case.

**Comment by dr-jts** [comment]
What previous bug report?
Can you supply a stack trace?
What kind of CoordinateSequence?
Can you supply code reproducing the problem?

**Comment by mukoki** [comment]
I added a PR with a test building a 4D XYZM CoordinateSequence which makes RayCrossingCounter#locatePointInRing fail
The fix I propose makes another test fail in Distance3DOp
I propose another fix for this failure consecutive to my first fix, but this is about 3d polygons projected to the XY, XZ or YZ plan, and I have not a clear idea about what all this code does.

**Comment by dr-jts** [comment]
Fixed by #589
