### ISSUE TITLE
Recommended way to translate older com.vividsolutions geometry to org.locationtech equivalents

### ISSUE THREAD

**Issue by integratedmodelling** [locationtech/jts#583]
I must mix APIs that still use JTS 1.13 with others that use the more modern org.locationtech packages. The package refactoring makes it safe to keep both versions in the same classpath, but there are situations where I get large geometries from the old API and must pass them to functions using the new. Is there a recommended way (or contributed project) to do that? Casting or serializing/deserializing could work if the memory image is identical, but even so it would feel very risky. 

Thank you,
ferdinando

**Comment by dr-jts** [comment]
You could write to WKB and read back from that.

**Comment by integratedmodelling** [comment]
Thanks Martin - just wanted to double-check for any endorsed method. For easy cut-and-paste reference if anyone needs it, this code does as suggested:

```
import org.integratedmodelling.klab.exceptions.KlabInternalErrorException;
import org.locationtech.jts.geom.Geometry;
import org.locationtech.jts.io.ParseException;
import org.locationtech.jts.io.WKBReader;

import com.vividsolutions.jts.io.WKBWriter;

public class JTSUtils {

	static WKBWriter wkbWriter = new WKBWriter();
	
	@SuppressWarnings("unchecked")
	public static <T extends Geometry, E extends com.vividsolutions.jts.geom.Geometry> T convert(E geometry) {
		String s = WKBWriter.toHex(wkbWriter.write(geometry));
		try {
			return (T)new WKBReader().read(WKBReader.hexToBytes(s));
		} catch (ParseException e) {
			throw // internal error
		}
	}
}
```
