### ISSUE TITLE
Geometry.Distance() allocates unnecessary arrayList

### ISSUE THREAD

**Issue by cmhodgson** [locationtech/jts#59]
The DistanceOp class makes use of the PolygonExtractor class, which makes an empty array to pass around to collect pieces of the geometry to calculate the distance between, but this is never used if there are no polygons in the distance calculation. This may seem minor but the distance operation is very basic and in some processing situations you may need to make millions of distance calculations; in my specific case these allocations caused the peak memory use of my program to increase from 2GB to 2.5GB. I think the DistanceOp class could be refactored to use more specific, optimized code for specific types of input geometry, rather than the current highly generalized approach which assumes the worst case of two multi-polygons and only afterward narrows down to the specific geometry types involved.
Another approach might be to refactor the PolygonExtractor into an iterator, rather than copying the polygon parts into a new list, it would allow iteration over the parts in-place, requiring less memory allocation and copying.

**Comment by AlexisDrogoul** [comment]
👍

**Comment by dr-jts** [comment]
Pull Request welcome!  Otherwise will have to wait for time to do this.

**Comment by dr-jts** [comment]
Curious to know more about your use case.  Are you seeing this as as hotspot?  If you are doing a lot of distance computation, perhaps [`IndexedFacetDistance`](https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/operation/distance/IndexedFacetDistance.java) might be of use?

**Comment by dr-jts** [comment]
@cmhodgson Is the issue the ArrayList which is allocated by PolygonExtracter even if there are no polygons?

Perhaps a simple dimension check could be made beforehand, and if dimension < 2 this code can be skpped.

**Comment by cmhodgson** [comment]
IndexedFacetDistance is interesting but still uses distanceOp, which then still had the problem that you have now solved. 
My use case was finding the closest street segment with a matching name to every address point in the province. There is already an index in place to narrow it down to all the segments with the matching name in the same locality so it isn't really worth the additional memory cost to index those groups spatially. The process only takes 5 mins but minimizing memory use is more important than speeding up the processing as it is a once a month process in production. The overhead of creating and collecting the extra arrays had essentially no effect on the performance time-wise but because of how sensitive Java is to the amount of garbage being collected, having these unused arrays lying around required an extra 1/2 GB of memory to be allocated to keep Java from throwing a "too much garbage collection" exception. 
I think I had considered a fix as simple as what you have now done but then got lost in a bunch of other semantic issues that I thought needed "fixing" and forgot about the simple alternative.

**Comment by dr-jts** [comment]
Good to know this is working for you, Chris.  

It seems it's more important to optimize Java memory use than performance (although often the two can be improved together).  The recent issue #165 is another example of this.
