### ISSUE TITLE
Request to update junit version

### ISSUE THREAD

**Issue by FObermaier** [locationtech/jts#607]
I tend to use IntelliJ IDEA Community as java editor, especially when working with this project.
This editor does not play with junit v3.7 and requires at least v3.8 so I kindly request to update junit to this version.

Thanks.

**Comment by mprins** [comment]
probably not but I don't recall any problems I ran into 10+ years ago switching from 3 to 4.

google is full of posts about migrating: https://www.google.com/search?hl=nl&ei=3Ox2X5G-Gsf9kwWGp7e4Dw&q=upgrade+junit+3+to+4&oq=junit+upgrade+3&gs_lcp=CgZwc3ktYWIQAxgAMgYIABAWEB46BAgAEEc6BAgAEBM6CAgAEBYQHhATUL-6AVjlvQFg_coBaABwAngAgAFbiAG0AZIBATKYAQCgAQGqAQdnd3Mtd2l6yAEIwAEB&sclient=psy-ab

**Comment by FObermaier** [comment]
I updated to v4.13 and rebuild the solution. It built without any severe problems, there are some deprecation warnings about using `junit.framework.Assert` class.

I don't know if the list is complete but here are some classes:
* KMLReaderTest
* BufferValidator
* GeometryOperationValidator

**Comment by dr-jts** [comment]
> I there are some deprecation warnings about using `junit.framework.Assert` class.

It would be nice to fix the deprecations.  Any idea what a fix would be?

**Comment by mprins** [comment]
I think the Assert class now lives in `org.junit.Assert` https://junit.org/junit4/javadoc/4.13/org/junit/Assert.html

**Comment by jnh5y** [comment]
@mprins Thanks!  @FObermaier I tried switching the imports and it seemed to work.  Here's a quick commit that does it: https://github.com/jnh5y/jts/commit/ee9975ed6bcdb41ea670c01a39d6689907714faf

**Comment by FObermaier** [comment]
Thanks
