### ISSUE TITLE
java.lang.NoClassDefFoundError: org/locationtech/jts/geom/Geometry

### ISSUE THREAD

**Issue by pipinoclaudia** [locationtech/jts#620]
I have a Maven project, which uses the lib "org.locationtech.jts". My maven pom has written using this dependencies: 

		<dependency>
			<groupId>org.locationtech.jts</groupId>
			<artifactId>jts-core</artifactId>
			<version>1.16.1</version>
		</dependency>

		<dependency>
			<groupId>org.locationtech.spatial4j</groupId>
			<artifactId>spatial4j</artifactId>
			<version>0.7</version>
		</dependency>

		<dependency>
			<groupId>org.locationtech.jts</groupId>
			<artifactId>jts-core</artifactId>
			<version>1.15.0</version>
			<exclusions>
				<exclusion>
					<groupId>xerces</groupId>
					<artifactId>xercesImpl</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

The problem is that running my application an exception has caught: 

java.lang.NoClassDefFoundError: org/locationtech/jts/geom/Geometry

Any solutions?

**Comment by jnh5y** [comment]
You seem to be including JTS twice.  I'd suggest picking one of the versions and try that.

**Comment by pipinoclaudia** [comment]
> You seem to be including JTS twice. I'd suggest picking one of the versions and try that.
