### ISSUE TITLE
(Java 11) GeometryFactory is not an ImageIO SPI class

### ISSUE THREAD

**Issue by kdumouchelle** [locationtech/jts#630]
Caused by: java.lang.ExceptionInInitializerError
Caused by: java.lang.IllegalArgumentException: com.vividsolutions.jts.geom.GeometryFactory is not an ImageIO SPI class

This is admittedly in the ancient version 1.11 (my company has a very slow and reactive FOSS process) but I have absolutely no idea if this has been resolved looking at the documentation. In locationtech/udig-platform#312 it was mentioned that java 10 upgrade for JTS was planned, but I don't see any mention of support for 9 or onwards in releases.

**Comment by jnh5y** [comment]
Good news!  Newer versions of JTS are being used in GeoTools / GeoServer on Java 11.  There were some changes which needed to be made in order for JTS, GeoTools, and GeoServer to upgrade.

If uDig upgrades to a version of GeoTools which supports Java 11, then the version of JTS it brings ought to work as well.

**Comment by fgdrf** [comment]
With [Release Candidate 2.2.0.RC1](https://github.com/locationtech/udig-platform/releases/tag/release%2F2.2.0.RC1) uDig supports Java 9+ Runtime Environments. Under the hood uDig has GeoTools 22.1 and jts 1.16.1
Hope this helps

**Comment by kdumouchelle** [comment]
Yeah it helps. It seems I'm going to have to update geotools as well in our project, which unfortunately will take foss approval (our company had already approved jts 17.1 and it simply hadn't made it into our baseline yet). It'll be a while before I can confirm whether the issue is still relevant with 17.1: I'll close this and make a new ticket if it's still an issue.

**Comment by shwetalishinde-tomtom** [comment]
Caused by: java.lang.IllegalArgumentException: org.geotools.jdbc.JDBCCallbackFactory is not an ImageIO SPI class
getting this error in jenkins job.
