### ISSUE TITLE
Is this geometry.Intersection method return correct?

### ISSUE THREAD

**Issue by alistuff** [locationtech/jts#659]
I want to calculate two polygon geometries intersection but the following code seem that return the incorrect result.

`WKTReader reader = new WKTReader();`
`Geometry left=reader.read(polygon 1 WKT);`
`Geometry right=reader.read(polygon 2 WKT);`
`Geometry intersection=left.intersection(right);`
`System.out.println(intersection)`
`Polygonizer polygonizer=new Polygonizer();`
`polygonizer.add(intersection);`
`Geometry result=polygonizer.getGeometry()`
`System.out.println(result)`

The intersection output :
GEOMETRYCOLLECTION (LINESTRING (113.12264458000004 23.410353323000038, 113.12264014000004 .... more

The result output :
MULTIPOLYGON (((113.1150908410001 23.402320665000047, 113.11504159600008 23.402253033000022, ...more

I use JTS TestBuilder run the same geometries as input and the result is :
GEOMETRYCOLLECTION EMPTY

What is the reason for this difference? 
Thanks

[polygon 1 wkt data](https://github.com/alistuff/testdata/blob/main/polygon1.wkt)
[polygon 2 wkt data](https://github.com/alistuff/testdata/blob/main/polygon2.wkt)

**Comment by dr-jts** [comment]
In JTS 1.18 this works for me in the TestBuilder.  

What version are you running?

![image](https://user-images.githubusercontent.com/3529053/103463671-e5673c00-4ce2-11eb-8f10-a08fb870a3c9.png)

**Comment by alistuff** [comment]
I use JTS 1.18 version too.
My test steps are:
   1. Overlay / intersection(polygon1,polygon2) => result 1
   2. Polygonizer/ polygonizer(result 1) => result 2

The result 2:   
In Java Code  => MULTIPOLYGON (((113.1150908410001 23.40232066...more
In Testbuilder => GEOMETRYCOLLECTION EMPTY

Is it a problem of JTS robustness?
Thanks.

**Comment by alistuff** [comment]
I used to use version JTS 1.14, now I use version 1.18 to get your results. 
How to set tolerance value when performing overlay operations? 
I do the same thing with ArcMap10.1 to get an empty collection.

**Comment by dr-jts** [comment]
JTS doesn't support a tolerance value for overlay, but `OverlayNG` does allow specifying a precision model scale factor, using the [`OverlayNG(geom, geom, opcode, scale)`](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/operation/overlayng/OverlayNG.html#OverlayNG-org.locationtech.jts.geom.Geometry-org.locationtech.jts.geom.Geometry-org.locationtech.jts.geom.PrecisionModel-int-) constructor.

In the TestBuilder you can run this using the functions under **OverlayNGSR**.

**Comment by alistuff** [comment]
I want to get the intersection result, but not the common boundary. What should I do? Can I ignore this part of the result by judging that the area of the returned result is less than MIN_AREA?

**Comment by alistuff** [comment]
@dr-jts  Do you have any advice to perform this operation? :)

**Comment by dr-jts** [comment]
> I want to get the intersection result, but not the common boundary. What should I do? 

* You can use the [`PolygonExtracter.getPolygons`](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/util/PolygonExtracter.html#getPolygons-org.locationtech.jts.geom.Geometry-) function to get just the polygons in the intersection result.
* You can use [`OverlayNG`](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/operation/overlayng/OverlayNG.html) directly to compute the intersection and call [`setStrictMode`](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/operation/overlayng/OverlayNG.html#setStrictMode-boolean-) to ensure that only the highest dimension elements are included in the result.

**Comment by alistuff** [comment]
Thanks. i work. :）
