### ISSUE TITLE
Insufficient Entropy CWE ID 331 - HotPixelIndex.java line 84

### ISSUE THREAD

**Issue by avinash-anand** [locationtech/jts#660]
Hi Team,

We are internally using `jts-core` for few of our use cases. Our applications goes through Vera code scans regularly. And there it identified this security issue in this library. I just wanted to bring this to your notice.
Below are the findings from Vera code.

```
Attack Vector: java.util.Random.nextInt

Number of Modules Affected: 1

Description: Standard random number generators do not provide a sufficient amount of entropy when used for security purposes. Attackers can brute force the output of pseudorandom number generators such as rand().

Remediation: If this random number is used where security is a concern, such as generating a session key or session identifier, use a trusted cryptographic random number generator instead. These can be found on the Windows platform in the CryptoAPI or in an open source library such as OpenSSL. In Java, use the SecureRandom object to ensure sufficient entropy.
```
the code it points to is [here](https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/noding/snapround/HotPixelIndex.java#L84).

Thanks.

**Comment by mprins** [comment]
how is using a random number for choosing a coordinate from an array of coordinates a security issue?  are you using Hotpixels in a security related context?
Note that this code is internal-use-only being in a non-public class

**Comment by avinash-anand** [comment]
I'm assuming Vera code internally scans all code and they may have defaults set that highlights this issue. We are not using this class. Hopefully this is not an issue. I thought to bring this to notice as this was reported in our reports.
