### ISSUE TITLE
Grid generator bug

### ISSUE THREAD

**Issue by ArtOshchepkov** [locationtech/jts#662]
I noticed that grid generator returns same polygons when making grid 1x4.
(Dividing  POLYGON ((0 0, 4 0, 4 4, 0 4, 0 0)) by 1 culmn and 4 rows returns POLYGON ((0 0, 0 1, 4 1, 4 0, 0 0)) four times which is wrong).

This reason could be found in the sources:
Consider line 81 of
https://github.com/locationtech/jts/blob/master/modules/core/src/test/java/org/locationtech/jts/generator/GridGenerator.java
`int row = numberRows==1?0:index / numberRows`
For ex, let number of columns = `1`, number of rows = `4`.
This line forces stuck the row in such case.

It seems like this line should be changed to
`int row = numberRows==1?0:index / numberColumns`

**Comment by dr-jts** [comment]
Good find, thanks.

Fixed by https://github.com/locationtech/jts/commit/9a6537e3b03af40cd01737e997ed7250f7a94c31
