### ISSUE TITLE
TopologyException in OverlayNG Intersection

### ISSUE THREAD

**Issue by jagill** [locationtech/jts#666]
Two 2-point LineStrings that seem like they are one floating point increment appart:
```
found non-noded intersection between LINESTRING ( -70.44853500000002 -23.098230000000004, -70.448535 -23.09823 ) and LINESTRING ( -70.44853500000002 -23.098230000000004, -70.44853499999999 -23.098229999999997 ) [ (-70.44853500000002, -23.098230000000004, NaN) ]
```

What's the expectation for things like this?  Should the default strategy handle it, or should we fall back to a different noding strategy?

**Comment by jagill** [comment]
Also, a similar one:
```
found non-noded intersection between LINESTRING ( 177.65832000000051 -38.84903150000009, 177.65832 -38.8490315 ) and LINESTRING ( 177.65832000000051 -38.84903150000009, 177.658293 -38.849027 ) [ (177.65832000000051, -38.84903150000009, NaN) ]
```

**Comment by jagill** [comment]
I should have made sure this issue is really hard before using up such a choice issue number.

**Comment by dr-jts** [comment]
> I should have made sure this issue is really hard before using up such a choice issue number.

Oh, this has the potential to be really hard alright!  If you have found robustness issues in OverlayNGRobust then they are the first that I've seen.

The lines in the TopologyException reports are usually very close - that's why they are causing a robustness problem.  But in theory the snapping should have taken care of them.  

Is it possible to get the data that causes the exception?

**Comment by jagill** [comment]
Just to be clear, I'm using `OverlayNG.overlay(left, right, OverlayNG.INTERSECTION)`, so if I should be putting in a non-default Noding strategy, do tell me.

I'm working on extracting the underlying geometries (and examples for some `side location conflict: arg 0 [ (-41.12081299153798, -3.011648338679938, NaN) ]` errors), but it will take a little bit.

**Comment by dr-jts** [comment]
> Just to be clear, I'm using `OverlayNG.overlay(left, right, OverlayNG.INTERSECTION)`, so if I should be putting in a non-default Noding strategy, do tell me.

Oh, yes, that is probably the cause.  Use `OverlayNGRobust(left, right, OverlayNG.INTERSECTION)` instead.  It contains snapping heuristics to deal with these kinds of errors. (Note that this is the class that is used by the `Geometry` overlay methods when `-Djts.overlay=ng` is set.)

**Comment by jagill** [comment]
Robust fixed these two TopologyExceptions, but there's still the `side location conflict` that I'm digging into...

**Comment by dr-jts** [comment]
`side location conflict` is often due to invalid input. But if not, let's see the data!

**Comment by jagill** [comment]
All current issues are due to invalid inputs.  OverlayNGRobust was the solution!
