### ISSUE TITLE
Where has jts-lab gone

### ISSUE THREAD

**Issue by FObermaier** [locationtech/jts#68]
In the sourceforge repository there is a module called `jts-lab` that contains `SnapRoundOverlayFunctions`:
https://sourceforge.net/p/jts-topo-suite/code/HEAD/tree/trunk/jts-lab/src/main/java/com/vividsolutions/jtslab/

I can't find this module and the in the current layout, has this approach been abandoned?

**Comment by dr-jts** [comment]
Good point, Frank.  I'm not quite sure what the strategy for this should be going forward.

The main goal of the JTS Lab module in SVN was to provide a place to make that code visible and secure.  With Git that's less critical, since experimental code can easily provided via individual repos and/or branches.  

That said, the integrated Lab module does have a few advantages:
* the code is always in synch with the master JTS branch
* it's obvious where to find it
* it can be part of the main Maven build
* in a few cases Lab code also required small changes to the core code,  This is easier to maintain in a module than in a branch, perhaps

Further thoughts are welcome.  And we will have to figure out a strategy for this soon.

**Comment by dr-jts** [comment]
The arguments _against_ the lab module I think are that the code is less tested and the design less stable than the other modules, so perhaps more properly belongs in a branch (or several) or an individual repo until it is ready to be integrated in core.

**Comment by dr-jts** [comment]
Perhaps this is similar to the GeoTools concept of community modules?  In this case the module would be in the master branch, but not part of the regular build (and thus not guaranteed to work).

**Comment by dr-jts** [comment]
@jodygarnett @jnh5y @lossyrob Any thoughts on this issue?

**Comment by jnh5y** [comment]
I like the idea of both options.  Maintaining code on separate branches gives a chance to work with core functionality.  That said, one of the JTS 2.0 ideas is to support drop-in / replacement operators.  If we do that, the extra functions / implementations can be in separate jars for advanced use cases.

**Comment by dr-jts** [comment]
It sounds like the simplest and most functional approach is to move the old jts-lab code into a new module "lab".  That will be a profile Maven build, so it doesn't _have_ to be kept fully functional at all times (although that will be the goal).

I'm not quite sure how to state the criteria for what gets into the LT lab module, as opposed to individual repos.  I'm a bit worried it will become messy and a burden to maintain (witness this current issue!).  However, probably better to have visibility of the code, which may spur some funding to clean things up.

**Comment by dr-jts** [comment]
Note that it's already viable in JTS 1 to provide extra functions in separate jars.  The lab will be an illustration of that.  However, the interface to the functions is completely informal and based on convention only (which has varied over time).

The JTS 2 approach is about formal support within JTS core for extensible operators.  It's not clear at the moment what the best approach is for providing this, but that may emerge over time.  I've been playing around with an idea similar to the new Functional programming support in Java 8, which has some nice capabilities.

**Comment by jodygarnett** [comment]
Put a nice "for sale" sign README in the lab directory; the following is
experimental ideas being considered for JTS and is not suitable for
production use. If you are interested any of the functionality here please
consider sponsoring JTS.

--
Jody Garnett

**Comment by FObermaier** [comment]
> It sounds like the simplest and most functional approach is to move the old jts-lab code into a new module "lab". That will be a profile Maven build, so it doesn't have to be kept fully functional at all times (although that will be the goal).

I favor this approach, too. IMHO the visibility when keeping it on a different branch is next to invisible.

**Comment by dr-jts** [comment]
Good ideas, all.  I will restore the lab module, and put appropriate caveats and terms-of-reference in a README.  I'll make it a Maven profile.

**Comment by dr-jts** [comment]
JTS Lab has now been restored.

https://github.com/locationtech/jts/tree/master/modules/lab
