### ISSUE TITLE
GeoJSONReader should read empty coordinates array as an empty Geometry

### ISSUE THREAD

**Issue by JamesRTaylor** [locationtech/jts#684]
For Point and Polygon, an empty coordinate array does not deserialize as an empty geometry, while it does for other types.  For example, 
   * {"type":"Point", "coordinates":[]} deserializes as POINT (0 0)
   * {"type":"Polygon", "coordinates"[]} causes an exception to be raised

Would be ideal if in both these cases, an empty point and an empty polygon are deserialized instead.

**Comment by JamesRTaylor** [comment]
I'd be happy to contribute a fix for this if you're open to it.

**Comment by dr-jts** [comment]
Is this for the `GeoJSONReader` ?

Would be happy to accept a PR for this.

**Comment by JamesRTaylor** [comment]
Yes, exactly.

Would you be up the related fix for https://github.com/locationtech/jts/issues/411 so that empty geometries for atomic types roundtrip?

**Comment by dr-jts** [comment]
Round-tripping would be nice, for sure.  I can put that on the todo list, or feel free to submit a PR.

**Comment by dr-jts** [comment]
It would be nice to handle both an empty array and `null`.

**Comment by JamesRTaylor** [comment]
FYI, I submitted a PR for this, @dr-jts.

**Comment by dr-jts** [comment]
Great, thanks.  I just merged it.

**Comment by JamesRTaylor** [comment]
Thanks for merging, @dr-jts. Do you know when the next release will occur yet?

**Comment by dr-jts** [comment]
No schedule for a release yet.  But the improvements are piling up fast, so will be soon-ish.
