### ISSUE TITLE
Polygonizer creates GeometryCollection with a single polygon

### ISSUE THREAD

**Issue by clarisma** [locationtech/jts#690]
In certain cases, Polygonizer.polygonize() will create a GeometryCollection containing one single Polygon, when it should instead simply return the Polygon itself.
This creates problems with subsequent operations like difference(), which does not accept GeometryCollections. 
The workaround is to turn a single-member collection into the member after calling Polygon.polygonize()

**Comment by dr-jts** [comment]
This is a subjective design issue.  Currently the design chooses uniformity of return type over convenience in the less-common case of having a single Polygon output.

**Comment by clarisma** [comment]
Ok, that makes sense. (I got a bit confused since getGeometry will return POLYGON or MULTIPOLYGON if the constructor argument extractOnlyPolygonal=true, vs. GEOMETRYCOLLECTION in all cases if extractOnlyPolygonal=false)

Thanks for all your work on this excellent library!
