### ISSUE TITLE
[JTS 1.16] Unexpected TopologyException when performing a union()

### ISSUE THREAD

**Issue by orosens** [locationtech/jts#695]
We are encoutering a random exception when performing a union of polygons. We use JTS 1.16.0.
The polygons are very simple shapes, squares with 4 points, here is an example : 
POLYGON ((147.43088524497458 -23.769756517872565, 147.46899517622472 -23.765914328974382, 147.47014373766143 -23.801824007071495, 147.43200720695464 -23.80559292617172, 147.43088524497458 -23.769756517872565))

When performing a union of several of these polygons (12 to 20), this exception pops up sometimes : 
```
org.locationtech.jts.geom.TopologyException: found non-noded intersection between LINESTRING ( 147.43398747048903 -23.87692002902414, 147.43398747048903 -23.87692002902462 ) and LINESTRING ( 147.43398747048903 -23.87692002902462, 147.43398747048903 -23.87692002902458 ) [ (147.43398747048903, -23.87692002902462, NaN) ]
   at org.locationtech.jts.noding.FastNodingValidator.checkValid(FastNodingValidator.java:140)
   at org.locationtech.jts.geomgraph.EdgeNodingValidator.checkValid(EdgeNodingValidator.java:81)
   at org.locationtech.jts.geomgraph.EdgeNodingValidator.checkValid(EdgeNodingValidator.java:46)
   at org.locationtech.jts.operation.overlay.OverlayOp.computeOverlay(OverlayOp.java:231)
   at org.locationtech.jts.operation.overlay.OverlayOp.getResultGeometry(OverlayOp.java:183)
   at org.locationtech.jts.operation.overlay.OverlayOp.overlayOp(OverlayOp.java:86)
   at org.locationtech.jts.operation.overlay.snap.SnapIfNeededOverlayOp.getResultGeometry(SnapIfNeededOverlayOp.java:75)
   at org.locationtech.jts.operation.overlay.snap.SnapIfNeededOverlayOp.overlayOp(SnapIfNeededOverlayOp.java:37)
   at org.locationtech.jts.geom.Geometry.union(Geometry.java:1407)
```
we use a CascadedPolygonUnion to perform this, but we also encounter the bug if we do a simple step by step union().

The unusual thing is that the LINESTRINGs have coordinates that do not match any of the polygon points used for the union.

The specificity of the shapes we are performing this union on is that they are adjacent : 
![image](https://user-images.githubusercontent.com/12375362/108336492-61a2d980-71d4-11eb-8c4e-33b0b57ccab6.png)
The ending points of one square are also the starting ones of the one on its right, and so on.

The bug seems to be affected by the precision of the WKT coordinates used to create the geometry. By removing a few trailing digitsfrom the WKT before the creating of the geometry, it didn't occur anymore on one of our test cases. However, it remaines very random, and this "trick" only solved one case of error.

We create our geometries using a simple WKTReader, using a FLOATING precision model.

Is this problem something you are aware of ? Any help would be greatly appreciated.

**Comment by dr-jts** [comment]
This is a well-known problem with earlier versions of JTS.  It's due to robustness problems caused by numerical roundoff error.  The FAQ has an [explanation](https://locationtech.github.io/jts/jts-faq.html#D1).

The good news is that JTS 1.18 implements a new overlay algorithm called OverlayNG, which solves most or all of these kinds of issues.  See this [blog post](http://lin-ear-th-inking.blogspot.com/2020/05/jts-overlay-next-generation.html) for more information.  At the moment you have to enable this using the `-Djts.overlay=ng` VM parameter.  It will become standard in a future release.

Please try this out and see if it solves your issues.  Also, feel free to post the actual dataset that is causing the issues - it's always good to have real-world data to test with.

**Comment by orosens** [comment]
Thank you for this quick and helpful answer. We will try again with the 1.18.0 version, you can considered this issue answered for.
Unfortunately, I cannot post the entire dataset, as I do not own it, and it is quite massive. But as I said, it consists of rows of adjacent squares smiliar to the one I produced above.
