### ISSUE TITLE
[Question] Finding intersection between multiple Polygons/MultiPolygons through a buffer

### ISSUE THREAD

**Issue by yakirs57** [locationtech/jts#697]
Hi,
I am new to the JTS package and something wasn't clear to me.
I want to find the intersection between multiple polygons/MultiPolygons through a buffer instead of iteration to save processing time.
Is there a way to do it?

**Comment by dr-jts** [comment]
Buffering won't find intersections.  But it can be used to perform a union, but executing `geom.buffer(0)`
