### ISSUE TITLE
SimpleSweepLineIntersector NullPointerException

### ISSUE THREAD

**Issue by micycle1** [locationtech/jts#705]
The `SimpleSweepLineIntersector.computeIntersections()` returns a NullPointerException (_"ss0" is null_), seemingly on all sets of input edges.

In comparison, the `SimpleMCSweepLineIntersector` and `SimpleEdgeSetIntersector` classes are fine.

I'm calling it like so:
```
RobustLineIntersector rli = new RobustLineIntersector();
SegmentIntersector si = new SegmentIntersector(rli, true, false);
EdgeSetIntersector i = new SimpleSweepLineIntersector();
i.computeIntersections(edgesA, edgesB, si);
```

which always leads to the following error (provided each edge set has at least 1 edge):

```
java.lang.NullPointerException: Cannot invoke "org.locationtech.jts.geomgraph.index.SweepLineSegment.computeIntersections(org.locationtech.jts.geomgraph.index.SweepLineSegment, org.locationtech.jts.geomgraph.index.SegmentIntersector)" because "ss0" is null
	at org.locationtech.jts.geomgraph.index.SimpleSweepLineIntersector.processOverlaps(SimpleSweepLineIntersector.java:137)
	at org.locationtech.jts.geomgraph.index.SimpleSweepLineIntersector.computeIntersections(SimpleSweepLineIntersector.java:118)
	at org.locationtech.jts.geomgraph.index.SimpleSweepLineIntersector.computeIntersections(SimpleSweepLineIntersector.java:60)
```

**Comment by dr-jts** [comment]
This class is not used anywhere in JTS, and is not recommended or supported for external use.  In fact, I"m hoping to remove the entire `GeometryGraph` API at some point soon (in favour of the `HalfEdge` graph structure).

So I'm not too interested in fixing this issue. Is there any reason you have to use this class?

**Comment by micycle1** [comment]
No reason I have to use the `SimpleSweepLineIntersector` in particular (in fact I'm using the `SimpleMCSweepLineIntersector` now).

If you're looking to remove the package, what's the preffered method for intersection detection between two sets of segments?

**Comment by dr-jts** [comment]
> what's the preffered method/approach for fast intersection detection between two sets of line segments?

Use [MCIndexSegmentSetMutualIntersector](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/noding/MCIndexSegmentSetMutualIntersector.html).

The `noding` package is the supported API for functionality around node detection and creation.

**Comment by micycle1** [comment]
Is this usage (particularly finding the intersection point) best practice?

```
final MCIndexSegmentSetMutualIntersector mci = new MCIndexSegmentSetMutualIntersector(
		SegmentStringUtil.extractSegmentStrings(g1));
final SegmentIntersectionDetector sid = new SegmentIntersectionDetector();

mci.process(SegmentStringUtil.extractSegmentStrings(g2), new SegmentIntersector() {

	@Override
	public void processIntersections(SegmentString e0, int segIndex0, SegmentString e1, int segIndex1) {
		sid.processIntersections(e0, segIndex0, e1, segIndex1);
		if (sid.getIntersection() != null) {
                    // do something with intersection point...
		}
	}

	@Override
	public boolean isDone() {
		return false;
	}
});
```

**Comment by dr-jts** [comment]
That seems reasonable, to avoid reproducing the somewhat complex intersection computation and analysis code inside `SegmentIntersectionDetector`.  You might need to set a flag or two on the `SegmentIntersectionDetector` to get it to find and report every intersection.
