### ISSUE TITLE
JAXB serialization to/from XML fails for Coordinates

### ISSUE THREAD

**Issue by seanrl** [locationtech/jts#711]
If you try to serialize a jts.Coordinate to/from XML, it will fail because it will find 2 options for the x, y, and z values (one public field, and one public getter).  An easy solution to this is to add `@XmlTransient` to the public fields (which really should just be private at some point, but I understand the desire for backwards compatibility).  Like so:

```
/**
   * The x-ordinate.
   */
  @XmlTransient
  public double x;

  /**
   * The y-ordinate.
   */
  @XmlTransient
  public double y;

  /**
   * The z-ordinate.
   * <p>
   * Direct access to this field is discouraged; use {@link #getZ()}.
   */
  @XmlTransient
  public double z;
  ```
  
  It would be great if we could get this in a future release.

**Comment by jnh5y** [comment]
@jodygarnett do you know anything about this annotation?

**Comment by bjornharrtell** [comment]
It seems like sound rationale to use this annotation and superficially it looks safe to use all the way back to at least Java 8, see https://docs.oracle.com/javase/8/docs/api/javax/xml/bind/annotation/XmlTransient.html.

**Comment by pomadchin** [comment]
But it is deprecated in JDK 9 and removed in JDK 11.

**Comment by bjornharrtell** [comment]
@pomadchin wow nice catch. Seems that it has since been removed and the recommended replacement is to depend on external implementation of it definitely making it less clear if this is a good idea to use here.

**Comment by mprins** [comment]
it is not a good idea to add `@XmlTransient` as I noted on the PR yesterday: https://github.com/locationtech/jts/pull/713#pullrequestreview-641461947

**Comment by seanrl** [comment]
@mprins Closing that PR, I agree with you.  Looking forward to the switch over to the JavaBean pattern eventually, and for now I'll just keep making internal releases for my needs.
