### ISSUE TITLE
Union of some peculiar geometries breakes commutative property

### ISSUE THREAD

**Issue by Cavva79** [locationtech/jts#718]
Hi @dr-jts,
always thanks for your support.
I'm experiencing some really strange behavior of union.
With at least those 2 geometries
```
POLYGON ((1740002.28 4981731.2, 1740011.15 4981551.29, 1740040.91 4981553.13, 1740095.86 4981555.41, 
          1740327.08 4981566.69, 1740318.17 4981748.35, 1740098.29 4981735.6, 1740002.28 4981731.2))
POLYGON ((1740002.2800000003 4981731.2, 1740006.7150060183 4981641.24487793, 
          1740002.28 4981731.2, 1740001.97 4981734.51, 1740002.2800000003 4981731.2))

```
the union between them is different if `GeometryA.union(GeometryB)` or `GeometryB.union(GeometryA)`. One of them get a LineString `LINESTRING (1740002.28 4981731.2, 1740001.97 4981734.51)` and the other a GeometryCollection containing that LineString `GEOMETRYCOLLECTION (LINESTRING (1740002.28 4981731.2, 1740001.97 4981734.51), POLYGON ((1740006.7150060183 4981641.24487793, 1740002.28 4981731.2, 1740098.29 4981735.6, 1740318.17 4981748.35, 1740327.08 4981566.69, 1740095.86 4981555.41, 1740040.91 4981553.13, 1740011.15 4981551.29, 1740006.7150060183 4981641.24487793)))`

Here a unit test I wrote for this purpose: https://github.com/Cavva79/jts-union-bug/blob/master/src/test/java/it/cd79/jts/union/bug/JtsUnionBug.java

Thank again

**Comment by dr-jts** [comment]
Confirmed that this does occur with the old overlay code.  But it does NOT occur with the new OverlayNG code.  

The old overlay is deprecated, so you should switch to using OverlayNG.  This is enabled by a [system property](https://github.com/locationtech/jts/blob/master/USING.md#jts-system-properties).

**Comment by Cavva79** [comment]
Thank you @dr-jts
