### ISSUE TITLE
Published Validation Suite

### ISSUE THREAD

**Issue by bjornharrtell** [locationtech/jts#72]
Was previously available at http://www.vividsolutions.com/jts/tests/index.html but no longer. Perhaps it can be published here on gh-pages?

**Comment by dr-jts** [comment]
That presentation of the validation suite hasn't been maintained for a long time, and in fact I'm not even sure the code in TestBuilder that generated it still runs!

The validation suite test source files are available here:  https://github.com/locationtech/jts/tree/master/modules/tests/src/test/resources/testxml

**Comment by dr-jts** [comment]
As I thought.  Probably difficult to resurrect, since the ability for TestBuilder to run a batch of tests was excised in order to simplify the code and UI.
