### ISSUE TITLE
Inconsistent behavior when querying Quadtree with null envelope

### ISSUE THREAD

**Issue by dbaston** [locationtech/jts#73]
An empty Quadtree can be happily queried with a null envelope, but a non-empty Quadtree will throw a NullPointerException in the same case.  For example:

```java
Quadtree qt = new Quadtree();
qt.query(null); // OK
qt.insert(new Envelope(0, 10, 0, 10), "some data");
qt.query(null); // NPE
```

It seems like a query with a null Envelope should either always return nothing (I'd lean towards this), or always throw an Exception.

**Comment by dr-jts** [comment]
Fixed by #80
