### ISSUE TITLE
TopologyException when generating a VoronoiDiagram

### ISSUE THREAD

**Issue by hallsbyra** [locationtech/jts#74]
To reproduce, use the following input in JTS TestBuilder and generate a plain VoronoiDiagram:

`POLYGON ((14.7119 201.6703, 74.2154 201.6703, 74.2154 166.6391, 14.7119 166.6391, 14.7119 201.6703))`

The error message:

>com.vividsolutions.jts.geom.TopologyException : com.vividsolutions.jts.geom.TopologyException: found non-noded intersection between LINESTRING ( 44.46365 107.13560000000001, 44.46365 -1707.7211500000005 ) and LINESTRING ( 44.46365000000006 -1707.7211500000005, -1847.4122000000002 184.15470000000002 ) [ (44.46365, -1707.7211500000005, NaN) ]

**Comment by dr-jts** [comment]
This works when OverlayNG is used.  In the next release this will be the default.

<img width="436" alt="image" src="https://github.com/user-attachments/assets/d0a1d04d-3240-4933-ba39-1e44eaa959ae" />
