### ISSUE TITLE
Please add Latitude and Longitude  in the Descript of Point getX() getY()

### ISSUE THREAD

**Issue by coding-jj** [locationtech/jts#742]
Having multiple tilted X Y Z Coordinates in multiple mathematical Models please clarify in the JavaDoc of the methods which is which:

- getY() = Latitude in Decimal Values
- getX() = Longitude  in Decimal Values

Please clarify in JavaDoc of methods.

**Comment by dr-jts** [comment]
Well, technically speaking JTS doesn't handle geodetic coordinate systems, only planar ones.  So it would potentially be confusing to refer to Latitude and Longitude in the Javadoc.
