### ISSUE TITLE
GeometryPrecisionReducer does not modify Z values

### ISSUE THREAD

**Issue by grimsa** [locationtech/jts#749]
Context:
The application I am working on has a custom 3D geometry model (e.g. `Point3d`, `Polygon3d`, and other classes), and it also relies quite heavily on JTS for 2D operations.

I have had excellent experience writing automated tests for 2D logic where expected geometries are represented in WKT format.
After I learned that WKT format supports Z values as well, my hope was to leverage JTS & WKT for testing 3D geometries too.

I was trying to do something like this:
```
// this would be produced by some business logic under test
Geometry actualGeometry = new WKTReader().read(
    "POLYGON Z((0.0070710678118655 0.0100000000000051 0.0070710678118655, 0.0070710678118655 99.99 0.0070710678118655, 89.99292893218812 99.99 89.99292893218812, 89.99292893218812 0.0100000000000051 89.99292893218812, 0.0070710678118655 0.0100000000000051 0.0070710678118655))"
);

// As our business logic uses FLOATING precision model, we do not want tests to fail
//     due to insignificant changes e.g. when upgrading to a newer JTS version
// The idea was to reduce the precision to 6 decimal places, normalize the geometry,
//     and use this WKT representation to compare against the "expected" value
var stableActualGeometry = GeometryPrecisionReducer.reduce(actualGeometry, new PrecisionModel(1_000_000)).norm();
var stableActualGeometryWkt = new WKTWriter(3).write(stableActualGeometry);
                            // = POLYGON Z((0.007071 0.01 0.0070710678118655, 0.007071 99.99 0.0070710678118655, 89.992929 99.99 89.99292893218812, 89.992929 0.01 89.99292893218812, 0.007071 0.01 0.0070710678118655))
var stableExpectedGeometryWkt = "POLYGON Z((0.007071 0.01 0.007071, 0.007071 99.99 0.007071, 89.992929 99.99 89.992929, 89.992929 0.01 89.992929, 0.007071 0.01 0.007071))";
assertEquals(stableExpectedGeometryWkt, stableActualGeometryWkt);
```

The outcome was unexpected - X and Y values got rounded, but Z did not.

I did not find a way to configure the behavior, but found this comment in `PrecisionModel#makePrecise`:
```
  public void makePrecise(Coordinate coord)
  {
    // optimization for full precision
    if (modelType == FLOATING) return;

    coord.x = makePrecise(coord.x);
    coord.y = makePrecise(coord.y);
    //MD says it's OK that we're not makePrecise'ing the z [Jon Aquino]
  }
```

For my use-case the only workaround I could come up with was to implement a custom `PrecisionModel`:
```
    private static class ZRoundingPrecisionModel extends PrecisionModel {
        public ZRoundingPrecisionModel(double scale) {
            super(scale);
        }

        @Override
        public void makePrecise(Coordinate coord) {
            super.makePrecise(coord);
            // Additionally make Z precise
            if (getType() != FLOATING && Double.isFinite(coord.getZ())) {
                coord.z = makePrecise(coord.z);
            }
        }
    }
```

Is this behavior (Z values not being changed) expected?
If there is something to be fixed, or a new configuration point introduced to support such usage, I'd be happy to contribute a pull request, as long as it is relatively straightforward change.

**Comment by dr-jts** [comment]
`GeometryPrecisionReducer` not modifying Z ordinates is expected behaviour.  The reason is that JTS is a 2D-only API.  So the Z ordinate is not expected to be in the same coordinate system as the XY ordinates, and hence is not subject to the same precision rules.

You can easily write code that will modify the Z ordinate in whatever way is required.  My preference would be to do that post-processing.  `PrecisionModel` isn't really intended to be subclassable, but currently that way works as well as you have discussed.

**Comment by grimsa** [comment]
This answers it, thank you.
I'm closing the issue then.
