### ISSUE TITLE
GeometryFixer might change GeometryType to single instance

### ISSUE THREAD

**Issue by FObermaier** [locationtech/jts#788]
When processing invalid multi geometries with `GeometryFixer`, the return value might change to its respective single instance geometry type.

To me this seems undesireable, especially when using data stores like e.g. PostGis, where you have to define a specific geometry type for a table's geometry colum. 

I propose to add a boolean variable `keepMulti` along with a proper `setKeepMulti(boolean)` method and adjust the `FixMultiXXX` implementations accordingly.

https://github.com/NetTopologySuite/NetTopologySuite/issues/566

**Comment by dr-jts** [comment]
Fixed by #791
