### ISSUE TITLE
`CoordinateList` and `GeometryPrecisionReducer` do not take Z ordinate into account

### ISSUE THREAD

**Issue by xkenmon** [locationtech/jts#801]
`CoordinateList` judges whether it is repeated without considering the z coordinate([code](https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/geom/CoordinateList.java#L147)), is this the expected behavior？

```wkt
POLYGON Z((116.45726159 39.96412692 6.00000008, 116.45726159 39.96412692 4.00000008, 116.45723818 39.96412692 4.00000008, 116.45723818 39.96412692 6.00000008, 116.45726159 39.96412692 6.00000008))
```
For the above input, the first and second coordinates are the same except for the z value. The third and fourth coordinates are also the same. When the precisionReducer.reduce method is called, the 5 coordinates become 3 coordinates, [this code](https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/precision/PrecisionReducerCoordinateOperation.java#L70) will return null, causing the geometry to be Empty after preserving the precision.

It can be reproduced with the following code:
```java
String wkt = "POLYGON Z((116.45726159 39.96412692 6.00000008, 116.45726159 39.96412692 4.00000008, 116.45723818 39.96412692 4.00000008, 116.45723818 39.96412692 6.00000008, 116.45726159 39.96412692 6.00000008))";
Geometry geometry = new WKTReader().read(wkt);
GeometryPrecisionReducer reducer = new GeometryPrecisionReducer(new PrecisionModel(Math.pow(10, 7)));
Geometry afterReduce = reducer.reduce(geometry);
System.out.println(afterReduce);  // POLYGON EMPTY
```

**Comment by dr-jts** [comment]
Yes, it is intentional behaviour that `CoordinateList` checks only the XY value for repeated coordinates.  Also, `GeometryPrecsionReducer` only considers the 2D topology of the inputs.   So the result of the example code is correct.  The 2D topology of the example polygon is collapsed, and so the precision reduction returns an empty polygon to reflect this.
