### ISSUE TITLE
Enveloppe of geometries around antemeridian

### ISSUE THREAD

**Issue by walfrat** [locationtech/jts#817]
Hello, 

Build two shapes, each on their own side of the antemeridian. Get the envelope of the geometry collection -> The enveloppe will not wrap the two shape but instead link only the two nearest point on the X-Axis of both shapes instead of the furthest.

Here is an ASCII Art of the resulting envelope that doesn't wrap both shape but insteanc only wrap on the Y axis while linking the two nearest point on X-Axis.

>                                 __________________________
>            +                  |                           |                    +
>       +                      +|                           |+                          +
>                      +        |___________________________|            +
>                                               |   <- antemeridian here

This is because, the envelope is build simply on the min/max of X/T values. in our case the max X will be the nearest point on the east side of the antemeridian while the min X will be the nearest point on the west side of the antemeridian, which cause the problem.

**Comment by dr-jts** [comment]
Yes, that's expected.  JTS does not handle geodetic coordinate systems.  You might be able to use [Spatial4J](https://github.com/locationtech/spatial4j) instead.

**Comment by walfrat** [comment]
Ok thanks for the answer.
