### ISSUE TITLE
adding point to polygon

### ISSUE THREAD

**Issue by mohammedX6** [locationtech/jts#824]
I want to add a point to the polygon border at some index how I can do that?

**Comment by dr-jts** [comment]
You have to extract the coordinate array, and then create a new array containing the added coordinate, and create a new Polygon.

**Comment by mohammedX6** [comment]
I tried that actually, the problem I have is I need to sort the polygon vertices CCW or C, unfortunately, I have a concave polygon so I can not do the sorting.

**Comment by dr-jts** [comment]
Well, you need to identify some executable criteria that allows deciding where the point should be inserted.  This is use-case specific.

If you provide data or at least a diagram it might be possible to assist further.

**Comment by mohammedX6** [comment]
Sure, In this video I am trying to add points, as you can see in the direction of the points It's working correctly, but it's not working backwards see starting from 00:15 things go wrong

https://user-images.githubusercontent.com/24648104/148105300-4b86b658-8e9d-4c94-a9e7-df064fb3bc4b.mp4

.

**Comment by mohammedX6** [comment]
i am inserting point like this        pointsList.insert(index+1, point);

**Comment by mohammedX6** [comment]
Can use the Orientation of vertices help?

**Comment by dr-jts** [comment]
I would look for the index of the segment which the point is closest to.

**Comment by mohammedX6** [comment]
can you please explain more

**Comment by dr-jts** [comment]
Iterate over the segments in the geometry.   Use `LineSegment` to compute the distance from the candidate insertion point to the segment.  Choose the index of the closest segment.

**Comment by mohammedX6** [comment]
For my use case it's perfectly working, I will update if it's working in all cases, THANK YOU VERY MUCH @dr-jts
