### ISSUE TITLE
WKTReader LINESTRING EMPTY  dimension = 3?

### ISSUE THREAD

**Issue by ebocher** [locationtech/jts#827]
Dear all,

The following codes

```
WKTReader wktReader = new WKTReader();
Point geom = (Point) wktReader.read("POINT EMPTY");
geom.getCoordinateSequence().getDimension()
```
returns 3

```
WKTReader wktReader = new WKTReader();
LineString geom = (LineString) wktReader.read("LINESTRING EMPTY");
geom.getCoordinateSequence().getDimension()
```
returns 3

```
WKTReader wktReader = new WKTReader();
POLYGON geom = (POLYGON) wktReader.read("POLYGON EMPTY");
geom.getCoordinateSequence().getDimension()
```
returns 3

Don't they have to return 2  or -1 ?

**Comment by mprins** [comment]
or throw a `NullPointerException` because an empty geometry does not have ordinates?

**Comment by ebocher** [comment]
PostGIS 3.1 (GEOS)

```
SELECT st_coorddim(ST_GeomFromText('LINESTRING EMPTY'));
```
returns 2

**Comment by dr-jts** [comment]
This is because the default for `WKTReader` is to support the old JTS semantics for WKT coordinates, in which the Z dimension was assumed to be present.  To avoid this you need to use [this method](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/io/WKTReader.html#setIsOldJtsCoordinateSyntaxAllowed-boolean-):
```
wktReader.setIsOldJtsCoordinateSyntaxAllowed(false);
```

**Comment by ebocher** [comment]
Hi @dr-jts,

Tested with JTS 1.18.2
wktReader.setIsOldJtsCoordinateSyntaxAllowed(true);

returns 3

**Comment by dr-jts** [comment]
Thanks.  That's a bug.  I will commit a fix soon.

**Comment by ebocher** [comment]
Thanks

**Comment by dr-jts** [comment]
Unfortunately it doesn't do anything for collections.  Since they don't contain geometries, they don't have coordinate sequences to carry the coordinate dimension.
