### ISSUE TITLE
CubicBezierCurve for open-end LineStrings

### ISSUE THREAD

**Issue by FObermaier** [locationtech/jts#831]
I tested the new `CubicBezierCurve` shape function (nice) and I'm wondering about the result for open end `LineString`s.
Shouldn't the first and the last control point lie on their respective segments, so that the result would look like the red line?
![Bezier](https://user-images.githubusercontent.com/2065346/150492037-e92e8c56-9461-4f77-a627-c2a3ae63851a.png)

**Comment by dr-jts** [comment]
I tried the flatter ends and thought the more curved ends looked nicer.  But really it's a subjective decision.   It can easily be made an option (say via a `setFlatEnds(boolean)` method.

**Comment by dr-jts** [comment]
I'm also thinking of adding the capability to set the control points via a sequence of coordinates giving the location of one control point for each vertex.  For interior vertices the other control point will be a reflection of the given one through the vertex itself.

**Comment by FObermaier** [comment]
Or that the control points are encoded within the LineString?

**Comment by FObermaier** [comment]
The only constraint is that the LineString has 4+n*3 vertices.

**Comment by dr-jts** [comment]
> The only constraint is that the LineString has 4+n*3 vertices.

Got it.  It is a good idea to support fully specifying the control points, to allow obtaining C0 (angles) and C1 (different curves) continuity at vertices, as well as the default C2 (smooth curves).   But I still think providing the control points separately is more flexible.

**Comment by dr-jts** [comment]
I've added ability to specify control points explicitly:
![image](https://user-images.githubusercontent.com/3529053/151043126-bd5f83b3-338c-41a3-8310-052662ec0504.png)


This will be merged soon.

**Comment by FObermaier** [comment]
Yes, I'm fine with the solution.
