### ISSUE TITLE
"Could not parse Geometry from GeoJson string.  Unsupported 'type':Feature" errors

### ISSUE THREAD

**Issue by thisisaaronland** [locationtech/jts#844]
Hi,

I am not a day-to-day Java person so apologies in advance if I am missing something obvious. I am trying to write a simple Dropwizard (jetty) server that I can upload GeoJSON data to and then process using JTS. For example, data like this:

* https://data.whosonfirst.org/102/527/513/102527513.geojson

Which is uploaded/received like this:

```
    @POST
    @Consumes({MediaType.MULTIPART_FORM_DATA + ";charset=utf-8"})
    public Response upload(@FormDataParam("file") InputStream input){

        GeoJsonReader reader = new GeoJsonReader();
        Geometry geom;

        try {
            BufferedReader buf = new BufferedReader(new InputStreamReader(input, StandardCharsets.UTF_8));
            geom = reader.read(buf);
        }

        catch (Exception e){
            return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(e.toString()).build();
        }
```

The problem I am encountering is that the uploads always fail with something like this:

```
org.locationtech.jts.io.ParseException: Could not parse Geometry from GeoJson string.  Unsupported 'type':Feature
```

Which I can tell is failing here:

https://github.com/locationtech/jts/blob/master/modules/io/common/src/main/java/org/locationtech/jts/io/geojson/GeoJsonReader.java#L142-L181

But is confusing when I look at the list of `GeoJsonConstants`:

https://github.com/locationtech/jts/blob/master/modules/io/common/src/main/java/org/locationtech/jts/io/geojson/GeoJsonConstants.java

Am I just missing some encoding requirements somewhere or ... ?

Thanks,

* dropwizard 2.0.28
* jersey.media.multipart 2.29.1
* jts 1.18.2

**Comment by thisisaaronland** [comment]
Update:

Cloning the `GeojsonReader` and `GeojsonConstants` packages in to my own code/namespace makes the problem go away. I have no idea why. The code in question is here:

https://github.com/aaronland/dropwizard-jts-server

**Comment by FObermaier** [comment]
This might have been fixed just recently with #837.

**Comment by thisisaaronland** [comment]
I wondered about that. I have also been having trouble loading the `ConcaveHull` classes and was starting to think that the code in GitHub is ahead of the published bundles in Maven. Do you whether/what the schedule for publishing releases to Maven is?

**Comment by thisisaaronland** [comment]
Closing since this is not actually a bug. I've updated my project to bundle the relevant code:

* https://github.com/aaronland/dropwizard-jts-server#known-knowns
