### ISSUE TITLE
TopologyPreservingSimplifier affected by Map type

### ISSUE THREAD

**Issue by wsw0108** [locationtech/jts#853]
In TopologyPreservingSimplifier.java, 
If I change type of linestringsMap from HashMap to TreeMap, the result for same input geometry will be different.

**Comment by wsw0108** [comment]
- code, [simplify.zip](https://github.com/locationtech/jts/files/8309216/simplify.zip)
- args, `-f qiantangjiang.wkt -iz 4 --preserve-topo=true`, or ``-f qiantangjiang.wkt -iz 4 --preserve-topo=true -sort-lines`

**Comment by dr-jts** [comment]
Yes, the result could be affected by ordering. It is not guaranteed to be deterministic.  I don't see a problem here?
