### ISSUE TITLE
Unexpected Intersection Result

### ISSUE THREAD

**Issue by fosskers** [locationtech/jts#86]
Hi, while doing some innocent intersections I came upon a surprising result.

### Attempted

Intersect `LINESTRING (0 0, 1000 1, 2000 0, 3000 1, 4000 0)` twice, once each with the following Polygons which represent (contrived) extents:

- `POLYGON ((0 0, 0 2500, 2500 2500, 2500 0, 0 0))`
- `POLYGON ((2500 0, 2500 2500, 5000 2500, 5000 0, 2500 0))`

### Expected Result

LEFT INTERSECT: `LINESTRING (0 0, 1000 1, 2000 0, 2500 0.5)`
RIGHT INTERSECT: `LINESTRING (2500 0.5, 3000 1, 4000 0)`

### Actual Result

LEFT INTERSECT: `MULTILINESTRING ((0 0, 1000 1, 2000 0), (2000 0, 2500 0.5))`
RIGHT INTERSECT: `LINESTRING (2500 0.5, 3000 1, 4000 0)`

I suppose no data has been *lost* per se, but the MultiLine result for the left intersect (where it doesn't happen with the right) is unexpected. Thoughts?

**Comment by fosskers** [comment]
If we make the original `LineString` more jagged, we get what we expect:

```
ORIG: LINESTRING (0 1000, 1000 1500, 2000 1000, 3000 1500, 4000 1000)
EXTENT 1: POLYGON ((0 0, 0 2500, 2500 2500, 2500 0, 0 0))
EXTENT 2: POLYGON ((2500 0, 2500 2500, 5000 2500, 5000 0, 2500 0))
LEFT INTERSECT: LINESTRING (0 1000, 1000 1500, 2000 1000, 2500 1250)
RIGHT INTERSECT: LINESTRING (2500 1250, 3000 1500, 4000 1000)
```

**Comment by dr-jts** [comment]
This is because the overlay methods (intersection etc) do not "sew together" linestring results.  In other words, the result is split at all intersections between the geometries.  This is done because merging the results incurs an additional performance penalty, so it is left to the caller to decide whether to do this.

This sounds like a good FAQ question!

**Comment by jnh5y** [comment]
Can we add this to a FAQ and close this issue?

**Comment by dr-jts** [comment]
Yes, that is a good way to capture this information.
