### ISSUE TITLE
Is there some kind of makeValid function for converting invalid polygons into multipolygons?

### ISSUE THREAD

**Issue by skylarjhdownes** [locationtech/jts#87]
Hello all,

I'm working with a complex set of generated polygons, and I've been searching for a consistent way to transform invalid polygons into sets of valid ones.  So far I've found [this SO post](http://stackoverflow.com/questions/31473553/is-there-a-way-to-convert-a-self-intersecting-polygon-to-a-multipolygon-in-jts), and seen that the version of JTS that Geotools is using [has a makeValid function](https://github.com/geotools/geotools/blob/0e6fc022f395194e7670b63d2de785123a178cdf/modules/library/api/src/main/java/org/geotools/geometry/jts/JTS.java#L1559) that seems to work okay but interacts somewhat oddly with holes.  I've also tried the polygon.buffer(0); trick, but that seems sub-optimal for the reasons outlined in the SO post above.

Is there a recommended approach to this?  I'm pretty new to JTS in general, so any pointers in the right direction would be appreciated.  Thanks!

**Comment by mukoki** [comment]
Hello,
If you want to compare, I've also implemented such a function based on JTS in OpenJUMP code :  https://sourceforge.net/p/jump-pilot/code/HEAD/tree/core/trunk/src/com/vividsolutions/jump/geom/MakeValidOp.java

The code is easily testable through OpenJUMP user interface (OpenJUMP 1.10).
It is quite difficult to define precisely what MakeValid should do in any case. The method has some options to help the user get what he wants. There are some places where it may be improved though (like avoiding the use of symDifference).
Anyway, I did not know there was a method in geotools and a comparison would be useful as a robust and fast MakeValid method would be a nice addition for JTS.

**Comment by skylarjhdownes** [comment]
As it turns out, [VWSimplifier.simplify()](https://github.com/locationtech/jts/blob/f6187ee22aee29933c561284e1cb56df32fddcc0/modules/core/src/main/java/org/locationtech/jts/simplify/VWSimplifier.java#L59) is good enough for my purposes, at least guaranteeing valid polygons as output.  I'll leave the issue open for the moment though, since it seems like a .makeValid() function would be a useful addition.

**Comment by dr-jts** [comment]
See this function for another option:  https://github.com/locationtech/jts/commit/315fb5fd6dcf034ab88d065b229dd3534f4e24c5

This should soon be moved into core as a `MakeValid` class.

**Comment by dr-jts** [comment]
See also #652

**Comment by dr-jts** [comment]
This functionality is now provided in the `GeometryFixer` class (#704).
