### ISSUE TITLE
Buffer behaviour for closed LineStrings

### ISSUE THREAD

**Issue by mwtoews** [locationtech/jts#877]
Testing with JTS 1.18.3 or since GEOS 3.9.x the buffer behavior changed for closed LineStrings. For example:

    LINESTRING (-13 8, 13 4, 14 -15, -16 -9, -13 8)

Buffer(5) is expected:
![image](https://user-images.githubusercontent.com/895458/171086096-864615d8-1f2c-4b61-bdcd-3dd499b2850e.png)

Buffer(25) is expected:
![image](https://user-images.githubusercontent.com/895458/171085846-2d456434-2a19-4cd4-b0c2-4cc32520bbf1.png)

Buffer(27) has unexpected interior:
![image](https://user-images.githubusercontent.com/895458/171085867-3d83c1a6-0e39-4818-8032-94d609145318.png)

Buffer(35) has unexpected interior that intersects part of the input:
![image](https://user-images.githubusercontent.com/895458/171085752-6c0fa751-8093-4123-8bb3-a3a5ccb94149.png)

Buffer(60) has unexpected interior that contains the input:
![image](https://user-images.githubusercontent.com/895458/171086283-59541d1a-4da5-4ee1-b152-67fc5362a97c.png)

This is a regression since older versions, e.g. JTS 1.15 (not sure exactly when) or GEOS 3.8.1, which get expected results for each example.

(Also, for reference this started from a discussion at https://github.com/shapely/shapely/discussions/1405)

**Comment by mwtoews** [comment]
Also, there's nothing particularly unique with the example. For something different, see `LINESTRING (0 0, 0 5, 5 5, 5 0, 0 0)` with buffer(10).
![image](https://user-images.githubusercontent.com/895458/171088272-fad895f8-dae2-49fb-80e4-dae6c3be19f3.png)

**Comment by mwtoews** [comment]
Doing a few version bisections, I've discovered that this regression was introduced with JTS [1.17.0](https://github.com/locationtech/jts/releases/tag/1.17.0).

**Comment by mprins** [comment]
This seems a duplicate of #876

**Comment by mwtoews** [comment]
Thanks, it is a duplicate!

**Comment by dr-jts** [comment]
Thanks for the detailed bug report.  A fix has been found and a patch will be in place soon (in JTS and GEOS).
