### ISSUE TITLE
Polygon Offset Example

### ISSUE THREAD

**Issue by nsiatras** [locationtech/jts#879]
Hello,

I am wondering if there is any example on how to perform polygon offsetting.

I have a double[][] array with the polygon vertices points in clockwise order and I want to inflate it by 2mm.
Is there any example code on how to perform the offseting ?

Thank you in advance

**Comment by nsiatras** [comment]
I found it

**Comment by CodeK1988** [comment]
So how?and thank you

**Comment by CodeK1988** [comment]
@nsiatras @dr-jts

**Comment by michaelkirk** [comment]
Probably you want to use the buffer functionality: http://www.tsusiatsoftware.net/jts/javadoc/com/vividsolutions/jts/geom/Geometry.html#buffer%28double%29
