### ISSUE TITLE
STRtree.nearestNeighbour with K throws NPE for empty tree

### ISSUE THREAD

**Issue by ashr123** [locationtech/jts#881]
```java
java.lang.NullPointerException
	at org.locationtech.jts.index.strtree.BoundablePair.distance(BoundablePair.java:94)
	at org.locationtech.jts.index.strtree.BoundablePair.(BoundablePair.java:48)
	at org.locationtech.jts.index.strtree.STRtree.nearestNeighbour(STRtree.java:523)
```
STRtree's internal structure and logic doesn't protect itself when the tree is empty.
(Version 1.18.2)

**Comment by dr-jts** [comment]
This is odd, because there is a [unit test](https://github.com/locationtech/jts/blob/master/modules/core/src/test/java/org/locationtech/jts/index/strtree/STRtreeNearestNeighbourTest.java#L31) for this situation.

Can you provide code that demonstrates the issue?

**Comment by ashr123** [comment]
I'm referring to `org.locationtech.jts.index.strtree.STRtree#nearestNeighbour(org.locationtech.jts.geom.Envelope, java.lang.Object, org.locationtech.jts.index.strtree.ItemDistance, int)` (with 4 parameters, there I can't see this check
in addition, can I suggest that You won't return `null` but `new Object[0]`?

**Comment by dr-jts** [comment]
Right, I see the problem now.  And agreed that returning `Object[0]` is nicer.
