### ISSUE TITLE
Extract LineStrings from Buffered GeometryCollection ??

### ISSUE THREAD

**Issue by nsiatras** [locationtech/jts#883]
Hello,

I have a GeometryCollection filled with LineString.
I use the **GeometryCollection.buffer** method to buffer it, but the return type is Geometry.

Is there any possible way to extract the original LineStrings from the buffered Geometry ?

Thank you in advance

**Comment by dr-jts** [comment]
The reason that the `Geometry.buffer` method returns a `Geometry` is that it can return both `Polygon` and `MultiPolygon`, and their only common superclass is `Geometry`.  

If you are asking whether you can somehow find the "centre" lines from a polygon that is a buffer, the answer is no, JTS does not contain an algorithm to do this.  Algorithms such as Medial Axis can do something approximating this, although it is not exact.
