### ISSUE TITLE
Change  Coodinate  to  byte[] or double[]

### ISSUE THREAD

**Issue by 13661172102** [locationtech/jts#901]
For large geometry, there is a lot of points,     then a lot of Coodinate  Object.    It takes multiple memory than byte[] or double[].

I know use Coodinate make the code readable. But i think performance is more important in future, because the spatial data size increase very fast.

**Comment by dr-jts** [comment]
This is why [`PackedCoordinateSequence`](https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/geom/impl/PackedCoordinateSequence.java) exists.

**Comment by 13661172102** [comment]
thanks u , it means a lot. I will try to extend [PackedCoordinateSequence](https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/geom/impl/PackedCoordinateSequence.java) for my own @dr-jts

**Comment by 13661172102** [comment]
@dr-jts  i have tried to use [PackedCoordinateSequence](https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/geom/impl/PackedCoordinateSequence.java) .  But I found that when i do something like intersection ， the toCoordinateArray() of PackedCoordinateSequence will be called.  Then double[] turns to Coordinate[] again and the memory use is largger than before because double[] and Coordinate[] both exists.

**Comment by dr-jts** [comment]
The `Coordinate[]` should only exist while the computation is happening, and then be freed.
