### ISSUE TITLE
GeometryFixer convert XY coordinates to XYZ coordinates after fixing polygon

### ISSUE THREAD

**Issue by chenhh021** [locationtech/jts#919]
After fixing Polygons with `GeometryFixer.Fix(geom)`, all coordinates are changed from XY to XYZ where Z = NaN. It can be reproduced by the test below.

```
WKTReader reader = new WKTReader();
reader.setIsOldJtsCoordinateSyntaxAllowed(false);

Geometry geom = read(reader, "POLYGON((0 0, 1 0.1, 1 1, 0.5 1, 0.5 1.5, 1 1, 1.5 1.5, 1.5 1, 1 1, 1.5 0.5, 1 0.1, 2 0, 2 2,0 2, 0 0))");
// the following assert passes
assertEquals(2, CoordinateArrays.dimension(geom.getCoordinates()));

Geometry fix = GeometryFixer.fix(geom);
// the following assert fails because coordinates are converted to 3d
assertEquals(2, CoordinateArrays.dimension(fix.getCoordinates()));
```

I think `GeometryFixer` should keep the dimension when the original coordinates are 2d. Is this a bug?

I am trying to find out the code causing this. By the way, I am new to this repository, I would appreciate it if anyone told me what I can do to help solve this problem.

Thanks in advance!

**Comment by dr-jts** [comment]
Yes, preserving Coordinate dimension is definitely a design goal.  Unfortunately JTS is not very good at doing that right now.

It will take some fairly deep code inspection, and perhaps tracing through with the debugger, to find out where the dimension change is happening.

**Comment by chenhh021** [comment]
Thanks for the advice.

I find dimension change happens when copy coordinates by creating new `Coordinates`.  One of the involved methods is `OffsetCurveBuilder.copyCoordinates`. Use` Coordinates.copy()` instead may solve the problem.

```
private static Coordinate[] copyCoordinates(Coordinate[] pts)
  {
    Coordinate[] copy = new Coordinate[pts.length];
    for (int i = 0; i < copy.length; i++) {
      copy[i] = new Coordinate(pts[i]); // dimension change happens here
     //one possible solution
     //copy[i] = pts[i].copy(); 
    }
    return copy;
  }
```

Many other methods are also involved. It's more complicated than expected, I think I need to inspect a little longer.

**Comment by chenhh021** [comment]
[PR](https://github.com/locationtech/jts/pull/922) created. @dr-jts Could you please take a review?
