### ISSUE TITLE
Make DistanceOp pluggable to override distance calculations

### ISSUE THREAD

**Issue by RichMacDonald** [locationtech/jts#929]
One of the common uses of JTS is to perform geospatial calculations. This entails:

1. Converting from geospatial coordinates to geometric coordinates using a "map-projection".
2. Performing the geometric calculations.
3. Perform the "inverse-map-projection" to convert the results from geometric coordinates to geospatial coordinates.

The particular map-projection is all-important, as some distortion is inevitable. No map-projection can preserve shape and distance simultaneously.

There are projections that are accurate for point-to-point, point-to-line, and line-to-line. When the line is a "great circle", that is. If the line is not a great circle, say a rhumb line, then it is common to linearize the line to make the distances short enough so that the approximation is accurate enough.

However, there are no projections that are accurate for point-to-polygon (anything-to-polygon). The common approach is to find a "pretty good map projection" and accept the inevitable inaccuracy.

However, polygon distance _can_ be made accurate by changing the projection for each line-segment. (Ignore the polygon containment issue for now.) The technique is to use "gnomonic projection that is re-centered on the closest-point".

In essence, different map-projections must be used for each point/line component within the geometry.

Which is a long-winded way of saying that the org.locationtech.jts.operation.distance.DistanceOp needs to delegate its distance calculations to a second component that is geospatially-aware.

I have a working branch at [org.locationtech.jts.operation.distance](https://github.com/RichMacDonald/jts/tree/DistanceOp) that demonstrates the concept. The existing Cartesian operations have been refactored to a default delegate class, so normal operation remains unchanged.

I have included some minor generics improvements in that branch. I am not yet experienced with the code cleanup and comment requirements of the master branch, so that part is not ready.

**Comment by dr-jts** [comment]
Have you looked at [Spatial4J](https://github.com/locationtech/spatial4j)?  Does it implement this functionality?

**Comment by dr-jts** [comment]
Why not use a true geodetic distance calculation?

**Comment by dr-jts** [comment]
Is pluggable distance really the only thing needed to compute accurate geodetic distances?  What about spheroidal wrap-around?

**Comment by RichMacDonald** [comment]
> Have you looked at [Spatial4J](https://github.com/locationtech/spatial4j)? Does it implement this functionality?

Primitively. It supports the spherical model, not the ellipsoidal model. And that project is pretty dead, I am afraid.

**Comment by RichMacDonald** [comment]
> Why not use a true geodetic distance calculation?

I am. My subclass of DistanceSupport delegates to geodesic models. From a [FAST model](https://github.com/mapbox/cheap-ruler), to a GOOD model (spherical haversine), to a [BEST model](https://geographiclib.sourceforge.io/). That latter model provides point-to-point, point-to-greatcircle, and greatcircle-to-greatcircle. But each calculation requires a gnonomonic projection centered at the intersection-point (iterative). So it is impossible to project a Polygon: Each line-segment needs a separate projection.

**Comment by RichMacDonald** [comment]
> Is pluggable distance really the only thing needed to compute accurate geodetic distances? What about spheroidal wrap-around?

I roll my own to deal with that. (Spatial4j does it as well.) My shapes in the geodesic model produce Geometry instances that are split across the antimeridian. Then JTS to work on those instances.

**Comment by dr-jts** [comment]
I suggest making your own version of `DistanceOp` which is pluggable.  Incorporating it into the main JTS codebase seems like adding complexity for a narrow and undocumented use case.

**Comment by RichMacDonald** [comment]
As long as no one ever makes changes to the existing DistanceOp, that will be fine.

What kind of documentation are you looking for? This is the math behind my issue. And the problem of distance-vs-map-projections is ancient.
https://link.springer.com/article/10.1007/s00190-012-0578-z (read pg 54)

FWIW, the PostGIS team uses GEOS, the C++ port of JTS. They have the same basic application I have, although they don't implement the rigor I am looking for. Afaik, they use the standard approach, which is to pick a "close but not perfect" map projection, then project the entire geometry from geospatial to cartesian coordinates. Thus no need to customize DistanceOp.

**Comment by RichMacDonald** [comment]
Anyone interested in this can pick it up from my fork at https://github.com/RichMacDonald/jts
