### ISSUE TITLE
Request: Alpha Shapes implementation

### ISSUE THREAD

**Issue by fosskers** [locationtech/jts#93]
I came upon a problem to which [Alpha Shapes](https://en.wikipedia.org/wiki/Alpha_shape) (not Convex Hull) was the answer. I found [this post on the GIS Stackexchange](http://gis.stackexchange.com/a/1209/94132), where it was mentioned that this feature has been desired in JTS for a long time.

Is there any plan to implement it? Thank you kindly.

**Comment by mukoki** [comment]
Maybe you can have a look at this implementation from Eric Grosso based on JTS :
http://www.rotefabrik.free.fr/concave_hull/

**Comment by fosskers** [comment]
Thanks! We ended up taking a different approach, but that link could be helpful to anyone who wanders by here in the future.

**Comment by dr-jts** [comment]
See #823
