### ISSUE TITLE
Misleading AffineTranformation public constructor

### ISSUE THREAD

**Issue by rddesmond** [locationtech/jts#932]
`AffineTranformation` has a 6-point constructor with no implementation.  Thought the user should be using the builder or factory, the existing constructor looks as if it would be functional.  It is not.  Ideally, the constructor would be removed, but to maintain backwards compatibility it could just have a `@Deprecated` annotation and java doc updated.  It could be made to function, throw an exception, or continue to be a no-op.

```java
  /**
   * Constructs a transformation
   * which maps the given source
   * points into the given destination points.
   * 
   * @param src0 source point 0
   * @param src1 source point 1
   * @param src2 source point 2
   * @param dest0 the mapped point for source point 0
   * @param dest1 the mapped point for source point 1
   * @param dest2 the mapped point for source point 2
   * 
   */
  public AffineTransformation(Coordinate src0,
      Coordinate src1,
      Coordinate src2,
      Coordinate dest0,
      Coordinate dest1,
      Coordinate dest2)
  {
  }
```

https://github.com/locationtech/jts/blame/0ccdd9fc8465c66b1352917431eda27d714df74f/modules/core/src/main/java/org/locationtech/jts/geom/util/AffineTransformation.java#L308-L328

**Comment by dr-jts** [comment]
Agreed.  In fact, the entire AffineTransformation API is too wide. Most constructors should be package-private, and the API limited to `AffineTransformationFactory` and (perhaps) the `AffineTransformation` create functions.

**Comment by rddesmond** [comment]
Whoa, this is great!  Thank you for your incredible contributions to JTS!
