### ISSUE TITLE
Information about license header is missing

### ISSUE THREAD

**Issue by FObermaier** [locationtech/jts#94]
The [guidelines for contributing](https://github.com/locationtech/jts/blob/master/CONTRIBUTING.md) to this repository are lacking information that __all__ source code files should have a license header and especially how it should look like.

**Comment by jnh5y** [comment]
@FObermaier does https://github.com/locationtech/jts/pull/99 help clarify?

**Comment by dr-jts** [comment]
Fixed by #99
