### ISSUE TITLE
Too many compile time dependencies?

### ISSUE THREAD

**Issue by karussell** [locationtech/jts#95]
Are these dependencies really necessary to build JTS? https://github.com/locationtech/jts/blob/master/pom.xml#L94-L117

junit is probably just for `test` scope and what about the oracle driver - should it be `provided`?

**Comment by mprins** [comment]
`dependencyManagement` is just that, these are not actual dependencies, is a managed list of dependencies so versions can be managed for child projects, the children can specify/override things like `scope`

**Comment by karussell** [comment]
Ups, sorry for the noise
