### ISSUE TITLE
OffsetCurveBuilder or OffsetCurve how set direction

### ISSUE THREAD

**Issue by CodeK1988** [locationtech/jts#958]
i want left offset or right offset.with distance.

OffsetCurveBuilder
ocb.getOffsetCurve(lineDrawable.getGeometry().getCoordinates(), 10000 / NEARNESS_FACTOR);  1000 work fine.
ocb.getOffsetCurve(lineDrawable.getGeometry().getCoordinates(), -10000 / NEARNESS_FACTOR); -10000 not working.
pls, thanks

**Comment by dr-jts** [comment]
Use `OffsetCurve` to compute offset curves.  `OffsetCurveBuilder` is now intended to be only for internal use.

**Comment by CodeK1988** [comment]
@dr-jts bro, OffsetCurve not support set direction? when i set distance value = -XXXX, i see the method inside used Math.abs, so how should i do?  thanks!

**Comment by dr-jts** [comment]
`OffsetCurve` uses the sign of the offset distance to indicate whether the offset is constructed on the left or the right side of the input.

**Comment by CodeK1988** [comment]
get it.  getCurveJoined method! thanks for reply

**Comment by CodeK1988** [comment]
OffsetCurve  getCurve distance  positive not working,

**Comment by dr-jts** [comment]
You'll have to provide input data and perhaps a code snippet that demonstrates this.
