### ISSUE TITLE
Bad calculations with geometries in the 180 meridian (anti-meridian)

### ISSUE THREAD

**Issue by UnaiUribarri-TomTom** [locationtech/jts#972]
Let us define a rectangle that centred on the 180 meridian, with the north-west corner at latitude 1, longitude 179 and the east-south corner at latitude -1, longitude -179.

Some geometry calculations over this rectangle are invalid: 
 * the centroid is in the 0 meridian instead of the 180 meridian
 * the envelope generated instead of being the given rectangle it covers the rest of the world, with latitudes from -179 to 179 instead of from 179 to -179.

**Comment by mprins** [comment]
AFAIK JTS is not aware of projections and works in a Cartesian space so this is expected IMO.

see also: https://locationtech.github.io/jts/jts-faq.html#F1
