### ISSUE TITLE
calling getX to set the minY?

### ISSUE THREAD

**Issue by aocalderon** [locationtech/jts#983]
Just to confirm if it is correct... I think it should call getY() instead of getX()...

https://github.com/locationtech/jts/blob/5d3de32bd361e19a9d5660958c1ca48ce8d06970/modules/core/src/main/java/org/locationtech/jts/index/hprtree/HilbertEncoder.java#L32

**Comment by dr-jts** [comment]
Good find!  A copy-and-paste error, of course.  Will fix soon.

**Comment by dr-jts** [comment]
Fixed by https://github.com/locationtech/jts/commit/2d2a1a966491c3dd1381bd4fcf2923b5872ef53c
