### ISSUE TITLE
intersection returns incorrect result if polygon passes the pole area

### ISSUE THREAD

**Issue by MansoorAhmadi** [locationtech/jts#991]
The intersection between two polygons or multi-polygons return an incorrect result when a polygon passes or if it's located on the pole. 

We read the polygon coordinates using the WKT reader and insect using the Geometry class.

  WKTReader reader = new WKTReader(jtsGeometryFactory);
  Geometry polygon1 = reader.read(myFirstPolygonAsString);
  Geometry polygon2 = reader.read(mySecondPolygonAsString);

  Geometry intersection = polygon1.intersection(polygon2);
  if (polygon1.intersects(polygon2)) {
      list.add(matched polygon);
  }

Please, find attached a full report [with screenshots] of the bug. 

We remain available, shall you have any questions.

Thank you
[Geometry bug report-revised.pdf](https://github.com/locationtech/jts/files/12094887/Geometry.bug.report-revised.pdf)

**Comment by dr-jts** [comment]
As mentioned in the FAQ [here](https://locationtech.github.io/jts/jts-faq.html#F1), JTS only supports planar coordinate systems, not geodetic ones.   So I think your expectation of what the results should be is incorrect.

**Comment by MansoorAhmadi** [comment]
Ok. 
Thank you. for your reply.
