### ISSUE TITLE
[INFO] JTS is now part of JCSG as the triangulation engine

### ISSUE THREAD

**Issue by madhephaestus** [locationtech/jts#993]
First, thank you for this awesome library!

I wanted to let you know i have removed the internal triangulation code from my CSG library and replaced it with JTS. Your triangulation algorithm's are both faster and also more robust to junk inputs (produced by CSG operations). 

https://github.com/NeuronRobotics/JCSG

**Comment by dr-jts** [comment]
Excellent!  Glad JTS is helping you out.
